### ISSUE TITLE
tender.status guidance for multi-lot processes

### ISSUE THREAD

**Issue by odscjen** [open-contracting/european-union-support#103]
Some guidance is needed to explain how to deal with `tender.status` for processes that have multiple `lots` that may each have a different `status`

**Comment by jpmckinney** [comment]
We can perhaps omit most of the guidance with respect to `tender.status`, as the direction in https://github.com/open-contracting/standard/pull/1509 and https://github.com/open-contracting/standard/pull/1160 is to deprecate `status`, and to only have `finalStatus` fields. Most values of `status` can be determined independently by comparing available dates (planned, active, complete) , leaving only the final statuses (cancelled, unsuccessful, withdrawn).

**Comment by jpmckinney** [comment]
Noting that BT-03 and BT-756 (PIN Competition Termination) map to `tender.status`. Those mappings are fine with respect to multi-lot processes.
