### ISSUE TITLE
BT-747 Selection Criteria Type codelist

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/european-union-support#106]
Similar to the [awardCriterionType](https://extensions.open-contracting.org/en/extensions/awardCriteria/master/codelists/#awardCriterionType.csv) codelist in the awardCriteria extension, we'll need to author a selectionCriterionType codelist based on the [selection-criterion](https://op.europa.eu/en/web/eu-vocabularies/concept-scheme/-/resource?uri=http://publications.europa.eu/resource/authority/selection-criterion) authority table.

**Comment by odscjen** [comment]
These codes already map perfectly the the [selectionCriteriaType](https://extensions.open-contracting.org/en/extensions/selectionCriteria/master/codelists/) codelist in the Selection Criteria extension. So the mapping table will look like:

Code,Label,OCDS code,OCDS label
ef-stand,Economic and financial standing,economic,Economic
other,Other,other,Other
sui-act,Suitability to pursue the professional activity,suitability,Suitability
tp-abil,Technical and professional ability,technical,Technical

**Comment by odscjen** [comment]
mapping table created in https://github.com/open-contracting/european-union-support/commit/0869e81a90704c9c57188f2be888a6d7c34a92eb

**Comment by duncandewhurst** [comment]
@odscjen does the mapping table need to be explicitly referenced in the mapping for BT-747-Lot?

**Comment by duncandewhurst** [comment]
> @odscjen does the mapping table need to be explicitly referenced in the mapping for BT-747-Lot?

The answer is yes - I'll make the update.
