### ISSUE TITLE
Use consistent language for business terms that map to properties of objects in arrays

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/european-union-support#108]
Based on https://opencontractingint.slack.com/archives/C03S8JL100P/p1661214078013339, we should use the following construction:

> These values are mapped to the same `<object>` objects as created for BT-##.
>
> For each `foo`, add or update a corresponding `<object>` in the <parent object>'s `.bar` array and map to...

For example, for **BT-5071-Lot**:

> These values are mapped to the same `Address` objects as created for BT-728-Lot, BT-5131-Lot, BT-5121-Lot, BT-5071-Lot, BT-727-Lot, BT-5101-Lot and BT-5141-Lot.
>
> For each `<cac:RealizedLocation>`, add or update the corresponding `Address` object in the item's `.deliveryAddresses` array and map to its `.region`.

Currently, the guidance for some business terms omits the second sentence.

**Comment by duncandewhurst** [comment]
Sounds good! Should be an easy find and replace.

**Comment by odscjen** [comment]
Great, find and replace done :)

**Comment by odscjen** [comment]
issue with BT-727 and BT-728 https://github.com/open-contracting/european-union-support/issues/160

**Comment by odscjen** [comment]
With the exception of the fields mentions in #160 all instances of this are now consistent so closing this issue
