### ISSUE TITLE
eForms version 1.1.0/1.1.1

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/european-union-support#109]
There were two new eForms versions in the last couple of weeks. According to the [changelog](https://github.com/OP-TED/eForms-SDK/blob/develop/CHANGELOG.md), the eForms metadata in version 1.1.1 is identical to version 1.1.0. However, some of the [changes in 1.1.0](https://github.com/OP-TED/eForms-SDK/blob/1.1.0/CHANGELOG.md) might affect the mapping:

> * New elements were added in the eForms schemas, and a few elements were removed.
> * Several new codelists were added.

Changes to the eForms regulation are also coming:

> An amendment to the [eForms Regulation](https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:32019R1780) will be published in the near future. This amendment includes changes to Annex II. It introduces new Business Terms, and modifies some existing Business Terms, affecting names, descriptions and rules.
> 
> Some of those changes have been implemented in this release, and correspond to most of the changes listed above. The remaining changes will be implemented in a future release.

There's no list of specific changes in the changelog. @jpmckinney can you rerun the script to update `guidance.yaml` so that we can see what the changes are?

**Comment by jpmckinney** [comment]
I've already made the upgrade to 1.1.0: https://github.com/open-contracting/european-union-support/compare/5af7784..102cc7d

2cf63a4bdf6f270e6f3854f1b8290a457e89a1f0 is the most relevant commit. I don't think the update affects any existing mappings. It does add a few new fields.

**Comment by duncandewhurst** [comment]
Great. Thanks!

Looking at the diff in https://github.com/open-contracting/european-union-support/commit/2cf63a4bdf6f270e6f3854f1b8290a457e89a1f0, I think we'll need to recheck the mapping for `BT-5011-Contract` so I'll leave this issue open as a reminder to do that.

**Comment by odscjen** [comment]
Does something else also need updating to accommodate 1.1.1. On running the lint I'm getting the error "404 Client Error: Not found for url: hrrps://dics.ted.europa.eu/eforms/1.1.0/schema/all-in-one.htlm

**Comment by jpmckinney** [comment]
Hmm, `hrrps` and `htlm` seem to be typos.

**Comment by odscjen** [comment]
sorry! that's what I get for writing comments at the end of a long week. those typos are just in my message, the error I'm getting is "404 Client Error: Not Found for url: https://docs.ted.europa.eu/eforms/1.1.0/schema/all-in-one.html"
