### ISSUE TITLE
Reliance on identifiers

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/european-union-support#111]
In order to identify which objects to update in OCDS, the proposed common operations guidance in https://github.com/open-contracting/european-union-support/issues/54 relies on mapping several identifiers from eForms to `id` fields in OCDS.

In order to determine whether it is possible to rely on these identifiers being unique, I've pulled together the information available in the eForms SDK docs into the following table (emphasis added):

| Business Term | Name | Description | Comment | XPaths | Mapping |
| -- | -- | -- | -- | -- | -- |
| OPT-200 | Company Technical Identifier |  Identifier used in the notice to refer to the Organization | **Unique** technical identifier ORG-XXXX | `efac:Company/cac:PartyIdentification/cbc:ID`, `cac:ContractingParty/cac:Party/cac:PartyIdentification​/cbc:ID` | `Organization.id` |
| OPT-201 | TouchPoint Technical Identifier | Identifier used in the notice to refer to the alternate contact details associated to a specific role/subrole | **Unique** technical identifier TPO-YYYY |  `efac:TouchPoint​/cac:PartyIdentification​/cbc:ID` | `Organization.id` |
| OPT-202 | Beneficial Owner Technical Identifier | Identifier used in the notice to refer to the Ultimate Beneficial Owner | | `efac:UltimateBeneficialOwner/cbc:ID` | `Person.id` |
| OPT-322 | LotResult Technical ID | **Unique** identifier for the LotResult. Shall follow the scheme "RES-XXXX". | | `efac:LotResult/cbc:ID` | `Award.id` |
| BT-137 | Purpose Lot Identifier | Encoded by the Contracting Authority in accordance with the prescribed format. | |`cac:ProcurementProjectLot/cbc:ID`, `efac:LotResult/efac:TenderLot​/cbc:ID` | `Lot.id` |

The [introduction](https://docs.ted.europa.eu/eforms/1.0.0/schema/all-in-one.html#_introduction) also mentions that, for BT-137:

> These technical identifiers are **unique within a notice and may not evolve (i.e. the same Lot will have the same technical identifier from the start to the end of the procurement procedure).**

Therefore, only OPT-202 isn't explicitly declared as unique. I don't know if the [schematron files](https://github.com/OP-TED/eForms-SDK/tree/develop/schematrons) might contain additional uniqueness rules.

@jpmckinney based on the above, are you happy to stick with the guidance as drafted in https://github.com/open-contracting/european-union-support/issues/54?

**Comment by jpmckinney** [comment]
Yes, let's assume OPT-202 is unique. We can perhaps make note of this assumption.

**Comment by duncandewhurst** [comment]
Great. Will do.

**Comment by duncandewhurst** [comment]
Noting that all of the fields for the above business terms are mandatory, with the exception of `BT-137-LotsGroup`

**Comment by duncandewhurst** [comment]
> Yes, let's assume OPT-202 is unique. We can perhaps make note of this assumption.

I've added a note to [Get the person for an ultimate beneficial owner](https://github.com/open-contracting/european-union-support/blob/main/output/content/eforms/operations.md#get-the-person-for-an-ultimate-beneficial-owner).
