### ISSUE TITLE
BT-195, BT-196, BT-197, BT-198: Unpublished information

### ISSUE THREAD

**Issue by odscjen** [open-contracting/european-union-support#112]
eForms allows publishers to keep [certain BTs publicly unpublished for a defined period of time](https://docs.ted.europa.eu/eforms/1.1.1/schema/all-in-one.html#withheldPublicationOfInformationSection). This is accomplished using an "unpublished" / 'FieldsPrivacy' block made up of 4 BTs:

- BT-195: a set of codes, each of which maps exclusively to another BT (e.g. 'not-val' maps to BT-161)
- BT-196: a free-text field describing the justification for withholding the information
- BT-197: a code ([5 to select from](https://op.europa.eu/en/web/eu-vocabularies/concept-scheme/-/resource?uri=http://publications.europa.eu/resource/authority/non-publication-justification)) justifying the publication delay/withholding of the BT
- BT-198: the date the BT will become accessible.

```
<efac:FieldsPrivacy>
    <efbc:FieldIdentifierCode listName="non-publication-identifier">not-val</efbc:FieldIdentifierCode>
    <cbc:ReasonCode listName="non-publication-justification">oth-int</cbc:ReasonCode>
    <efbc:ReasonDescription languageID="ENG">Information delayed publication because of ...</efbc:ReasonDescription>
    <efbc:ReasonDescription languageID="FRA">Publication de l'information ajournée parce que ...</efbc:ReasonDescription>
    <efbc:PublicationDate>2025-03-31+01:00</efbc:PublicationDate>
</efac:FieldsPrivacy>
```

If a BT is to be unpublished all 4 of these fields are mandatory.

I can't find in any of the documentation whether or not this unpublished block will be publicly published to allow users to see what's been withheld, why, and when it'll become available. But from an OCDS point-of-view it does seem like this is information that should be published for transparency.

I couldn't see a way to currently include this in OCDS. I suggest we create a new extension called something like "Withheld Information" made up of a `withheldInformation` array populated with `withheldBusinessTerm` objects. BT-196, BT-197 and BT-198 could map directly to fields in these objects, and BT-195 could be mapped to two, one to name the affected BT and another to give either its name or its description. I looked over the BT's that it is possible to withhold and they don't all map directly to a single unique OCDS field so this 
cannot be used as the identifier in the proposed object. So what I'm suggesting looks like this:
```
{
    "withheldInformation": [
        {
            "businessTerm": "BT-161",
            "businessTermName": "Notice Value",
            "delayRationale": "Information delayed publication because of ...",
            "delayRationaleClassification": "oth-int",
            "accessibleDate": "2024-12-31T09:00:00+01:00"
        }
    ]
}
```
As there are potentially 43 separate BTs that can be withheld this could get large, but the details can be different for each withheld BT so I don't see a way of sensibly combining this information using an array field to reference multiple BTs without it getting messy

**Comment by jpmckinney** [comment]
Hmm, so these fields work well in eForms' notice based system, because the details about withheld information are constrained to the individual notice. eForms (and TED) have no concept of a compiled release / complete record.

In OCDS, we'd end up with a list of withheld information, that at some point is no longer withheld. I guess this is fine as it discloses what information had been withheld, which might be of some analytical interest.

In eForms, BG-8 is named "Not Immediately Published" ("Information about fields not intended for immediate publication.") The semantics are somewhat different than "withheld information", since information can be withheld indefinitely. However, since we'll be including a date at which information will be released, I think it's fine to go with the broader semantics.

`withheldInformation` sounds like a good term for the array, following "Put the qualifier before the concept" from the [style guide](https://ocds-standard-development-handbook.readthedocs.io/en/latest/meta/schema_style_guide.html#field-and-code-names).

For the array entries, we can be more generic so that this can be reusable in other jurisdictions.

First, since different notices might have different `efac:FieldsPrivacy`, we need an `id` field, so that the information is merged correctly. If we expect only one `efac:FieldsPrivacy` entry per `efbc:FieldIdentifierCode` value across all notices, then we can map that to `id`. Otherwise, we'll need some other instruction for assigning the `id`. If so, instead of `businessTerm`, I considered `identifier` – but that name implies an `Identifier` object; perhaps `field` then.

Instead of `businessTermName`, use `name`.

Since information (in the general case) can be withheld indefinitely, remove `delay` from the other terms.

Instead of `accessibleDate`: Dublin Core uses [available](https://www.dublincore.org/specifications/dublin-core/dcmi-terms/terms/available/). Schema.org's [Date type](https://schema.org/Date) is used for `availabilityStarts` (which pairs with `availabilityEnds`). I'm not sure that, in the case of withheld information, we need to worry about an end date. So, I suggest `availabilityDate`.

**Comment by odscjen** [comment]
I can imagine analytical instances where knowing what information had once been withheld could be useful even if it was now available (looking for patterns in what gets withheld etc) so I do think this is worth including.

Looking at one of the [example xlm notices](https://github.com/OP-TED/eForms-SDK/blob/develop/examples/notices/can_25_withheld_lots.xml) that uses the `efac:FieldsPrivacy` block it looks as though certainly in the case of `lots` a BT can be withheld for one lot but published immediately for another. In this case adding an entry to `withheldInformation` at a release/notice level would erroneously imply the withheld status of all instances of that BT. Adding a `relatedLots` field to `withheldInformation` could address this particular point. 

But there are other fields that can occur multiple times in a notice that can be withheld and are mapped to array objects in OCDS (`bids` and `awards`). Presumably the same ability to publish a BT for one but not another holds for these as well. We could use `relatedBids` and `awardID` to perform the same function as `relatedLots` in those cases. 

But I think using a `relatedXXX` array or similar doesn’t solve the merge issue for creating a compiled release? In which case a new identifier will need to be created. A simple method here would be to just append the BT with the associated identifier, e.g. “BT-161-Lot-0001”. The trade-off here is that there will need to be a `withheldInformation` object for every individual withheld BT, we couldn’t combine if there were common justifications for multiple entries. But we also then wouldn’t need a `relatedXXX` field, that could be inferred from the `field`.

So taking your suggested changes and the new identifier type field gives:
```
{
    "withheldInformation": [
        {
            "field": "BT-161-Lot-0001",
            "name": "Notice Value",
            "rationale": "Information delayed publication because of ...",
            "rationaleClassification": "oth-int",
            "availabilityDate": "2024-12-31T09:00:00+01:00"
        }
    ]
}
```

Now that `field` is no longer just the BT, maybe `id` would be more appropriate? This keeps it generic, but is potentially less obvious that it’s identifying the BT affected. This will obviously be explained in the eForms guidance so maybe it's not a problem and it's more important to keep it generic.

**Comment by odscjen** [comment]
Using the classification object is a good idea. I’ve added that into the example.

It occurs to me that BTs that map to `bid.statistics` always refer to a single `lot`. So we wouldn’t need to create an incomplete statistic in order to reference them, we can just reference what will be the `relatedLot` it will refer to once it is published.

The BT’s that use `AwardCriterionParameter` map to each of the 4 potential fields in  `.lots.awardCriteria.criteria.numbers` (so `weight`, `percentage`, `threshold` and `number`). So part of what is being withheld in these cases isn’t just the criterion value but also how the value is being calculated with respect to the award. But as with the bid statistics they refer to a specific single `lot` so again `relatedLot` can actually be used as a reference here.

So for creating the `id` the only parts that need to be appended to the BT are the `lot.id` or the `tender.id`.

```
{
    "withheldInformation": [
        {
            "field": "BT-161",
            “id”: “BT-161-Lot-0001
            "name": "Notice Value",
            "rationale": "Information delayed publication because of ...",
            "rationaleClassification": {
                    “scheme: “non-publication-justification”
                    “id”: “oth-int”,
                    “description”: “Other public interest”
                    “uri”: http://publications.europa.eu/resource/authority/non-publication-justification/oth-int
                    }
            "availabilityDate": "2024-12-31T09:00:00+01:00"
        }
    ]
}
```

**Comment by odscjen** [comment]
@jpmckinney if you're happy with the adjusted mapping in the above comment I'll make a start on drafting the guidance.

**Comment by odscjen** [comment]
Looking at the guidance the tricky bit is going to be creating the `withheldInformation.id` field. My initial thought was to create an entry in `common-operations.md` to reference, but there are 3 potential OCDS ids that will make up the second half of the string (`tender.id`, `lots.id`, `lotGroup.id`) and these do not correspond to 3 straightforward XPath relationships with the withheld BTs. 

So rather than having a common operations section with multiple if/else sections I think that in this case it would be easier to parse for the user to have the guidance on creating the `.id` field included in the guidance for mapping BT-195 (identifier). If the  `<efac:FieldsPrivacy>` is used all 4 BTs are mandatory so even if a user doesn't tackle the conversion in numerical BT order they will still get to the `.id` creation.

The suggested guidance is the same for all version of BT-196, BT-197 and BT-198:

>**BT-196 (description)**
These values are mapped to the same `withheldBusinessTerm` objects as created for BT-195, BT-197 and BT-198.

>For each `<efac:FieldsPrivacy>` add a corresponding `withheldBusinessTerm` object to the  `withheldInformation` array and map to its `.rationale`.

>**BT-197 (justification code)**
These values are mapped to the same `withheldBusinessTerm` objects as created for BT-195, BT-196 and BT-198.

>For each `<efac:FieldsPrivacy>` add a corresponding `withheldBusinessTerm` object to the  `withheldInformation` array. Add a `.rationaleClassification` object, map the value of the XPath `<cbc:ReasonCode>` to `.id` and map the `@listName` to `.scheme`. Look up the code in the [non-publication-justification authority table](https://op.europa.eu/en/web/eu-vocabularies/concept-scheme/-/resource?uri=http://publications.europa.eu/resource/authority/non-publication-justification) and map its label to `.description` and its uri to `.uri`.

>**BT-198 (accessibility date)**
These values are mapped to the same `withheldBusinessTerm` objects as created for BT-195, BT-196 and BT-197. 

>For each `<efac:FieldsPrivacy>` add a corresponding `withheldBusinessTerm` object to the  `withheldInformation` array. [Convert date to ISO format](common-operations.md#convert-a-date-to-iso-format) and map to `.availabilityDate`

But would be customised for each version of BT-195. For example for BT-195 (BT-09):

>**BT-195 (Identifier) - BT-09**
These values are mapped to the same `withheldBusinessTerm` objects as created for BT-196, BT-197 and BT-198.

>For each <efac:FieldsPrivacy> add a corresponding `withheldBusinessTerm` object to the  `withheldInformation` array. Look up Business Term that corresponds to the value in the XPath `efac:FieldsPrivacy/efbc:FieldIdentifierCode` in the [SDK Withheld Information tables](https://docs.ted.europa.eu/eforms/1.1.1/schema/withheld-publication.html). Map the Business Term (BT-XXX) to `.field` and the Name of the Business Term to `.name`. Find the value of XPath `ancestor::cbc:ContractFolderID` that corresponds to the notice `tender.id` and append this to the Business Term with a hyphen. Set this string as the `.id`.

This final sentence will change depending on the BT being withheld and will ultimately reference the XPath to `ContractFolderID`, `TenderLot/cbc:ID`, `ProcurementProjectLot/cbc:ID`, or `LotsGroupID` and it's corresponding `tender.id`, `lots.id` or `lotGroup.id`.

A full example would be useful to include but this would presumably go into the extension documentation rather than the mapping guidance.

**Comment by duncandewhurst** [comment]
According to https://github.com/open-contracting/european-union-support/issues/107, the final sentence of the guidance for BT-197 (justification code) should be omit the name of the authority table:

> Look up the code in the [~~non-publication-justification~~ authority table](https://op.europa.eu/en/web/eu-vocabularies/concept-scheme/-/resource?uri=http://publications.europa.eu/resource/authority/non-publication-justification) and map its label to `.description` and its uri to `.uri`.

**Comment by odscjen** [comment]
@jpmckinney 

> Instead of `withheldBusinessTerm` we can go with `WithheldInformationItem`, to be consistent with the array's name and to avoid importing the EU's language.

+1

> I think we need to change the "add a corresponding withheldBusinessTerm object" construction, as we aren't always adding objects, but updating existing objects created by other mappings.

Agreed. The guidance for BT-195 will create the corresponding object and the other 3 terms will add to it. In this case the first sentence agreed in https://github.com/open-contracting/european-union-support/issues/108 is superfluous, as the object is being created in BT-195 only, the others are just adding to it. Also if the guidance is going to be repeated and individualized for each version of the 4 BTs the start of the 2nd paragraph also isn't necessary. So we could simplify the whole guidance to (using BT-09 as an example):

>**BT-195 (BT-09)**
Look up Business Term that corresponds to the value `efbc:FieldIdentifierCode` in the [SDK Withheld Information tables](https://docs.ted.europa.eu/eforms/1.1.1/schema/withheld-publication.html). 
>- Find the value of `ancestor::cbc:ContractFolderID` that corresponds to the notice `tender.id` and append this to the Business Term (BT-XXX) with a hyphen to generate an identifier. 
>- Add a `withheldInformationItem` to the `withheldInformation` array
>- Map the identifier you have just generated to its `.id`
>- Map the Business Term to `.field`
>- Map the Name of the Business Term to `.name`.

>**BT-196 (BT-09)**
Get the `withheldBusinessTerm` object created for BT-195 (BT-09) and map to its `.rationale`.

>**BT-197 (BT-09)**
Get the `withheldBusinessTerm` object created for BT-195 (BT-09).
>Add a `.rationaleClassification` object to it and map the value of the `cbc:ReasonCode` to `.id` and the `cbc:ReasonCode[@listName]` to `.scheme`. Look up the code in the [authority table](https://op.europa.eu/en/web/eu-vocabularies/concept-scheme/-/resource?uri=http://publications.europa.eu/resource/authority/non-publication-justification) and map its label to `.description` and its uri to `.uri`.

>**BT-198 (BT-09)**
Get the `withheldBusinessTerm` object created for BT-195 (BT-09).
>[Convert date to ISO format](common-operations.md#convert-a-date-to-iso-format) and map to its `.availabilityDate`

If the user gets to BT-196, 197 or 198 before the relevant BT-195 this guidance will prompt them to do BT-195 first.

**Comment by jpmckinney** [comment]
Where are "Business Term" and "Name of the Business Term" coming from? (It might be clearer once the commit is made.)

**Comment by odscjen** [comment]
The Business Term is the BT-XXX and the Name of the Business Term is it's official name. So in the above case they'd be BT-09 and "Cross Border Law" respectively. I agree it's unclear but I'm not sure how to refer to them in a clearer way while still being generic?

Maybe if the whole guidance is going to be specific to the BT being withheld we just explicitly put what these should be in for each BT-195?

**Comment by jpmckinney** [comment]
Once I see the eForms and OCDS examples, it might turn out that the example clarifies the instruction.

**Comment by jpmckinney** [comment]
But yes, if each BT-195 is specific to a BT, we might as well make the instructions explicit.

**Comment by odscjen** [comment]
The eforms examples for the entire BG is:

```
<efac:FieldsPrivacy>
    <efbc:FieldIdentifierCode listName="non-publication-identifier">cro-bor-law</efbc:FieldIdentifierCode>
    <cbc:ReasonCode listName="non-publication-justification">oth-int</cbc:ReasonCode>
    <efbc:ReasonDescription languageID="ENG">Information delayed publication because of ...</efbc:ReasonDescription>
    <efbc:ReasonDescription languageID="FRA">Publication de l'information ajournée parce que ...</efbc:ReasonDescription>
    <efbc:PublicationDate>2025-03-31+01:00</efbc:PublicationDate>
</efac:FieldsPrivacy>
```

Individual eforms examples (all using BT-09 as the withheld term)
BT-195: `<efac:FieldsPrivacy><efbc:FieldIdentifierCode listName="non-publication-identifier">cro-bor-law</efbc:FieldIdentifierCode></efac:FieldsPrivacy>`
BT-196: `<efac:FieldsPrivacy><efbc:ReasonDescription languageID="ENG">Information delayed publication because of ...</efbc:ReasonDescription></efac:FieldsPrivacy>`
BT-197: `<efac:FieldsPrivacy><cbc:ReasonCode listName="non-publication-justification">oth-int</cbc:ReasonCode></efac:FieldsPrivacy>`
BT-198: `<efac:FieldsPrivacy><efbc:PublicationDate>2025-03-31+01:00</efbc:PublicationDate></efac:FieldsPrivacy>`

The whole OCDS object would look like:

```json
{
    "withheldInformation": [
        {
            "field": "BT-09",
            "id": "BT-09-18d27a53-0109-4f93-9231-6659d931bce0",
            "name": "Cross Border Law",
            "rationale": "Information delayed publication because of ...",
            "rationaleClassification": {
                "scheme": "non-publication-justification",
                "id": "oth-int",
                "description": "Other public interest",
                "uri": "http://publications.europa.eu/resource/authority/non-publication-justification/oth-int"
            },
            "availabilityDate": "2024-12-31T09:00:00+01:00"
        }
    ]
}
```

**Comment by odscjen** [comment]
@jpmckinney see above for eforms examples and complete suggested OCDS for the BG as applied to BT-09

**Comment by jpmckinney** [comment]
You can go ahead and make the commit. Once that's done, I'll re-read it with everything in context.

**Comment by odscjen** [comment]
It's just occurred to me, should we be explicit in the guidance here that as well as creating the `wtihheldInformationItem` objects that the user should also NOT create whatever object the withheld BT would be mapped to? And that they should ensure to create those objects in a new release once the embargo date has passed? This is something that could go into the common guidance rather than being repeated in each individual piece of BT-195 guidance. The [example XML](https://github.com/OP-TED/eForms-SDK/blob/develop/examples/notices/can_25_withheld_lots.xml) features both the `FieldsPrivacy` object AND the information being withheld. Presumably because the withholding is only from the publicly published version, and it will be present in versions available to select groups.

**Comment by jpmckinney** [comment]
Yes, that instruction sounds good to me.

**Comment by odscjen** [comment]
Great, @jpmckinney how does this sound using BT-09 as an example where the reference to the common operations and removing the information is in the final bullet point of the BT specific guidance:

>**BT-195 (BT-09)**
Look up Business Term that corresponds to the value `efbc:FieldIdentifierCode` in the [SDK Withheld Information tables](https://docs.ted.europa.eu/eforms/1.1.1/schema/withheld-publication.html). 
>- Find the value of `ancestor::cbc:ContractFolderID` that corresponds to the notice `tender.id` and append this to the Business Term (BT-09) with a hyphen to generate an identifier. 
>- Add a `withheldInformationItem` to the `withheldInformation` array
>- Map the identifier you have just generated to its `.id`
>- Set `.field` to "BT-09"
>- Set `.name` to "Cross Border Law".
>- remove the value of BT-09 from all subsequent releases until it is time to [Publish previously withheld information](common-operations.md#publish-previously-withheld-information)

>**Publish previously withheld information**
>Withheld Business Terms should be published on the date given by the related BT-198. Convert the withheld business terms to OCDS as described in the guidance and [create a release](common-operations.md#create-a-release) adding `previouslyWithheldInformation` to the `.tag` array.

**Comment by jpmckinney** [comment]
Is there a reason we prefix `field` with the BT instead of the code (not-val, win-cho, etc.). Do we use business terms as values in any other mapping?

At any rate, we can remove the "look up" instruction, since we know that it is BT-09 for the field BT-195(BT-09)-Procedure.

I'm not sure about the instruction "remove the value of BT-09 from all subsequent releases". We can't remove something from a release that doesn't exist yet. I think it's sufficient to say something like, "Do not perform the mappings described in [BT-09(a)-Procedure] and [BT-09(b)-Procedure]." Similarly, we should refer to BT-198 here, but to the field BT-198(BT-09)-Procedure.

For "Publish previously withheld information", I'm not sure how the eForms publication system works – whether the eSenders send both the data and its withholding metadata at the same time, such that TED can then automatically publish the withheld information at the appropriate time, or whether the eSenders need to send the withheld data later. It sounds like the former is the case. In that case, yes, we will need something like this instruction.

I might ask @duncandewhurst to review for clarity.

**Comment by jpmckinney** [comment]
We should consider a command to auomatically generate the guidance for these BTs, as it is very time consuming to edit them all (I'm currently fixing the YAML syntax).

**Comment by odscjen** [comment]
I think prefixing the `field` with the BT was a hangover from attempting to write this as common guidance. It could be changed to the code. The look up was also a hangover from that so agree that it can be removed.

I also haven't been able to find any explicity guidance as to what happens with the withheld data once it's reached it's publication date, but from the example XML it does appear that the esenders provide both the data and the withholding info at the same time so presumably TED automatically publish it once the date is reached. 

I had intended the "Publish previously withheld information" section to sit in the common-operations.md which is why I referred to BT-198 and not BT-198 (BT-09)-Procedure. If it would be preferable to be that explicity it'll need to go in as an extra bullet point in the tailored guidance (which is probably fine as there is tailored guidance anyway).

So with that feedback the new version for @duncandewhurst to review for clarity is:

>**BT-195 (BT-09)**
>- Find the value of `ancestor::cbc:ContractFolderID` that corresponds to the notice `tender.id` and append this to the value of this field with a hyphen to generate an identifier. 
>- Add a `withheldInformationItem` to the `withheldInformation` array
>- Map the identifier you have just generated to its `.id`
>- Set `.field` to "cro-bor-law"
>- Set `.name` to "Cross Border Law".
>- Do not perform the mappings described in [BT-09(a)-Procedure] and [BT-09(b)-Procedure].
>- The withheld information should be published on the date given in BT-198(BT-09)-Procedure. 
>- - Follow the guidance in [BT-09(a)-Procedure] or [BT-09(b)-Procedure]
>- - [create a release](common-operations.md#create-a-release) with all previously withheld information that is to be published on this date. 
>- - Add `previouslyWithheldInformation` to the release's `.tag` array.

**Comment by duncandewhurst** [comment]
Regarding:

> * Find the value of `ancestor::cbc:ContractFolderID` that corresponds to the notice `tender.id` and append this to the value of this field with a hyphen to generate an identifier.

* Looking at [`can_24_maximal.xml`](https://github.com/OP-TED/eForms-SDK/blob/develop/examples/notices/can_24_maximal.xml), `cbc:ContractFolderID` doesn't have any children so I don't think it can be an ancestor of `BT-195(BT-09)-Procedure`. The `xpathAbsolute` for `BT-04-notice` is `/*/cbc:ContractFolderID` so I think that's probably the correct XPath to use to reference that field.
* `BT-04-notice` is mandatory and not repeatable so why is it necessary to perform the lookup against `tender.id`? Can't the guidance simply reference the XPath?

If you agree, then I think the first few bullets can be simplified to:

> * Add a `withheldInformationItem` to the `withheldInformation` array and set:
>   * `.id` to `[efbc:FieldIdentifierCode]-[/*/cbc:ContractFolderID]`
>   * `.field` to "cro-bor-law"
>   * `.name` to "Cross Border Law"

Regarding:

> > * Do not perform the mappings described in [BT-09(a)-Procedure] and [BT-09(b)-Procedure].
> > * The withheld information should be published on the date given in BT-198(BT-09)-Procedure.
> > * * Follow the guidance in [BT-09(a)-Procedure] or [BT-09(b)-Procedure]
> > * * [create a release](common-operations.md#create-a-release) with all previously withheld information that is to be published on this date.
> > * * Add `previouslyWithheldInformation` to the release's `.tag` array.

I think that it would make more sense to put this in the common operations guidance, something along the lines of:

> **Withheld publication of information**
> Some information required by eForms may remain non-public ("unpublished") for a defined period, as described in [withheld publication of information](https://docs.ted.europa.eu/eforms/1.3.2/schema/all-in-one.html#withheldPublicationOfInformationSection). For fields with an associated `efac:FieldsPrivacy` element, wait until the date in `/efbc:PublicationDate` and then:
> * [Create a release](common-operations.md#create-a-release) and add 'previouslyWithheldInformation' to its `.tag` array.
> * Perform the mapping for the fields and publish the release.

**Comment by odscjen** [comment]
thanks @duncandewhurst.

I agree with the initial simplification and thanks for clarifying how to refer to the correct XPATH, I wasn't sure how to refer to something that wasn't an ancestor but the sibling of an ancestor.

I also agree that the withheld info section can go into common guidance, what you suggest is good. IBut I think this common guidance will still need referenced in the withheld BT-195 field. So how about adding the following bullet points to that:
> * Do not perform the mappings described in [BT-09(a)-Procedure] and [BT-09(b)-Procedure].
> * Once the date given in BT-198(BT-09) is reached the follow the guidance in [Withheld publication of information](common-operations.md#withheld-publication-of-information) to create a new release

**Comment by duncandewhurst** [comment]
My thinking was that if we put the guidance on withheld publication of information somewhere where the reader will see it before reading the individual mappings for each field, then we don't need the 'do not perform the mappings' instruction at all and we don't need to repeat the instruction about waiting until the date for each BT.

That said, perhaps common operations is not the right place as presumably the reader will only read the items on that page if they are referenced from an individual mapping. We could instead add it to the content for the overall documentation proposed in https://github.com/open-contracting/european-union-support/issues/105

**Comment by odscjen** [comment]
ah, yes I've been assuming the reader would likely only read the common operations when directed to from an individual mapping.

The only concern I have with putting it in the overall documentation is with how we're framing that overall documentation. From the current thread it appears to be about notice types and associated fields not covered by the common guidance, but that isn't the case with the withheld information BG. So maybe the common-operations is the more appropriate place for it along with the extra sentences in the individual mappings?

**Comment by duncandewhurst** [comment]
Let's use #105 as a place to log content for the overall documentation that doesn't belong in the common operations guidance. We still need to decide how to structure the overall documentation, as part of which we can decide where to put the different bits of content in #105, including making sure that the content on withheld publication is presented to readers before they look at the individual mappings.

That said, if you still think it's better to repeat some of the guidance for each mapping, do say so :-)

**Comment by odscjen** [comment]
No that all makes sense, I think that as long as the guidance points users to read the overall guidance before they start on the individual mappings then that piece of guidance can go there. I'll copy your suggested guidance over to #105

**Comment by odscjen** [comment]
closing this now as I've updated the guidance.yaml

**Comment by odscjen** [comment]
A small amendment to the guidance has occurred to me as I'm working on the extension for these fields.

Current guidance for BT-197 is

> Get the `withheldInformationItem` object created for BT-195(BT-09)-Procedure. Add a `.rationaleClassification` object to it and map the value of the `cbc:ReasonCode` to `.id` and the `cbc:ReasonCode[@listName]` to `.scheme`. Look up the code in the [authority table](https://op.europa.eu/en/web/eu-vocabularies/concept-scheme/-/resource?uri=http://publications.europa.eu/resource/authority/non-publication-justification), map its label to `.description` and its URI to `.uri`.

But when putting together the extension `rationaleClassification` uses the `Classification` object and so needs a code from `itemClassificationScheme.csv`. So my proposal change to the guidance is:

> Get the `withheldInformationItem` object created for BT-195(BT-09)-Procedure. Add a `.rationaleClassification` object to it and map the value of the `cbc:ReasonCode` to `.id` and, set  `.scheme` to 'eu-non-publication-justification'. Look up the code in the [authority table](https://op.europa.eu/en/web/eu-vocabularies/concept-scheme/-/resource?uri=http://publications.europa.eu/resource/authority/non-publication-justification), map its label to `.description` and its URI to `.uri`.

Just wanted to double check this with either @jpmckinney or @duncandewhurst before I make the change to 44 fields :)

**Comment by jpmckinney** [comment]
Yes, makes sense to map to `eu-non-publication-justification` instead of using `non-publication-justification` from  `cbc:ReasonCode[@listName]`

**Comment by odscjen** [comment]
guidance.yaml updated so closing this issue again
