### ISSUE TITLE
Use consistent language and reference common guidance for dealing with dates

### ISSUE THREAD

**Issue by odscjen** [open-contracting/european-union-support#113]
There is a section "Convert a date to ISO format" in the [proposed common-operations](https://github.com/open-contracting/european-union-support/issues/54#issuecomment-1178339887) but this isn't being referenced in the guidance for date BT's. Suggest altering all relevant guidance to:

"[Convert date to ISO format](common-operations.md#convert-a-date-to-iso-format) and map to `field`"

For example this would change the guidance for BT-536 to:

[Get the lot for the ProcurementProjectLot](common-operations.md#get-the-lot-for-a-procurementprojectlot), [Convert date to ISO format](common-operations.md#convert-a-date-to-iso-format) and map to the lot's `.contractPeriod.startDate`.

**Comment by odscjen** [comment]
great, I've updated all the existing date guidance

**Comment by duncandewhurst** [comment]
I've done a final check for consistency across the mappings with `type: date` and corrected a few minor grammatical differences.
