### ISSUE TITLE
BT-5011, BT-722, BT-6110: EU funds

### ISSUE THREAD

**Issue by odscjen** [open-contracting/european-union-support#115]
These 3 BT's correspond to the id (BT-5011), the name (BT-722) and the general description (BT-6110) of EU funds that are at least partially funding a procurement. BT-722 and BT-6110 are currently without guidance but BT-5011 does have some. It currently says to map the "Identification of the project" to `finance.description` and to set `finance.id` incrementaly. I don't think this is correct and suggest the following update along with linked guidance for the other 2 BTs.

**BT-5011**
> Get the `Organization` object whose `.name` is 'European Union'. If none exists yet:
          - [Add a party](common-operations.md#add-a-party)
          - Set its `.name` to 'European Union'
        - Add 'funder' to its `.roles`
        Get the `Finance` object whose `.id` matches the value of XPATH `efac:Funding/efbc:FinancingIdentifier`. If none exists yet:
          - Add a `Finance` object to the contract's `.finance` array
          - Map the value of XPATH `efac:Funding/efbc:FinancingIdentifier` to its `.id`
          - Set its `.financingParty.name` to 'European Union'
          - Set its `.financingParty.id` to the party's `.id`

The only potential issue I could see with the above is a project also has funding from somewhere other than the EU and the id for that might be the same as the EU fund. But I suspect that is a very unlikely scenario.

**BT-722**
> These values are mapped to the same `finance` object as created for BT-5011 and BT-6110.

> For each `efac:Funding` , add or update the corresponding `Finance` object in the contract's `.finance` array and map to its `.title`.

**BT-6110**
> These values are mapped to the same `finance` object as created for BT-5011 and BT-722.

> For each `efac:Funding` , add or update the corresponding `Finance` object in the contract's `.finance` array and map to its `.description`.

**Comment by odscjen** [comment]
Near identical guidance would work for BT-5010 (EU Funds Financing Identifier), BT-7220 (EU Funds Programme) and BT-6140 (EU Funds Details) except in this case the `.finance` array would be in `.budget`. The XPATH in the above examples may need adjusted to specify if the code is stemming from `cac:TenderingTerms` (map to .budget) or `cac:SettledContract`.

**Comment by jpmckinney** [comment]
In TED, there was no ID, hence assigning IDs incrementally. The new guidance looks good for eForms. It looks like the "Identification of the project" guidance was accidentally copied over from the TED guidance.

> Add 'funder' to its .roles

Like in the current guidance, this should be at the top-level of indentation, since some other instruction might have created a European Union party, without initializing it with a 'funder' role.

"BT-6011" should be "BT-6110".

**Comment by jpmckinney** [comment]
Oh, and Finance objects have a `title` not a `name` https://extensions.open-contracting.org/en/extensions/finance/master/schema/

**Comment by odscjen** [comment]
Great, I've edited the above to correct the typo and mis-naming of a field.

Adjusting the guidance for BT-5011 to account for possible missing role gives:

**BT-5011**
> Get the `Organization` object whose `.name` is 'European Union' and add 'funder' to its `.roles`.
If none exists yet:
          - [Add a party](common-operations.md#add-a-party)
          - Set its `.name` to 'European Union'
        - Add 'funder' to its `.roles`
        Get the `Finance` object whose `.id` matches the value of XPATH `efac:Funding/efbc:FinancingIdentifier`. If none exists yet:
          - Add a `Finance` object to the contract's `.finance` array
          - Map the value of XPATH `efac:Funding/efbc:FinancingIdentifier` to its `.id`
          - Set its `.financingParty.title` to 'European Union'
          - Set its `.financingParty.id` to the party's `.id`

**Comment by odscjen** [comment]
Noting that for the `Finance` object created for BT-5010, BT-6140 and BT-7220 `.relatedLots` will also need to be included.

**Comment by odscjen** [comment]
@jpmckinney  For BG-614 the sdk guidance states that "Within each BG-614, at least one of BT-7220 or BT-5010 shall be specified." So it's possible that a publisher may include the name of the funding program but not the identifier. In that case the guidance as above would be incomplete as it relies on BT-5010 being present to create the `Finance` object and it's compulsory `.id`. 

The guidance could be altered to point to BT-5010 and say follow that guidance up to the point of creating the `finance.id` and at that point create the `.id` incrementally. There is however the possibility of existing `Finance` objects with the same `.title` taken from another BT-7220. From the looks of the [examples](https://github.com/OP-TED/eForms-SDK/blob/develop/examples/notices/can_24_maximal.xml) it appears that BT-5010 is the more granular identifier, i.e. the EU Funds Programme named in BT-7220 (which must be taken from the [EU program](https://op.europa.eu/en/web/eu-vocabularies/concept-scheme/-/resource?uri=http://publications.europa.eu/resource/authority/eu-programme) codelist) has multiple EU Funds Identifiers (BT-5010) attached to it. In that case the necessary `Finance` object would already exist, but it would only be appropriate to use it if its `.id` was created incrementally and not from a BT-5010. But even then it's possible the associated BT-6140 description would be different, and would therefore still need a separate `Finance` object. 

So given the above suggest the following guidance for BT-7220:
> These values are mapped to the same `finance` object as created for BT-5010 and BT-6140. If BT-5010 is not present follow the guidance for BT-5010, setting the `.id` of the `Finance` object incrementally based on its position in the `finance` array rather than the value of BT-5010.

> For each `ancestor::efac:Funding` , add or update the corresponding `Finance` object in the budget's `.finance` array and map to its `.title`.

The sdk doesn't specify if the same issue will apply to BG-611.

**Comment by jpmckinney** [comment]
Yes, looks good. In short, use BT-5010 if available, and otherwise set according to position in finance array.

**Comment by odscjen** [comment]
guidance.yaml is updated so closing this issue
