### ISSUE TITLE
BT-635, BT-636, BT-712: complaints about buyer decisions

### ISSUE THREAD

**Issue by odscjen** [open-contracting/european-union-support#116]
These 3 all related to complaints received by the buyer about their decisions. At first glance they would seem to map well to `.statistic` with:
* BT-635 -> `.statistic.value`
* BT-712 -> `.statistic.value`
* BT-636 -> `.statistic.measure`

For BT-712 `.statistic.measure` would always be `complainants`.

There are two issues that I can see.
1. At the moment `.statistic` only exists in `bid` but these aren't statistics relating to bids, they're complaints. We could create a new release level object, `complaints` with `complaints.statistic`. This might cause issues for publishers with their own local complaints extension, e.g. Albania, Kyrgyz Republic, Paraguay, Belarus, Prozorro. It doesn't look as though any of them are using `complaints.statistic` but for Prozorro (possibly others, I wasn't able to check them all), the `complaints` object isn't at release level.
2. The value of BT-636 pulls from an authority table, [irregularity-type](https://op.europa.eu/en/web/eu-vocabularies/concept-scheme/-/resource?uri=http://publications.europa.eu/resource/authority/irregularity-type) which has 33 codes all of which would need to be mapped to OCDS compliant codes. The labels of most are sentences rather than single words so they can't be used as codes. But we could stick with the EU codes in `.measure` and add the labels to `.notes` to ensure there is still a more human readable version of the information in the OCDS publication.

@jpmckinney thoughts?

**Comment by jpmckinney** [comment]
For easier reference:

BT-635 Buyer Review Requests Count

> The number of requests the buyer received to review any of its decisions.

BT-636 Buyer Review Requests Irregularity Type

> The type of irregularity alleged in the review requests.

BT-712 Buyer Review Complainants

> The number of organisations that requested the buyer to review any of its decisions (e.g. the technical specifications, award decision).

**Comment by jpmckinney** [comment]
As for your second issue, your proposed solution sounds good.

**Comment by yolile** [comment]
FYI there is one local extension from Colombia that adds `statistics` at the top level https://apiocds.colombiacompra.gov.co/recursos/processStatistics/extension.json

**Comment by jpmckinney** [comment]
Cool! I would call it `statistics` rather than `processStatistics` like in that extension, following our style guide.

**Comment by jpmckinney** [comment]
Since we are moving `statistics` out of `bids/statistics`, we need a way to retain the scope (bid, review requests, etc.), besides the `measure`, which is the specific statistic within that scope (but as it's an open codelist, it's not easy to determine the scope based only on the measure).

We often use the term `type` in other parts of the schema for scoping, but in statistics this can be confused with the data type (numerical, categorical), kind (frequency, central tendency, variability, etc.), or the measure itself. `scope` has fewer possible confusions.

So rather than adding text that needs to be parsed to `notes`, we can add a `scope` field and set it to `bids`, etc.

**Comment by jpmckinney** [comment]
For BT-712, scope can be 'complainants' like in the review-type codelist (which has a [single code](https://github.com/OP-TED/eForms-SDK/blob/a92fd0b633114096f375464320a6c9f1dd5862f7/codelists/review-type.gc#L122-L125)).

I think complaint and review request are synonyms in the EU, and complaint is more broadly used internationally, so we can use a scope of 'complaints'.

**Comment by odscjen** [comment]
Sounds good, so we'll have

```json
{
   "statistics": [
          {
             "id": "1"
             "value": "2",
             "measure": "ab-low",
             "scope": "complaints",
             "notes": "Unjustified rejection of abnormally low tenders"
          }
     ]
}
```

From BT-712 "complainants" would already be going into `measure`, so the `scope` could still just be "complaints" (can't have a complaint without a complainant!)

**Comment by jpmckinney** [comment]
Ah, yes, that works – hopefully eForms doesn't come up with a bunch of complainant-specific measures :)

**Comment by odscjen** [comment]
Great, so based on all that the proposed guidance is:

>**BT-635**
These values are mapped to the same `Statistic` objects as created for BT-636.
For each `ancestor::AppealRequestStatistics`, [add a statistic](common-operations.md#add-a-statistic) or update the corresponding `Statistic` object and map to its `.value`.

>**BT-636**
These values are mapped to the same `Statistic` objects as created for BT-636.
For each `ancestor::AppealRequestStatistics`, [add a statistic](common-operations.md#add-a-statistic) or update the corresponding `Statistic` object and map to its `.measure`. Look-up the code's label in the [authority table](https://op.europa.eu/en/web/eu-vocabularies/concept-scheme/-/resource?uri=http://publications.europa.eu/resource/authority/irregularity-type) and map it to `.notes`

>**BT-712**
[add a statistic](common-operations.md#add-a-statistic) `Statistic` object, map to its `.value` and set its `.measure` to “complainants”.

Where I've assumed the adjusted common guidance for "Add a statistic" proposed in https://github.com/open-contracting/european-union-support/issues/54#issuecomment-1300469620

**Comment by odscjen** [comment]
updated guidance.yaml so closing this issue now

**Comment by duncandewhurst** [comment]
> I think perhaps we can just have a top-level `statistics`. The bid extension is not yet part of OCDS. We can create an issue for OCDS 1.2 to discuss moving `bids/statistics` to `statistics`, as it's not necessary to scope statistics hierarchically, since the statistic `measure` already provides scope. (We can discuss this in a new issue.)

@jpmckinney just checking what needs to be done for the current state (i.e. mapping eForms to OCDS 1.1): create a new statistics extension which adds a top-level `statistics` array whose items are the `Statistic` definition from the bid extension, with the addition of `.scope`. Is that right?
