### ISSUE TITLE
Refer to XPaths consistently

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/european-union-support#117]
From https://github.com/open-contracting/european-union-support/issues/112#issuecomment-1292358615:

> Are we consistent in how we refer to XPaths? Sometimes they are `/` delimited, other times have `<...>` angle brackets, sometimes are prefixed with the word XPath, etc. We should follow one style throughout the guidance.

I don't think we've been fully consistent in how we reference XPaths. I think the most consistent way would be:

* omit angle brackets
* fully reference the XPath in relation to the element being mapped, using `ancestor::`, `sibling::` etc. as needed
* use `/` as the delimiter between elements. 
* use `element[@attribute_name]` to reference attributes
* don't prefix with the word 'XPath' unless it isn't clear from the context that the reference is to an XPath

For example, the element being mapped in BT-197 (justification code) is `cbc:ReasonCode` so the guidance proposed in https://github.com/open-contracting/european-union-support/issues/112#issuecomment-1283803601 would need updating to replace `<efac:FieldsPrivacy>` with `ancestor::efac:FieldsPrivacy` and `@listName` with `cbc:ReasonCode[@listName]`:

>For each `ancestor::efac:FieldsPrivacy` add a corresponding `withheldBusinessTerm` object to the  `withheldInformation` array. Add a `.rationaleClassification` object, map `cbc:ReasonCode` to `.id` and map `cbc:ReasonCode[@listName]` to `.scheme`. Look up the code in the [non-publication-justification authority table](https://op.europa.eu/en/web/eu-vocabularies/concept-scheme/-/resource?uri=http://publications.europa.eu/resource/authority/non-publication-justification) and map its label to `.description` and its uri to `.uri`.

Generally, I think it's sufficient to write '...map to...' without explicitly referencing the element being mapped. In the above case, the mapping includes both the element and an attribute so it makes sense to explicitly specify `cbc:ReasonCode` and `cbc:ReasonCode[@listName]`.

**Comment by duncandewhurst** [comment]
Related discussion in https://github.com/open-contracting/european-union-support/issues/54#issuecomment-1292762998

**Comment by jpmckinney** [comment]
+1 to this proposal.

**Comment by duncandewhurst** [comment]
I've added this guidance to `2019_regulation.md` so I'll close this issue.

**Comment by duncandewhurst** [comment]
Just noting that I've updated `guidance.yaml` inline with:

> don't prefix with the word 'XPath' unless it isn't clear from the context that the reference is to an XPath
