### ISSUE TITLE
One contract related to many awards

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/european-union-support#119]
Related to https://github.com/open-contracting/european-union-support/issues/54#issuecomment-1214474190

As discussed in https://github.com/open-contracting/standard/issues/790 and the related issues and PR comments, this situation can occur in eForms.

Most fields on `SettledContract` in eForms map to `Contract` in OCDS (see table below) so we need to author guidance on setting `awardId` on the `Contract` object that will be created for those fields. There could be multiple `LotResults` (awards) per `SettledContract`, but `contracts/awardId` is not an array.

In https://github.com/open-contracting/european-union-support/issues/110#issuecomment-1259961946 we agreed to keep the 1-1 relationship between `LotResult` and `Award`, and between `SettledContract` and `Contract`. However, the approach proposed in https://github.com/open-contracting/standard/issues/790#issuecomment-835427362 and https://github.com/open-contracting/standard/issues/891#issuecomment-832277089 is to combine multiple awards in eForms (`LotResult`s) to one `Award` in OCDS, i.e. to lose the 1:1 relationship.

@jpmckinney how do you think this should be handled? The combining multiple awards option seems like it would add quite a lot of complexity to the eForms guidance for any fields that map to awards.

---

| Field            | Status     | Mapping in `guidance.yaml`         | Notes                                    | Guidance updated |
| ---------------- | ---------- | ---------------------------------- | ---------------------------------------- | -- |
| OPT-316-Contract | Unmapped   |                                    | Map to `contracts.id`                    | :heavy_check_mark: |
| BT-1451-Contract | Reviewed   | `awards.date`                      |                                          | N/A |
| BT-145-Contract  | Reviewed   | `contracts.dateSigned`             | Add common operations guidance           | :heavy_check_mark: |
| BT-721-Contract  | Unmapped   |                                    | Map to `contracts.title`                 | :heavy_check_mark: |
| BT-151-Contract  | Unreviewed | `contracts.documents.url`          | Add common operations guidance           | :heavy_check_mark: ||
| BT-768-Contract  | Reviewed   | Discard                            |                                          | N/A |
| OPT-100-Contract | Unmapped   |                                    | Check frameworks guidance      | :heavy_check_mark: (see https://github.com/open-contracting/european-union-support/issues/124) |
| OPT-300-Contract | Unmapped   |                                    | Map to signatories extension?              | :heavy_check_mark: (see https://github.com/open-contracting/european-union-support/issues/128) |
| BT-3202-Contract | Unreviewed | `awards.relatedBids`               |                             |  :heavy_check_mark:  (see https://github.com/open-contracting/european-union-support/issues/123) |
| BT-150-Contract  | Unreviewed | `awards.id`                        | Map to `contracts.identifiers`           | :heavy_check_mark: |
| OPP-020-Contract | Unmapped   |                                    | T02 (transport) only                     | See https://github.com/open-contracting/european-union-support/issues/129 |
| OPP-021-Contract | Unmapped | | T02 (transport) only | See https://github.com/open-contracting/european-union-support/issues/129 |
| OPP-022-Contract | Unmapped   |                                    | T02 (transport) only                     | See https://github.com/open-contracting/european-union-support/issues/129  |
| OPP-023-Contract | Unmapped   |                                    | T02 (transport) only                     | See https://github.com/open-contracting/european-union-support/issues/129  |
| BT-5011-Contract | Reviewed   | `contracts.finance.financingParty` | See #115, add common operations guidance | :heavy_check_mark: |
| BT-722-Contract  | Unreviewed | `contracts.finance.name`           | See #115, add common operations guidance | N/A |
| BT-6110-Contract | Unreviewed | `contracts.finance.description`    | See #115, add common operations guidance | N/A |

**Comment by jpmckinney** [comment]
I suppose the EU extension *could* have an `awardID` when it's 1:1 and an `awardIDs` when it's m:1 between LotResult and SettledContract, and the absence of `awardID` would be treated as an indicator to look in `awardIDs`. I suppose the extension will have to require one of awardID or awardIDs (I forget if that's possible in our version of JSON Schema).

That seems to be the simplest approach, but with the disadvantages described in the linked issues (mainly inconsistency with OCDS as-is).

**Comment by duncandewhurst** [comment]
Sounds good. I think that's the least bad option.

>  I suppose the extension will have to require one of awardID or awardIDs (I forget if that's possible in our version of JSON Schema).

JSON Schema Draft 4 supports [`oneOf`](https://datatracker.ietf.org/doc/html/draft-fge-json-schema-validation-00#section-5.5.5) so this should work:

```json
{
  "definitions": {
    "Contract": {
      "required": [
        "id"
      ],
      "oneOf": [
        {
          "required": [
            "awardID"
          ]
        },
        {
          "required": [
            "awardIDs"
          ]
        }
      ]
    }
  }
}

```

**Comment by duncandewhurst** [comment]
Draft common operations guidance:

> **Get the contract for a SettledContract**
> Get the `Contract` in `contracts` whose `.id` is equal to `ancestor::efac:SettledContract/cbc:ID`. If none exists yet:
> 
> * Add a `Contract` to `contracts`
> * Set its `.id` to the value of `ancestor::efac:SettledContract/cbc:ID`
> * Get all LotResults (`ancestor::efac:NoticeResult/efac:LotResult`) with an `/efac:SettledContract/cbc:ID` equal to `ancestor::efac:SettledContract/cbc:ID`
>   * If there is more than one, add each LotResult's `/cbc:ID` to the contract's `.awardIDs`
>   * If there is exactly one, add its `/cbc:ID` to the contract's `.awardID`

**Comment by jpmckinney** [comment]
Looks good!

**Comment by duncandewhurst** [comment]
Closing since the guidance has been added to [`output/content/eforms/operations.md`](https://github.com/open-contracting/european-union-support/blob/main/output/content/eforms/operations.md) and the mapping of OPP-020, OPP-021, OPP-022 and OPP-023 is tracked in #129
