### ISSUE TITLE
BT-717, BT-735: clean vehicle directive

### ISSUE THREAD

**Issue by odscjen** [open-contracting/european-union-support#122]
BT-717 is a boolean, the clean vehicle directive applies to this procurement true or false.
BT-735 uses the [CVD contract type](https://op.europa.eu/en/web/eu-vocabularies/concept-scheme/-/resource?uri=http://publications.europa.eu/resource/authority/cvd-contract-type) codelist to give further details. BT-717 can be used without BT-735 following so we can't just discard the boolean by saying that the presence of another field implies it. And BT-735 can be repeated.

Suggesting modelling BT-735 using the pattern set out in procurement method rationale classifications alongside a simple boolean for BT-717. Both would sit under `lot`.

```json
{
    "tender": {
        "lots": [
            {
                "cleanVehicleDirective": "true",
                "cleanVehicleDirectiveClassifications": [
                    {
                        "id": "oth-serv-contr",
                        "description": "Other service contract",
                        "scheme": "eforms-CVD contract type"
                    }
                ]
            }
        ]
    }
}
```

**Comment by jpmckinney** [comment]
I created https://github.com/OP-TED/eForms-SDK/discussions/197 to understand where BT-717 comes from.

In extensions like [techniques](https://extensions.open-contracting.org/en/extensions/techniques/master/) we pair a `hasX` boolean with an `X` field. That might be the way to go here, depending on whether BT-717's semantics are "there is a BT-735, even if we haven't published it" or something else.

**Comment by jpmckinney** [comment]
Found the file that describes the new BTs (hard to extract programmatically) https://ec.europa.eu/info/law/better-regulation/have-your-say/initiatives/13550-Public-proc
[090166e5f0264197.pdf](https://github.com/open-contracting/european-union-support/files/10024108/090166e5f0264197.pdf)
urement-eForms-amending-the-Implementing-Regulation-on-standard-forms-used-for-publication-of-notices_en 

BT-717

> The procurement falls within the scope of the European Parliament and Council 2009/33/EC (Clean Vehicles Directive – CVD).

BT-735

> The CVD legal basis to establish which category of procurement procedure applies.

**Comment by jpmckinney** [comment]
Ideally we can make this less specific to the EU's directive. Maybe a generic classifications array, and maybe BT-717 is sufficiently related to sustainability to be covered by the related fields? #95

**Comment by odscjen** [comment]
I think the problem with using the sustainability array is that this isn't generic, it's referencing a specific directive rather than a general goal or strategy.

Could we use the Legal Basis extension? If BT-717 is 'true' then map to
```json
{
  "tender": {
      "legalBasis": {
         "id": "32019L1161",
         "scheme": "CELEX",
         "description": "Clean Vehicles Directive"
      }
   }
```
If BT-717 is false then discard.

Or would this not fit with the semantics of `legalBasis` as it's not the legal basis that allows the procurement to go ahead in it's current form, but rather noting for BT-717 that the procurement falls in the scope of this specific legal directive?

BT-735 has 3 codes, each of which refer to a type of contract as covered by specific directive(s)/regulation(s) that the procurement is going through. Again while the general goal of the CVD is the reduction of emissions these codes aren't specific goals or strategies in themselves, they refer to the 'thing' being procured so I don't think `sustainability` is the right fit. They could go into `additionalProcurementCategories` using a mapping table such as:

code | label | OCDS code | OCDS definition
-- | -- | -- | --
oth-serv-contr | Other service contract | cleanVehicleDirectiveOtherServiceContract | Services contracts for public road transport services, special-purpose road passenger-transport services, non-scheduled passenger transport, refuse collection services, mail and parcel transport and delivery as defined in the EU Clean Vehicles Directive.
pass-tran-serv | Passenger road transport services | cleanVehicleDirectivePassengerRoadTransportServices | Public service contracts for the provision of passenger road transport services as defined by the EU Clean Vehicles Directive
veh-acq | Vehicle purchase, lease or rent | cleanVehicleDirectiveRoadTransportVehicles | Contract for the purchase, lease, rent or hire-purchase of road transport vehicles as defined in the EU Clean Vehicles Directive

I've started each code with `cleanVehicleDirective` infront of each as I think it's important to retain the clear link to the legal definition being used here, they're not generic but instead defined within the [CVD directive](https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:32019L1161&from=EN#d1e645-116-1) (Article 3).

OR they could also fit into `tender.items.classification` using `.scheme` = 'eforms-CVD Contract Type' as ultimately these codes are essentially referring to specific subsets of goods/services that are classified in schemes such as CPV?

**Comment by jpmckinney** [comment]
You're right that it's not the legal basis for the procedure as a whole. [coveredBy](https://extensions.open-contracting.org/en/extensions/coveredBy/master/) has the right semantics for BT-717.

The three codes for BT-735 match the 3 bullets on [this page](https://transport.ec.europa.eu/transport-themes/clean-transport-urban-transport/clean-and-energy-efficient-vehicles/clean-vehicles-directive_en) ("Which vehicles are concerned?"), which is Article 3 Scope of [2019/1161](https://eur-lex.europa.eu/eli/dir/2019/1161/oj).

I guess `additionalProcurementCategories` should work then for BT-735, because the semantics of Scope are like a subcategorization of the higher level goods, services and works.

**Comment by jpmckinney** [comment]
Okay, I think we model BT-735 as `cleanVehicleDirectiveContractType` (based off the BT's name) which has a string (code) value, and call it a day, since it's EU exclusive.

**Comment by odscjen** [comment]
Great, I'll use `coveredBy` for BT-717 if true, discard if false.

I think if we're trying to limit the number of extensions created just for the eForms then `tender.additionalClassifications` is a good call, we could use `.scheme` = 'eforms-CVD Contract Type` and then just use the codes themselves as `.id` with the labels as `.description`?

Or maybe it is just simpler and more immediately obvious to the end user to use `tender.cleanVehicleDirectiveContractType` @jpmckinney

**Comment by jpmckinney** [comment]
Let's go with additionalClassifications. We can set scheme to `cvd-contract-type` to match the eForms codelist.

**Comment by duncandewhurst** [comment]
Closing as guidance.yaml is up to date
