### ISSUE TITLE
BT-3202-Contract: Contract Tender ID (Reference)

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/european-union-support#123]
This field belongs to [SettledContract](https://docs.ted.europa.eu/eforms/1.3.2/schema/all-in-one.html#settledContractSection), i.e. `Contract` in OCDS. It references the [Lot Tenders](https://docs.ted.europa.eu/eforms/1.3.2/schema/all-in-one.html#lotTenderSection) (`bids` in OCDS) that, combined together, lead to the contract. It is mandatory and repeatable.

The draft guidance maps the field to `awards.relatedBids`, which seems reasonable, since there is no `.relatedBids` on `Contract`. However, since [one contract can be related to many awards](https://github.com/open-contracting/european-union-support/issues/119), further guidance is needed on how to identify which award to map to.

`LotResult` (`Award` in OCDS) has a similar field (OPT-320-LotResult: Tender Identifier Reference), which is optional so we can't rely on that.

`LotTender` has a mandatory field (BT-13714-LotTender: Tender Lot Identifier) that references the `TenderLot` (`Lot` or `LotGroup` in OCDS) for which the tender was submitted. `LotResult` has a similar field (BT-13713-LotResult: Result Lot Identifier), which is also mandatory, although it can only reference lots, not groups of lots.

One option to identify the award to map to is to:
* Look up the `LotTender` that is referenced in BT-3203-Contract
* Check which `TenderLots` it references in BT-13714-LotTender
* Look up the `LotResult` that references the same `TenderLots` in BT-13713-LotResult
* Get the award with the same `.id` as the LotResult's `cbc:ID`.

However, that is quite convoluted and there will be no link between the `LotResult` and the `TenderLot` if it is a `LotGroup`.

Alternatively, we could add `.relatedBids` to `Contract` and map to that, which would be more closely aligned with eForms' model, but would mean that there are two ways to determine which bids led to a contract:

* Check `Contract.relatedBids`
* Check `Award.relatedBids` for each award referenced in `Contract.awardID` or `Contract.awardIDs`

@jpmckinney what do you think?

**Comment by jpmckinney** [comment]
I prefer the less convoluted option, as I have a feeling the other option might lead to more issues as we complete the mapping.

**Comment by duncandewhurst** [comment]
Sounds good. Me too :-)

**Comment by duncandewhurst** [comment]
I've updated the mappings for BT-3202-Contract and OPT-320-LotResult so I'll close this issue.
