### ISSUE TITLE
OPT-100-Contract: Framework Notice Identifier

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/european-union-support#124]
This field belongs to [SettledContract](https://docs.ted.europa.eu/eforms/1.3.2/schema/all-in-one.html#settledContractSection). It is used to relate the award of a contract in the second stage of a framework agreement procedure to the notice that announced the first stage of the framework procedure. It is described as:

> ID of the notice related to the Framework Contract under which the current contract takes place

There are two possible schemes for the ID:

* **ojs-notice-id** - Publication ID of the notice that announced the Framework Agreement (eForms or TEDXML notices).
* **notice-id-ref** - A combination of the Notice Identifier (BT-701) and the Notice Version (BT-757) of the notice that announced the Framework Agreement (eForms notices only)

In either case, in order to [relate the second stage to the first stage](https://standard.open-contracting.org/latest/en/guidance/map/framework_agreements/#relate-the-second-stage-to-the-first-stage) in OCDS, the publisher would need to look up the OCID of the referenced notice.

@jpmckinney do you think it is sufficient for the guidance to read:

> * [Get the contract for the SettledContract](common-operations.md#get-the-contract-for-a-settledcontract)
> * Add a `RelatedProcess` to the relatedProcesses array and:
>   * Set its `.id` incrementally
>   * Add 'framework' to its `.relationship` array
>   * Set its `.scheme` to 'ocid'
>   * Set its `.identifier` to the `.ocid` of the referenced notice

Or do we need to expand on how to find the `.ocid` of the referenced notice and what to do if the referenced notice isn't available in OCDS format?

**Comment by jpmckinney** [comment]
We can add the instructions for the case where the referenced notice isn't in OCDS. The scheme can be 'ojs-notice-id' or 'notice-id-ref' and the identifier can be the same as in the eForms data.

**Comment by jpmckinney** [comment]
As for finding the ocid of the referenced notice, I assume that might be implementation-specific, so we can leave it as an exercise for the reader.

**Comment by duncandewhurst** [comment]
Sounds good!

**Comment by duncandewhurst** [comment]
Updated guidance:

> * [Get the contract for the SettledContract](common-operations.md#get-the-contract-for-a-settledcontract)
> * Add a `RelatedProcess` to the `relatedProcesses` array and:
>   * Set its `.id` incrementally
>   * Add 'framework' to its `.relationship` array
>   * If the referenced notice is available in OCDS:
>     * Set `.scheme` to 'ocid'
>     * Set `.identifier` to the `.ocid` of the referenced notice
>   * Otherwise:
>     * Set `.scheme` to the value of `cbc:ID[@schemeName]`
>     * Map `cbc:ID` to `.identifier`

**Comment by jpmckinney** [comment]
Looks good!

**Comment by duncandewhurst** [comment]
I realised that the first instruction ([Get the contract for the SettledContract](https://github.com/open-contracting/european-union-support/issues/common-operations.md#get-the-contract-for-a-settledcontract)) is unnecessary since the relationship in OCDS is at the contracting process level.

I checked the eForms SDK documentation and I can't see any reference to one notice containing settled contracts from different procedures (I vaguely recall that this sort of grouping might've been possible in TED) so I think its fine to simply remove the bullet point.

I've updated `guidance.yaml` so I'll close this issue, but feel free to reopen it if you think differently.
