### ISSUE TITLE
BT-1711: Tender ranked, true/false boolean

### ISSUE THREAD

**Issue by odscjen** [open-contracting/european-union-support#125]
This is a new field introduced in 1.3.0.

It's a boolean to say if the tender (bid) has been ranked. "This needs to be set to "true" to be able to specify the Rank. A true value does not however mandate the rank specification, unless required by the Regulation Annex.". The rank position if given will be covered by BT-171. But because the rank position is not mandatory this boolean cannot be discarded and implied by the presence of another field.

Suggest adding `bids.hasRank` as a new field that follows the logic of similar boolean in `techniques`. This is similar to the suggestion in https://github.com/open-contracting/european-union-support/issues/122#issuecomment-1309116739 for a different set of BT's. Given that this boolean now exists, would it be preferable to also create a `.rank` field for BT-171 rather than using the `cascade` array suggested in https://github.com/open-contracting/european-union-support/issues/80?

What do you think @jpmckinney

**Comment by jpmckinney** [comment]
You mean adding `bids/details/hasRank` and `bids/details/rank`? Yes, that makes sense.

BT-171 is:

> The position of the tender (i.e. whether the tender ended up first, second, third, etc.) in a design contest, some framework agreements with multiple winners (e.g. cascades) or an innovation partnership.

The challenge that Colin was addressing in #80 is how to reflect these in the award.

I assume that in a design contest, being ranked first means you win, and being ranked not first means you don't win. So, `awards` can just refer to the rank 1 winner.

In a framework agreement with multiple winners (e.g. cascades), `awards` would refer to all winners. This is typical, as it means all `awards.suppliers` are part of the FA. I suppose a user would need to know to look up the ranks to see how they are positioned in the cascade. I don't know if there is a BT that maps to a boolean on `awards`, like an `awards.hasCascade`, to give the user a clue that they need to look up bid ranks.

For an innovation partnership, I have no idea, and there isn't much public information.

Having thought through all that, I think we can avoid the `cascade` array, as you suggest.

**Comment by odscjen** [comment]
Sorry for the typo, yes I meant `bids/details/hasRank` and `bids/details/rank`.  I'll use the former for BT-1711 and change the guidance for BT-171 to map to the latter.

I can't see a BT that would map to a boolean like `awards.hasCascade`

**Comment by jpmckinney** [comment]
Hmm, okay, for now we'll leave it as something the user needs to infer (if lot/process uses an FA, award has multiple suppliers, and bids have ranks, then suppliers are in a cascade).

**Comment by duncandewhurst** [comment]
@jpmckinney should we document that inference logic somewhere?

**Comment by jpmckinney** [comment]
Yes, it would be good to document, maybe in one of the Markdown files. I'm not sure if we have any other content relating to the interpretation of the OCDS data. If not, it can go into one of the existing files for now.

**Comment by duncandewhurst** [comment]
I don't think we have any content like that yet. I've added a data use heading to `how.md` and put it there for now (ac78b0606752e73efdc89557234d1244c7bd2a5a).
