### ISSUE TITLE
Essential assets (OPP-020, OPP-021, OPP-022, OPP-023)

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/european-union-support#129]
The following business terms belong to [SettledContract](https://docs.ted.europa.eu/eforms/1.3.2/schema/all-in-one.html#settledContractSection):

eForms BT | Description | Cardin. | XSD element
-- | -- | -- | --
Assets related contract extension indicator (OPP-020) | Extended contract duration due to essential assets necessary for the provision of the service (T02 only) | 1 | efac:DurationJustification​/efbc:ExtendedDurationIndicator
Used asset (OPP-021) | List of assets used for the provision of the public transportation services: (T02 only) | * | efac:DurationJustification​/efac:AssetsList​/efac:Asset​/efbc:AssetDescription
Significance (%) (OPP-022) | Significance of the essential assets provided in relation to the overall assets needed for the provision of the public services (estimated % share of assets provided in overall assets used to provide services under contract): (T02 only) | * | efac:DurationJustification​/efac:AssetsList​/efac:Asset​/efbc:AssetSignificance
Predominance (%) (OPP-023) | Predominant use of assets (estimated % share of assets provided compared to assets used for activities other than the public services): (T02 only) | * | efac:DurationJustification​/efac:AssetsList​/efac:Asset​/efbc:AssetPredominance

These business terms look to be lifted straight from section II.4 of [form T02](https://standard.open-contracting.org/profiles/eu/latest/en/forms/T02/) in TED so it should be possible to map them to the [essential assets extension](https://extensions.open-contracting.org/en/extensions/essentialAssets/master/). However, there are two differences:

* The essential assets extension adds fields to `tender`, but, in eForms, these fields belong to `SettledContract` (`Contract` in OCDS). One result notice can contain many settled contracts so, presumably, it is possible for a single procedure to have both a settled contract with essential assets and a settled contract without.
* `tender.essentialAssets` is an object, but, in eForms, there can be more than one asset, each with its own description, significance and predominance

Therefore, I think the eForms fields should map to `Contract` and `Contract.essentialAssets` should be an array of `essentialAssets` objects.

@jpmckinney does that sound good?

**Comment by jpmckinney** [comment]
I've started a discussion as it seems surprising that an element would move from section II (object of procurement) to (effectively) section V (award). https://github.com/OP-TED/eForms-SDK/discussions/250

**Comment by duncandewhurst** [comment]
Agreed. Thanks for starting the discussion!

**Comment by duncandewhurst** [comment]
Noting that, if mapped to `Contract`, the guidance for these business terms will need to reference 'Get the contract for a SettledContract' in [`output/content/eforms/operations.md`](https://github.com/open-contracting/european-union-support/blob/main/output/content/eforms/operations.md).

**Comment by jpmckinney** [comment]
Let's map as if it were section II like in the old forms (i.e. map it on the lot or tender).

**Comment by duncandewhurst** [comment]
@jpmckinney please can you check that you're happy with the following?

OPP-020-Contract to OPP-023-Contract are the only children of `SettledContract` that map to lots so I've authored a new common operation:

> ## Get the lots for a SettledContract
> 
> For each `ancestor::efac:NoticeResult/efac:LotResult` with a `/SettledContract` equal to the value of `ancestor::efac:SettledContract/cbc:ID`, get the `Lot` in `tender/lots` whose `.id` is equal to the value of the `LotResult`'s `/efac:TenderLot/cbc:ID`.

I've drafted the following mappings:

> ## OPP-020-Contract
> 
> [Get the lots for the SettledContract](common-operations.md#get-the-lots-for-settledcontract) and map to each lot's `.hasEssentialAssets`.
> 
> ## OPP-021-Contract
> 
> This field maps to the same `EssentialAssets` objects created for OPP-022-Contract and OPP-023-Contract.
> 
> [Get the lots for the SettledContract](common-operations.md#get-the-lots-for-settledcontract). For each lot, add or update the corresponding `EssentialAssets` object in the lot's `.essentialAssets` array and map to its `.description`.
> 
> ## OPP-022-Contract
> 
> This field maps to the same `EssentialAssets` objects created for OPP-021-Contract and OPP-023-Contract.
> 
> [Get the lots for the SettledContract](common-operations.md#get-the-lots-for-settledcontract). For each lot, add or update the corresponding `EssentialAssets` object in the lot's `.essentialAssets` array and map to its `.significance`.
> 
> ## OPP-023-Contract
> 
> This field maps to the same `EssentialAssets` objects created for OPP-021-Contract and OPP-022-Contract.
> 
> [Get the lots for the SettledContract](common-operations.md#get-the-lots-for-settledcontract). For each lot, add or update the corresponding `EssentialAssets` object in the lot's `.essentialAssets` array and map to its `.predominance`.

The above mappings would require the addition of `Lot.essentialAssets` to the essential assets extension. That field would be an array of `EssentialAssets` objects, rather than a singular object as in `tender.essentialAssets`. I think that's OK since OPP-020 through OPP-023 only appear on a `NoticeResult` for which there are always lots so there's no need to map to tender.

**Comment by jpmckinney** [comment]
Looks good! And yes, I anticipated having to extend that extension for lots (will be the case for many tender-only extensions).

**Comment by jpmckinney** [comment]
I've now asked the TED Helpdesk about this, as instructed by the eForms-SDK discussion.

**Comment by duncandewhurst** [comment]
I've updated `guidance.yaml` and `operations.md` per https://github.com/open-contracting/european-union-support/issues/129#issuecomment-1423471358.

@jpmckinney I'll close this issue for now and you can reopen it if the TED Helpdesk reply.

**Comment by jpmckinney** [comment]
I shared the TED Helpdesk's response in https://github.com/open-contracting/european-union-support/issues/131#issuecomment-1599445547
