### ISSUE TITLE
OPP-010, OPP-011, OPP-012: OJEU notice publication info

### ISSUE THREAD

**Issue by odscjen** [open-contracting/european-union-support#130]
These 3 terms give the OJEU notice identifier (OPP-010), the identifier of the issue of the OJEU (OPP-011) and the publication date of that issue (OPP-012).

I can't see any equivalent terms for the TED to OCDS guidance, @jpmckinney should we just discard these fields as the Notice ID (BT-701) exists and can be used to find the notice in the OJEU, and there's already a date (BT-05) for the notice being submitted to TED? 

Or is there a case for retaining this info in OCDS?

**Comment by jpmckinney** [comment]
Like with OPP-070 ([Slack thread](https://opencontractingint.slack.com/archives/C03S8JL100P/p1669216510754849)), these are notice-specific data elements, and so if we were to add them we'd need to make them `omitWhenMerged`. I think the only use is for reconciliation between OCDS and TED. I figure we can discard them for now.
