### ISSUE TITLE
OPP-030, OPP-031, OPP-032, OPP-033, OPP-034: T02 contract terms

### ISSUE THREAD

**Issue by odscjen** [open-contracting/european-union-support#131]
The contract terms in forms T02 that were all mapped to individual fields in the extension `contractTerms` have been remodelled in eForms to take the form of a `efac:ContractTerm` which has a code, a description and a boolean indicator. This example from [the example t02-ESP.xml](https://github.com/OP-TED/eForms-SDK/blob/develop/examples/notices/t02_ESP.xml) shows how this object appears.

```
<efac:ContractTerm>
	<efbc:TermCode listName="contract-detail">exc-right</efbc:TermCode>
	<efbc:TermDescription languageID="SPA">Description of the costs parameters blablabla ...</efbc:TermDescription>
	<efbc:TermIndicator>true</efbc:TermIndicator>
</efac:ContractTerm>
```
I'm currently waiting on [confirmation](https://github.com/OP-TED/eForms-SDK/discussions/230) if the [SDK guidance](https://docs.ted.europa.eu/eforms/1.3.2/schema/all-in-one.html#lotTenderSection) has a typo in it as it references listName = "contract-term" which I don't think exists. But assuming that what they did mean was "contract-detail" then these terms will map fairly easily to `.contractTerms` as the codes all map to a field of that object and either the description or the indicator can be used for the field value as appropriate.

Code | contractTerm field
-- | --
all-rev-tic | operatorRevenueShare
cost-comp | financialTerms
exc-right | hasExclusiveRights
other | otherTerms
publ-ser-obl | performanceTerms
soc-stand | socialStandards

However `efac:ContractTerm` is a child of `efac:LotTender`, which is the eForms equivalent of a bid. @jpmckinney are you happy with adding `contractTerms` to `bids.details`?

EDIT: It's been confirmed that the correct listName is "contract-detail"

**Comment by odscjen** [comment]
And OPP-070: Kilometers Public Transport, which would map to the EU extension field `.publicPassengerTransportServicesKilometers` but again as it appears as a child of `efac:LotTender` it would need to go under `bids.details`

**Comment by jpmckinney** [comment]
I'm confused that these would appear on the bid. I created this discussion: https://github.com/OP-TED/eForms-SDK/discussions/248

**Comment by odscjen** [comment]
thanks for starting the discussion, it is odd that they're on the bid...

**Comment by jpmckinney** [comment]
Although PO hasn't responded, I think we should map as lot (or tender) contract terms, like in the [old forms](https://standard.open-contracting.org/profiles/eu/latest/en/forms/T02/). It would be unusual for a bidder to describe their own penalties as part of their bid.

**Comment by odscjen** [comment]
That sounds like a good way forward. 

There is one issue that needs a bit of thought. Because these are in `LotTender` the XPATH doesn't include `cac:ProcurementProjectLot[cbc:ID/@schemeName='Lot']` which is I think how the guidance has been deciding to create a "-Lot" version of a BT. And so these fields are all "-Tender" in the guidance.yaml. 

The SDK says about `LotTender` 
>"LotTenders are the results of the decomposition of a received tender into fragments, each corresponding to a lot or group of lots."

Which sounds as though `LotTender` will ALWAYS specify a lot that the bid is for. So should the guidance include the option to map to either `lot` or `tender` as applicable, or just say map to the associated `lot`?
@jpmckinney

**Comment by jpmckinney** [comment]
I've now asked the TED Helpdesk about this, as instructed by the eForms-SDK discussion.

**Comment by duncandewhurst** [comment]
Generally looks good, with a few tweaks. Let me know if I misunderstood anything.

**OPP-030**

Implementers will see the guidance for OPT-032 and OPT-031 as part of mapping those fields so I think the guidance can just be 'Discard'.

**OPP-031**

Why does the guidance reference [Get the bid for the LotTender](operations.md#get-the-bid-for-a-lottender)? I don't see `bids` in OCDS referenced in the guidance.

I think it might be better to document the mapping in the guidance rather than in a mapping table because it is about what field map to, rather than what code to use or value to set.

`all-rev-tic` should be discarded because it is covered by the guidance for OPP-032.

`exc-right` (a string) maps to `.hasExclusiveRights`, which is boolean field so we either need to change the type of that field or accept some information loss.

Taking into account the above, I think the guidance can be updated as follows:

> Get the `Lot` object in `tender.lots` whose `.id` matches `ancestor::efac:LotTender/efac:TenderLot:cbc:ID`.
>
> Map to the lot's `.contractTerms` according to the value of `ancestor::ContractTerm/efbc:TermCode`:
> 
> * `all-rev-tic`: Discard
> * `cost-comp`: Map to the lot's `contractTerms.financialTerms`
> * `exc-right`: Set the lot's `contractTerms.hasExclusiveRights` to `true`
> * `other`:  Map to the lot's `otherTerms`
> * `publ-ser-obl`: Map to the lot's `performanceTerms`
> * `soc-stand`: Map to the lot's `socialStandards`

**OPP-032** / **OPP-034**

As above, not sure why the guidance references [Get the bid for the LotTender](operations.md#get-the-bid-for-a-lottender).

**OPP-033**

As above, can just be 'Discard'.

**Comment by odscjen** [comment]
thanks @duncandewhurst that all looks good. I'm also not sure why I'd included the Get the bid for the LotTender! I can only assume I was thinking that these terms appear under `LotTender` so we should be ensuring there is a `bid` in the OCDS for it and that the lot these field applies to is included in the bid's `relatedLots` array. But for these terms that maybe isn't important...

**Comment by odscjen** [comment]
I've updated according to your suggestions so I'm closing this. If including the Get the bid for the LotTender is a good idea we can reopen this

**Comment by duncandewhurst** [comment]
I realised that the first sentences of the guidance for OPP-031, OPP-032 and OPP-034 were missing instructions about what to do if no such `Lot` exists yet. In abb1fb25c41c7fcfdb593f1ebb1c677c7da0c104, I've added a "Get the Lot for a LotTender" section to `common-operations.md` and referenced that instead of repeating the instructions for each field.

I think it's fine to omit 'Get the bid for the LotTender' as we're assuming that these fields will be the same across all LotTenders. However, we should probably add a note similar to the ones we added elsewhere, along the lines of:

> This mapping assumes that the value of this field is consistent across all the LotTenders for a given lot. If the values in your data source vary, contact the [OCDS data support team](mailto:data@open-contracting.org).

**Comment by odscjen** [comment]
Good catch, as you've already updated those terms I'll close this issue again :)

**Comment by duncandewhurst** [comment]
@jpmckinney are you happy with the wording proposed in https://github.com/open-contracting/european-union-support/issues/131#issuecomment-1445553965? I thought we had added something similar elsewhere, but I can't find it now.

**Comment by jpmckinney** [comment]
Yes, looks good - just capitalize Data Support Team.

**Comment by jpmckinney** [comment]
I think the other wording was maybe in this comment: https://github.com/open-contracting/european-union-support/issues/145#issuecomment-1341623984

**Comment by duncandewhurst** [comment]
Great, that was it, I was looking for 'data support team' or 'helpdesk'. I've updated the guidance in 823390e8a65e10591318bd3832c16f4a228ab317 so I think this issue really can be closed now :-)

**Comment by jpmckinney** [comment]
Sharing the Publication Office's response here.

My original email:

> I have a couple questions that are important to interpreting the meaning of eForms XML for data analysis.
>  
> Why are OPP-030 through 034 and OPP-080 children of LotTender?
>  
> LotTender represents a tender (bid). These OPP fields are:
> 
> - 030 Contract conditions Code – uses the contract-detail authority table
> - 031 Contract Conditions Description (other than revenue allocation)
> - 032 Revenues Allocation – seems to correspond to "III.1.3) Allocation of revenues of sales from tickets" on the old T02 form
> - 033 Penalties and Rewards Code – uses the rewards-penalties codelist, which seems to be a single-code codelist
> - 034 Penalties and Rewards Description – along with 033, seems to correspond to "III.2.2) Information on rewards and penalties" on the old T02 form
>  
> I'm confused as to why these are attached to the bid, and not the lot. Does the bidder decide their own contract conditions, penalties, and rewards? I thought it was the buyer or procuring entity who did so, in which case it seems inappropriate for these fields to hang off individual bids. On the old T02 form, these appeared in section III, which had nothing to do with individual bids... Can you clarify?
> 
> Similarly for OPP-080 Kilometers Public Transport. This corresponds to "Kilometres of public passenger transport services" under "V.2.4) Information on value of the contract" on the old T02 form. This field describes the contract (or the award), but not the bid.
> 
> Why are Essential assets children of SettledContract?
>  
> In the old T02 form, II.4) Essential assets is in section II, which describes the object of procurement. These fields were singular (at most one per notice).
> 
> In eForms, the corresponding fields (OPP-020 to 023) are children of SettledContract. That makes the fields plural. There also seems to be a semantic shift, since SettledContract corresponds to section V, which describes the award of contract.
> 
> I just want to confirm whether (1) these fields can in reality hold different values for different contracts? (I know the schema permits it, but does this actually correspond to real procedures?) and (2) that these fields are, semantically, about the contract, not about the object of procurement? (I know the schema makes them about the contract, but is that correct?)

The eventual response:

> We have gone through your different questions and discussed them with our experts. Given the schema constraints, the ability to later adopt approaches (like the ones used for eForms), the absence of competition notice, the ignorance whether the information results from negotiations or not and its necessary presence in the Result publication (T02), we have decided to keep the model in its current state.  

So, the response is as clear as mud, but I think what they're saying is that our interpretation is correct, but they aren't changing eForms.
