### ISSUE TITLE
OPT-030: Procedure Service Provider or eSender

### ISSUE THREAD

**Issue by odscjen** [open-contracting/european-union-support#132]
The code OPT-030 doesn't appear in the SDK guidance but the actual XPATH [does](https://docs.ted.europa.eu/eforms/1.3.2/schema/all-in-one.html#_buyer_and_service_providers). This terms allows the publisher to nest 2 stakeholders under the `ContractingParty`, i.e. the buyer. The 2 stakeholders can be the Procurement Service Provider or the eSender. They get their own `ID` which is different from their `ancestor::cac:ContractingParty/cac:Party/cac:PartyIdentification​/cbc:ID`.
```
<cac:ContractingParty>
    <cac:Party>
        <cac:PartyIdentification>
            <cbc:ID schemeName="organization">ORG-0001</cbc:ID>
        </cac:PartyIdentification>
        <cac:ServiceProviderParty>
            <cbc:ServiceTypeCode listName="organisation-role">serv-prov</cbc:ServiceTypeCode>
            <cac:Party>
                <cac:PartyIdentification>
                    <!-- Reference (Technical ID) to the legal organization acting as a PSP. -->
                    <cbc:ID schemeName="organization">ORG-0005</cbc:ID>
                </cac:PartyIdentification>
            </cac:Party>
        </cac:ServiceProviderParty>
    </cac:Party>
</cac:ContractingParty>
```
@jpmckinney Given that the comment in the above code (taken from the SDK page) specifically mentions that the `cac:ServiceProviderParty/cac:Party/cac:PartyIdentification/cbc:ID` is "the legal organization acting as the PSP" should they be modelled as a separate organization in the `parties` array with the relevant role?

**Comment by duncandewhurst** [comment]
That sounds like the correct approach to me. The SDK documentation doesn't specify whether the procurement service provider or eSender can be the same organisation as the buyer, but that can be handled by referring to the 'get the organization for a company' guidance in https://github.com/open-contracting/european-union-support/issues/54#issuecomment-1236502928.

**Comment by odscjen** [comment]
Great thanks, although it will actually need slightly different guidance to 'get the organization for a company' as that references `ancestor::efac:Company​/cac:PartyIdentification​/cbc:ID` and that path doesn't exist for this field.

> Get the `Organization` in `parties` whose `id` is equal to the value of `ancestor::cac:ServiceProviderParty/cac:Party​/cac:PartyIdentification​/cbc:ID`. If none exists yet:
> 1. Add an `Organization` to `parties`
> 2. Set its `.id` to the value of the `ancestor::cac:ServiceProviderParty/cac:Party​/cac:PartyIdentification​/cbc:ID`.
> If the value of the field is "serv-prov" add `serviceProvider` to the `.roles` array. If the value of the field is "ted-esen" add `esender` to the `.roles` array.

I think this is the only field where this particular XPATH is used for the identifier so I don't think it's worth putting it into common operations. Unless it would be preferable to keep all references to organizations there for consistency?

**Comment by jpmckinney** [comment]
All sounds good to me :)
