### ISSUE TITLE
OPT-070: reserved execution justification/description

### ISSUE THREAD

**Issue by odscjen** [open-contracting/european-union-support#133]
Another code that doesn't appear in the SDK guidance but from the XPATH it appears to be an optional `Description` field that appears as part of the block with BT-736, e.g.

```
<cac:ContractExecutionRequirement>
    <cbc:ExecutionRequirementCode listName="reserved-execution">not-known</cbc:ExecutionRequirementCode>
    <cbc:Description languageID="ENG">...</cbc:Description>
</cac:ContractExecutionRequirement>
```
BT-736 is mapping to `tender.contractTerms.reservedExecution`. 

Neither the guidance nor the example XML notices that I checked include this `Description` field so it's hard to know what it's likely use will be. We could just discard it under the assumption that it's unlikely to be used much and any relevant information it would contain is likely to be covered by other terms already. Or it could be mapped to `tender.awardCriteriaDetails` which is currently unused in the guidance. 

@jpmckinney which option seems best, or is there a third that would be preferable?

**Comment by jpmckinney** [comment]
Hmm, maybe submit a discussion to OP-TED/eForms-SDK? Otherwise I think we can have some stock wording like "This data element is underspecified in eForms. No mapping is available."

**Comment by odscjen** [comment]
https://github.com/OP-TED/eForms-SDK/discussions/254 question asked, but if no answer is forthcoming that stock wording looks good, there's another few terms we might need it in too!

**Comment by odscjen** [comment]
latest response from the OP-TED/eForms-SDK discussion is to redirect question to the Helpdesk ted@publications.europa.eu, I've emailed them now

**Comment by jpmckinney** [comment]
Sounds good. For now we can discard with their reason.

> Discard. OPT-070 may only be used under some circumstances for a Call for Expression of Interest, which is not covered by the eForms regulation.

**Comment by odscjen** [comment]
The helpdesk responded:

"We can inform you that the CEI form is not part of the eForms regulation, and is not used in the standard eForms notices, so the OP is not focusing on it now. Once development has been completed for the standard eForms, we will work on other forms, including the MOVE (transport regulation) and CEI forms. At that time, we will document the use of OPT-070, and set occurrence and validation rules for it."

So I'll update the guidance with your sentence and close this issue
