### ISSUE TITLE
BT-08 Organization Role: Winner

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/european-union-support#136]
Per [4.6.3. General structure of an organization related information](https://docs.ted.europa.eu/eforms/1.4.0/schema/all-in-one.html#_general_structure_of_an_organization_related_information), there's no field for an organization's role. Instead:

> Roles and subroles are conveyed by their dedicated element in a specific context from where a reference to the Company or TouchPoint exist, linking role/subrole to the appropriate contact information of the organization

How to identify the winner is described in [4.6.4.1. Roles](https://docs.ted.europa.eu/eforms/1.4.0/schema/all-in-one.html#_roles):

> For a given lot result, we look for the contracts listed; from these contracts we identify the tenders associated and from there we get the tendering party(-ies).

Therefore, I think that we need to add some instructions to the mapping for BT-3202 Contract Tender ID (Reference), which is the reference from a `SettledContract` (`Contract`) to the `LotTender` (`Bid`) that led to it, to look up the `TenderingParty` (bidder), add 'supplier' to the equivalent organization in OCDS and populate `Award.suppliers`:

> * [Get the contract for the SettledContract](common-operations.md#get-the-contract-for-a-settledcontract) and add the value of this field to its `.relatedBids` array.
> * Get the `ancestor::efac:NoticeResult/efac:LotTender` whose `/cbc:ID` is equal to the value of this field.
> * [Get the organization for the company](common-operations.md#get-the-organization-for-a-company) referenced in the `LotTender`'s `/efac:TenderingParty​/cbc:ID` and:
>   * Add 'supplier' to the organization's `.roles` array.
>   * For each `ancestor::efac:NoticeResult/efac:LotResult` with an `/efac:SettledContract/cbc:ID` equal to the value of `ancestor::efac:SettledContract/cbc:ID`:
>     * [Get the award for the LotResult](common-operations.md#get-the-award-for-a-lotresult])
>     * Add an `OrganizationReference` to the award's `.suppliers` array and:
>       * Set the organization reference's `.id` to the organization's `.id`
>       * Set the organization reference's `.name` to the organization's `.name`

I think that we will need to work out similar mappings for each role listed in [Table 25. Roles marked using XML elements](https://docs.ted.europa.eu/eforms/1.4.0/schema/all-in-one.html#rolesMarkedUsingXmlElementsTable).

@odscjen @jpmckinney since the above mapping is quite convoluted, please could you check it for clarity? Thanks!

**Comment by odscjen** [comment]
The first 2 steps make sense. I think there's a missing step after that however. The `LotTender`'s `/efac:TenderingParty/cbc:ID` is the term OPT-210 (which we haven't written guidance for yet)  which in the examples takes the form "TPA-0001". The ID we need takes the example form "ORG-0001" and there can be multiple `Tenderer`'s under `TenderingParty`. To get to this we need to replace the above 3rd bullet point with:

> * Get the `ancestor::efac:NoticeResult/efac:TenderingParty` whose `/cbc:ID` matches the `LotTender`'s `/efac:TenderingParty/cbc:ID` 
> * [Get the organization for the company](common-operations.md#get-the-organization-for-a-company) referenced in the `TenderingParty`'s `efac:Tenderer/cbc:ID` and for each:

then the user should have the value(s) that matches to the ID in `efac:Organization/efac:Company/cac:PartyIdentification` and can follow the rest of the sub-bullet points which all seem clear.

**Comment by duncandewhurst** [comment]
Good spot! Your proposed update makes sense :-)

**Comment by jpmckinney** [comment]
I haven't attempted to apply the mapping to data, but it looks clear. It certainly highlights that using eForms data to answer a simple question like "who won?" is a bit difficult...

**Comment by odscjen** [comment]
Further potential changes, I've written some common guidance for [Get the organization for a tenderer](https://github.com/open-contracting/european-union-support/issues/54#issuecomment-1332267966) which could be used here to replace my second bullet point with:
>* [Get the organization for a tenderer](common-operations.md#get-the-organization-for-a-tenderer) and for each:

**Comment by duncandewhurst** [comment]
Looks good!

> It certainly highlights that using eForms data to answer a simple question like "who won?" is a bit difficult...

Indeed.

**Comment by duncandewhurst** [comment]
I've updated `guidance.yaml`.

**Comment by odscjen** [comment]
BT-08 seems to have disappeared from guidance.yaml?!

**Comment by jpmckinney** [comment]
I don't think there was ever a BT-08 in the guidance.yaml.
