### ISSUE TITLE
OPT-110, OPT-111, OPT-112, OPT-113, OPT-120, OPT-130: legislation documentation

### ISSUE THREAD

**Issue by odscjen** [open-contracting/european-union-support#138]
These 6 terms relate to legislation documentation, with OPT-111 (Fiscal), OPT-112 (Environmental) and OPT-113 (Employment) providing document ID's about which the SDK example includes the comment "ID mandated by schema, but unused in eForms". And OPT-110, OPT-120 and OPT-130 providing URI's to the legislation for each of the 3 types respectively.

Each legislation type also includes a `PartyIdentification/cbc:ID` but this is already mentioned in https://github.com/open-contracting/european-union-support/issues/136 and can probably be dealt with there.

For these 6 terms they are obvious fits for sticking into a `documents` array. The issue is which high level block to put them in? `Tender`?

Also all the other guidance so far for mapping to `.document` says to set `.id` incrementally. Is it worth retaining the ID's from these terms given the comment quoted above or continue to just use incremental ids for consistency within the OCDS data?

@jpmckinney thoughts?

**Comment by jpmckinney** [comment]
We can retain the IDs. It makes the mapping easier. We can put these in `tender/documents`, since legislation is usually referred to at that stage.

**Comment by jpmckinney** [comment]
For context, taking as example, OPT-301-Lot-EnvironLegis (Environmental Legislation Organization Technical Identifier Reference)

> Points to the Organization, or its alternate contact details, from where additional information about the environmental legislation may be obtained.

I think we would go with option 1. The field can be named `publisher` from Dublin Core, whose definition is "An entity responsible for making the resource available." (`creator` is used to distinguish making available from authoring)

**Comment by duncandewhurst** [comment]
> Get the `Document` in `tender.documents` whose `.id` matches `ancestor:cac:FiscalLegislationDocumentReference/cbc:ID`.

The mapping should describe what to do if the document hasn't been created yet. Since there are many fields related to document references, we can add a 'Get the document for a document reference' section to the common operations guidance, following the 'Get the X... If none exists yet...' pattern, and refer to it here.

> Get the `organization` in `parties` whose `id` is equal to the value of this field. If none exists yet:
> 
>     1. Add an `Organization` to `parties`
>     2. Set its `.id` to the value of this field.

Since there are many OPT-301 'Organization Technical Identifier Reference' fields, we can add a 'Get the organization for a organization technical identifier reference' section to the common operations guidance and refer to it here.

>     3. Perform the mapping for `BT-500-Organization-Company` for this `organization`.

I would put this at the beginning of the mapping so that reader doesn't need to switch back and forth between mappings. Also, the field can refer to a company or a touchpoint so the mapping should cover both cases.

With those changes:

> 1. If the reference is to a Touchpoint (TPO-XXXX), perform the mapping for `BT-500-Organization-Touchpoint` for the Touchpoint. If the reference is to a company (ORG-XXXX), perform the mapping for `BT-500-Organization-Company` for the company.
> 2. Get the document for the document reference and map to its `publisher.id`.
> 3. Get the organization for the organization technical identifier reference and add 'informationProvider' to its `.roles` array.
> 4. Set the document's `publisher.name` to the organization's `.name`.

**Comment by duncandewhurst** [comment]
Actually, if we make setting the organization reference's `.name` a post-processing step per https://github.com/open-contracting/european-union-support/issues/140#issuecomment-1345773263, then we can remove step 1.

**Comment by odscjen** [comment]
Excellent suggestion with the common guidance for technical identifiers. I'd been unsure as to how to do that given that they've all got different field names but your draft is good :)

For the document common reference the issue I can see there is that `documents` can appear under multiple different parent OCDS objects. In this particular instance I'd forgotten to add to the suggested guidance that the guidance for creating the `Document` in these cases is already covered in OPT-111. So the guidance could be:

> These values map to the same `Document` objects as created for OPT-111-Lot.
> Map to the document's `publisher.id`
> [Get the organization for the organization technical identifier reference](common-operations.md#get-the-organization-for-an-organization-technical-identifier-reference) and add 'informationProvider' to its .roles array.

**Comment by duncandewhurst** [comment]
We've generally only used the 'these values map to the same...'  construction when the objects being referenced have no identifier. How about:

> From `tender.documents`, [get the document for the document reference]() and map to its `.publisher.id`.

That way, the common operations guidance can just refer to `.documents` and the context can be specified in the individual mappings.

**Comment by odscjen** [comment]
Good point @duncandewhurst, I've suggested some common guidance in https://github.com/open-contracting/european-union-support/issues/150 as the `.document` mappings aren't totally uniform in eForms.
