### ISSUE TITLE
Organization reference names

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/european-union-support#140]
I think this issue is relevant to any mappings that involve adding an `OrganizationReference` object. In particular, it's relevant to:

* https://github.com/open-contracting/european-union-support/issues/136
* https://github.com/open-contracting/european-union-support/issues/128
* https://github.com/open-contracting/european-union-support/issues/141 (`OPT-300-Procedure-Buyer`, `OPT-310-Tender`)

When adding an `OrganizationReference` we need to provide guidance on setting the organization reference's `.name`.

Unless the mapping for `BT-500-Organization-Company` (Organisation Name) has already been performed, it's possible that the `.name` of the referenced `Organization` object isn't yet populated. I think that there are two options to address this:

1. Preface the mappings for the above business terms with an instruction to first perform the mapping for `BT-500-Organization-Company`.
2. Add instructions to each of the above mappings to set `.name` on the relevant `Organization` objects before adding the `OrganizationReference`, e.g.

> Get the `ancestor::efext:EformsExtension/efac:Organizations/efac:Organization/efac:Company` whose `/cac:PartyIdentification/cbc:ID` is equal to the organization's `.id` and set the organization's `.name` to the value of `/cac:PartyName/cbc:Name`.

I prefer option 1. because it keeps the mappings more straightforward and reduces duplication. @odscjen, @jpmckinney let me know if you think differently.

**Comment by odscjen** [comment]
I agree that option 1. is preferable

**Comment by jpmckinney** [comment]
Option 1 sounds good. Alternatively, if this is just about populating the reference's `.name`, this can be a post-processing step to just set it according to the referenced party's `.name`.

**Comment by duncandewhurst** [comment]
A post-processing step would be even simpler so that sounds good to me.

**Comment by odscjen** [comment]
To ensure I'm understanding the agreement correctly here, in the fields where a reference's .`name` needs populating we just don't mention it in the guidance for the individual BT and instead put in some post-processing guidance into the general guidance that says to go back and add `.name` to all `OrganizationReference`s?

**Comment by duncandewhurst** [comment]
Yep, exactly. I've proposed the post-processing guidance in https://github.com/open-contracting/european-union-support/issues/105

**Comment by duncandewhurst** [comment]
I've gone through the mappings that involve adding an `OrganizatonReference` and removed any references to populating `.name` or performing the mapping for `BT-500-Organization-Company`.
