### ISSUE TITLE
Roles marked using XML elements

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/european-union-support#141]
From https://github.com/open-contracting/european-union-support/issues/136#issue-1465730208:

> Per [4.6.3. General structure of an organization related information](https://docs.ted.europa.eu/eforms/1.4.0/schema/all-in-one.html#_general_structure_of_an_organization_related_information), there's no field for an organization's role. Instead:
> 
> > Roles and subroles are conveyed by their dedicated element in a specific context from where a reference to the Company or TouchPoint exist, linking role/subrole to the appropriate contact information of the organization

@odscjen, I've copied below the [table of roles marked using XML elements](https://docs.ted.europa.eu/eforms/latest/schema/all-in-one.html#rolesMarkedUsingXmlElementsTable) so that we can use it to track which field covers the mapping for each role and the status of those mappings.

Role | Description | XSD element | Field | Status
-- | -- | -- | -- | --
Buyer (#) | Organization that manages the budget allocated for the procedure and pays for the items being procured[[32](https://docs.ted.europa.eu/eforms/latest/schema/all-in-one.html#_footnotedef_32)]. | `/*/cac:ContractingParty` | `OPT-300-Procedure-Buyer` (Buyer Technical Identifier Reference) | :heavy_check_mark: |
Winner (#) | The tendering Party to whom the contract is awarded[[33](https://docs.ted.europa.eu/eforms/latest/schema/all-in-one.html#_footnotedef_33)]. NB: A winner may be a single organization or a grouping of organizations | Only provided as an example (*): `/ContractAwardNotice​/ext:UBLExtensions​/ext:UBLExtension​/ext:ExtensionContent​/efext:EformsExtension​/efac:NoticeResult​/efac:TenderingParty[cbc:ID​/text()=..​/efac:LotTender[cbc:ID​/text()=../efac:LotResult[efac:TenderLot​/cbc:ID​/text()='LOT-0001']​/efac:LotTender​/cbc:ID​/text()]​[not(cbc:TenderRank/text()='0')]​/efac:TenderingParty​/cbc:ID​/text()]` | `BT-3202-Contract` (Contract Tender ID (Reference)) | :heavy_check_mark: |
Tendering Party[[34](https://docs.ted.europa.eu/eforms/latest/schema/all-in-one.html#_footnotedef_34)] | Party, or Parties, who has / have submitted his / their tender NB: The Tendering Party may be composed of a single organization or a grouping of organizations | Only provided as an example (**): `/ContractAwardNotice​/ext:UBLExtensions​/ext:UBLExtension​/ext:ExtensionContent​/efext:EformsExtension​/efac:NoticeResult​/efac:TenderingParty[cbc:ID​/text() = ../efac:LotTender[cbc:ID​/text()=../efac:LotResult[efac:TenderLot​/cbc:ID​/text()='LOT-0001']​/efac:LotTender​/cbc:ID​/text()]​/efac:TenderingParty​/cbc:ID​/text()]` | `OPT-310-Tender` (Tendering Party ID Reference) | :heavy_check_mark: |
Tenderer | Any economic operator at the forefront of work in a Tendering Party | `/ContractAwardNotice​/ext:UBLExtensions​/ext:UBLExtension​/ext:ExtensionContent​/efext:EformsExtension​/efac:NoticeResult​/efac:TenderingParty​/efac:Tenderer` | `OPT-310-Tender` (Tendering Party ID Reference) | :heavy_check_mark: |
Review Requester | Organization requesting for review | `/ContractAwardNotice​/ext:UBLExtensions​/ext:UBLExtension​/ext:ExtensionContent​/efext:EformsExtension​/efac:AppealsInformation​/efac:AppealStatus​/efac:AppealingParty` | N/A | Not yet modelled in eForms, see https://github.com/OP-TED/eForms-SDK/discussions/258
Subcontractor | Organization that performs parts of the work of a main contractor. | `/ContractAwardNotice​/ext:UBLExtensions​/ext:UBLExtension​/ext:ExtensionContent​/efext:EformsExtension​/efac:NoticeResult​/efac:TenderingParty​/efac:SubContractor` | `OPT-301-Tenderer-SubCont` (Subcontractor ID Reference) | :heavy_check_mark: 
Mediation organization | Third party helping with Alternative Dispute Resolution | `/*/cac:ProcurementProjectLot​/cac:TenderingTerms​/cac:AppealTerms​/cac:MediationParty` | `OPT-301-Lot-Mediator` and `OPT-301-Part-Mediator` (Mediator Technical Identifier Reference) | :heavy_check_mark:
Review organization (#) | Organization dealing with review requests. | `/*/cac:ProcurementProjectLot​/cac:TenderingTerms​/cac:AppealTerms​/cac:AppealReceiverParty` | `OPT-301-Lot-ReviewOrg` and `OPT-301-Part-ReviewOrg` (Review Organization Technical Identifier Reference) | :heavy_check_mark:
Tax legislation information provider | Organization providing information concerning the general regulatory framework for taxes applicable in the place where the contract is to be performed. | `/*/cac:ProcurementProjectLot​/cac:TenderingTerms/cac:FiscalLegislationDocumentReference​/cac:Attachment​/cac:ExternalReference​/cbc:URI` And `/*/cac:ProcurementProjectLot​/cac:TenderingTerms​/cac:FiscalLegislationDocumentReference​/cac:IssuerParty` | `OPT-301-Lot-FiscalLegis` and `OPT-301-Part-FiscalLegis` (Fiscal Legislation Organization Technical Identifier Reference) | :heavy_check_mark: ([#138](https://github.com/open-contracting/european-union-support/issues/138))
Environment legislation information provider | Organization providing information concerning the general regulatory framework for environmental protection applicable in the place where the contract is to be performed. | `/*/cac:ProcurementProjectLot​/cac:TenderingTerms​/cac:EnvironmentalLegislationDocumentReference​/cac:Attachment​/cac:ExternalReference​/cbc:URI` And `/*/cac:ProcurementProjectLot​/cac:TenderingTerms​/cac:EnvironmentalLegislationDocumentReference​/cac:IssuerParty` | `OPT-301-Lot-EnvironLegis` and `OPT-301-Part-EnvironLegis` (Environmental Legislation Organization Technical Identifier Reference) | :heavy_check_mark: ([#138](https://github.com/open-contracting/european-union-support/issues/138))
Employment legislation information provider | Organization providing information concerning the general regulatory framework for employment protection and working conditions applicable in the place where the contract is to be performed. | `/*/cac:ProcurementProjectLot​/cac:TenderingTerms​/cac:EmploymentLegislationDocumentReference​/cac:Attachment​/cac:ExternalReference​/cbc:URI` And `/*/cac:ProcurementProjectLot​/cac:TenderingTerms​/cac:EmploymentLegislationDocumentReference​/cac:IssuerParty` | `OPT-301-Lot-EmployLegis` and `OPT-301-Part-EmployLegis` (Employment Legislation Organization Technical Identifier Reference) | :heavy_check_mark: ([#138](https://github.com/open-contracting/european-union-support/issues/138))
Review Requester | Organization that requested a review request. | `/ContractAwardNotice​/ext:UBLExtensions​/ext:UBLExtension​/ext:ExtensionContent​/efext:EformsExtension​/efac:AppealsInformation​/efac:AppealStatus​/efac:AppealingParty` | Duplicate, see above | N/A
Beneficial owner | Beneficial Owner of the winning organization | `/ContractAwardNotice​/ext:UBLExtensions​/ext:UBLExtension​/ext:ExtensionContent​/efext:EformsExtension​/efac:Organizations​/efac:UltimateBeneficialOwner` | `OPT-302-Organization` (Beneficial Owner Reference) | :heavy_check_mark:

**Comment by odscjen** [comment]
There are also a set of sub-roles marked with XML elements, most of these appear to be OPT-301 terms.



Sub-role | Description | XSD element | Field | Status
-- | -- | -- | -- | --
Group leader (Buyer) | To be used when:     there are multiple buyers and one acts as a group leader | For joint procurement:    `/*/ext:UBLExtensions​/ext:UBLExtension​/ext:ExtensionContent​/efext:EformsExtension​/efac:Organizations​/efac:Organization​/efac:Company[../efbc:GroupLeadIndicator​/text()="true"]` | ? | TODO
Group leader (Tenderer) | To be used when:     the winner is a consortium (or similar grouping) and the leader should then be identified individually within this consortium | For winning consortium    `/ContractAwardNotice​/ext:UBLExtensions​/ext:UBLExtension​/ext:ExtensionContent​/efext:EformsExtension​/efac:NoticeResult​/efac:TenderingParty​/efac:Tenderer[efbc:GroupLeadIndicator​/text()="true"]` | `OPT-170-Tenderer` | :heavy_check_mark: 
Additional Information Providing Organization | Organization providing additional information about the procurement procedure | `/*/cac:ProcurementProjectLot/cac:TenderingTerms​/cac:AdditionalInformationParty` | `OPT-301-Lot-AddInfo` and  `OPT-301-Part-AddInfo` | TODO
Documents provider organization | Organization providing offline access to the procurement documents | `/*/cac:ProcurementProjectLot/cac:TenderingTerms​/cac:DocumentProviderParty` | `OPT-301-Lot-DocProvider` and `OPT-301-Part-DocProvider` | TODO
Review Information Providing Organization | Organization providing more information on the time limits for review procedures | `/*/cac:ProcurementProjectLot/cac:TenderingTerms​/cac:AppealTerms​/cac:AppealInformationParty` | `OPT-301-Lot-ReviewInfo` and `OPT-301-Part-ReviewInfo` | TODO
Requests to participate Recipient Organization | Organization receiving requests to participate (*The procurement context allows identification of whether this applies to "requests to participate" or to "tender".) | `/*/cac:ProcurementProjectLot/cac:TenderingTerms​/cac:TenderRecipientParty` | `OPT-301-Lot-TenderReceipt` and `OPT-301-Part-TenderReceipt`  | TODO
Requests to participate processing Organization | Organization processing requests to participate (*The procurement context allows identification of whether this applies to "requests to participate" or to "tender".) | `/*/cac:ProcurementProjectLot/cac:TenderingTerms​/cac:TenderEvaluationParty` | `OPT-301-Lot-TenderEval` and `OPT-301-Part-TenderEval` | TODO
Tender Recipient Organization | Organization receiving tenders (*The procurement context allows identification of whether this applies to "requests to participate" or to "tender".) | `/*/cac:ProcurementProjectLot/cac:TenderingTerms​/cac:TenderRecipientParty` | `OPT-301-Lot-TenderReceipt` and `OPT-301-Part-TenderReceipt` | TODO
Tender Evaluation Organization | Organization processing tenders (*The procurement context allows identification of whether this applies to "requests to participate" or to "tender".) | `/*/cac:ProcurementProjectLot/cac:TenderingTerms​/cac:TenderEvaluationParty` | `OPT-301-Lot-TenderEval` and `OPT-301-Part-TenderEval` | TODO
Contract Signatory | Organization signing the contract | `/ContractAwardNotice​/ext:UBLExtensions​/ext:UBLExtension​/ext:ExtensionContent​/efext:EformsExtension​/efac:NoticeResult​/efac:SettledContract​/cac:SignatoryParty` | `OPT-300-Contract-Signatory` | :heavy_check_mark: 
Financing Organization | Organization whose budget is used to pay for the contract | `/ContractAwardNotice​/ext:UBLExtensions​/ext:UBLExtension​/ext:ExtensionContent​/efext:EformsExtension​/efac:NoticeResult​/efac:LotResult​/cac:FinancingParty` | `OPT-301-LotResult-Financing` | TODO
Paying Organization | Organization executing the payment | `/ContractAwardNotice​/ext:UBLExtensions​/ext:UBLExtension​/ext:ExtensionContent​/efext:EformsExtension​/efac:NoticeResult​/efac:LotResult​/cac:PayerParty` | `OPT-301-LotResult-Paying` | TODO

**Comment by duncandewhurst** [comment]
I've mapped Review Information Providing Organization (`OPT-301-Lot-ReviewInfo` and `OPT-301-Part-ReviewInfo`) to 'reviewContactPoint' from the European Union extension. For `OPT-301-Lot-ReviewInfo`, I've used the boiler plate from #145 rather than adding a field to explicitly link the review information providing organization with a specific lot.

**Comment by duncandewhurst** [comment]
With the exception of 'Review Requester', which is not yet modelled in eForms, all the roles are mapped so I'll close this issue.
