### ISSUE TITLE
Example completeness

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/european-union-support#142]
So far, we've populated `eForms example` in `guidance.yaml` with only the XML element referenced in `xpathAbsolute`. For mappings that involve other XML elements, that means that the relationship between the `eForms example` and the `OCDS example` isn't always clear.

In those cases, should we expand the `eForms example` to include all of the XML elements referenced in the mapping?

For example, for `OPT-310-Tender` (Tendering Party ID Reference) the XML element in `xpathAbsolute` doesn't actually appear in the `OCDS example` at all:

**`xpathAbsolute`**
`/*/ext:UBLExtensions/ext:UBLExtension/ext:ExtensionContent/efext:EformsExtension/efac:NoticeResult/efac:LotTender/efac:TenderingParty/cbc:ID`

**`eForms guidance`:**

> * Perform the mapping for `BT-500-Organization-Company` (Organisation Name).
> * [Get the bid for the LotTender](common-operations.md#get-the-bid-for-a-lottender) and get the `ancestor::efac:NoticeResult/efac:TenderingParty` whose `/cbc:ID` is equal to the value of this field.
> * For each `/efac:Tenderer` in the tendering party:
>   * [Get the organization for the tenderer](common-operations.md#get-the-organisation-for-a-tenderer).
>   * Add an `OrganizationReference` object to the bid's `.tenderers` array, set its `.id` to the organization's `.id` and set its `.name` to the organization's `.name`.

**`eForms example`:**
`<efac:NoticeResult><efac:LotTender><efac:TenderingParty><cbc:ID schemeName="tendering-party">TPA-0002</cbc:ID></efac:TenderingParty></efac:LotTender></efac:NoticeResult>`

**`OCDS example`:**
`{"bids": [{"tenderers": [{"id": "ORG-0011", "Competitor"}]}]}`

We could expand the eForms example as follows, although it is rather long:

```xml
<efext:EformsExtension>
  <efac:NoticeResult>
    <efac:LotTender>
      <efac:TenderingParty>
        <cbc:ID schemeName="tendering-party">TPA-0002</cbc:ID>
      </efac:TenderingParty>
    </efac:LotTender>
    <efac:TenderingParty>
      <cbc:ID schemeName="tendering-party">TPA-0002</cbc:ID>
      <efac:Tenderer>
        <cbc:ID schemeName="organization">ORG-0011</cbc:ID>
      </efac:Tenderer>
    </efac:TenderingParty>
  </efac:NoticeResult>
  <efac:Organizations>
    <efac:Organization>
      <efac:Company>
        <cac:PartyIdentification>
          <cbc:ID schemeName="organization">ORG-0011</cbc:ID>
        </cac:PartyIdentification>
        <cac:PartyName>
          <cbc:Name languageID="ENG">Competitor</cbc:Name>
        </cac:PartyName>
      </efac:Company>
    </efac:Organization>
  </efac:Organizations>
</efext:EformsExtension>
```

**Comment by jpmckinney** [comment]
Sounds good to me!

**Comment by duncandewhurst** [comment]
Jen and I will both check through for BTs that would benefit from a more complete eForms example.

**Comment by odscjen** [comment]
I started looking through examples as we're mostly done with the extensions. In the cases like BT-06

> This field maps to the same `Sustainability` objects as created for BT-777-Lot.
        [Get the lot for the ProcurementProjectLot](operations.md#get-the-lot-for-a-procurementprojectlot).
        If the code is "none" discard, otherwise set the lot's `.hasSustainability` to "true".
        For each `cac:ProcurementAdditionalType`, add or update the corresponding `Sustainability` object to the lot's `.sustainability` array.
        - Map the code to the sustainability's `.goal` according to the [strategic procurement mapping table](codelists/strategic-procurement).
        - Add 'awardCriteria', 'contractPerformanceConditions', 'selectionCriteria' and 'technicalSpecifications' to the sustainability's `.strategies` array.

i.e. cases where we're referring to a common operation of looking up an ID, should we extend the example to include that ID or is that overkill?

So for BT-06 the eforms example would become

```xml
<cac:ProcurementProjectLot>
	<cbc:ID schemeName="Lot">LOT-0001"</cbc:ID>
            <cac:ProcurementProject>
                <cac:ProcurementAdditionalType>
                    <cbc:ProcurementTypeCode listName="strategic-procurement">inn-pur</cbc:ProcurementTypeCode>
                </cac:ProcurementAdditionalType>
            </cac:ProcurementProject>
</cac:ProcurementProjectLot>
```

@duncandewhurst @jpmckinney?

**Comment by jpmckinney** [comment]
I think so. The updated example does make it easier to follow.

**Comment by duncandewhurst** [comment]
Yep, I think that's worth doing. We should also set `tender.lots.id` in the OCDS example.

**Comment by odscjen** [comment]
Great, thanks both

**Comment by jpmckinney** [comment]
BT-3202-Contract is a good candidate for a larger example.

**Comment by duncandewhurst** [comment]
Incomplete eForms examples:

- [ ] BT-13713-LotResult
- [ ] BT-13714-Tender
- [ ] BT-1375-Procedure (update OCDS example, too)
- [ ] BT-162-Tender
- [ ] BT-163-Tender
- [ ] OPT-300-Contract-Signatory
- [ ] OPT-302-Organization

Incomplete OCDS examples:

- [ ] BT-151-Contract
- [ ] BT-200-Contract, BT-201-Contract, BT-202-Contract
- [ ] BT-262-Part, BT-262-Procedure
- [ ] BT-263-Part, BT-263-Procedure
- [ ] BT-44-Lot
- [ ] BT-7220-Lot
- [ ] OPT-100-Contract
- [ ] OPT-302-Organization

Other issues that I noticed:

- [ ] BT-157-LotsGroup: broken link in guidance
- [ ] BT-200-Contract, BT-201-Contract, BT-202-Contract: incoherent guidance on identifier uniqueness
- [ ] BT-263-Lot: guidance incomplete, c.f. to BT-263-Lot
- [ ] BT-501-Organization-Company: example would be clearer with a real organization identifier
- [ ] BT-7220-Lot: typo in guidance (setting vs set)
- [ ] OPT-156-LotResult: inconsistent eForms and OCDS examples

Where the guidance for a field references a common operation, in most cases, the eForms and OCDS examples do not include the fields referenced in the guidance for the common operation. To show how identifiers and objects in eForms and OCDS relate to each other whilst avoiding repetition in the field mappings, we could see if it makes sense to add eForms and OCDS examples on the common operations page.

**Comment by odscjen** [comment]
I'm assuming that in your comment lists @duncandewhurst that you've not included those fields where the only element of guidance that's not covered in the example is the common operation element? 

Given how often a lot of these common operations are referenced I agree that it makes general sense to add examples to the common operations page itself rather than clutter up the guidance page. There may be examples however, where showing the full example in the guidance might be useful, particularly if there are multiple common operations referenced for a single field, e.g. in BT-3202?

**Comment by odscjen** [comment]
- [ ] BT-262-Lot and BT-263-Lot - guidance doesn't mention how to add `item.id`

**Comment by odscjen** [comment]
BT-7220 typo in guidance. I don't agree that this is a typo, its saying to follow a piece of guidance but do something different for part of it. Changing "setting" to "set" would to me read as though the full guidance for BT-5010 is to be followed and then the user should move onto the rest of the sentence, the first part of which would be to change something they'd just set by following the guidance for BT-5010 which could be confusing.

**Comment by jpmckinney** [comment]
I think "setting" is indeed fine, but we can use a comma after "follow" (in general "if" clauses should end in a comma to be easier to parse).

**Comment by duncandewhurst** [comment]
> I'm assuming that in your comment lists @duncandewhurst that you've not included those fields where the only element of guidance that's not covered in the example is the common operation element?

Yep, that's right. If wanted to include the fields referenced in the common operations, we'd need to update the majority of the examples, which would involve a lot of repetition.

> There may be examples however, where showing the full example in the guidance might be useful, particularly if there are multiple common operations referenced for a single field, e.g. in BT-3202?

Yep, we can do that for BT-3202 (already mentioned in this thread) and for any other field mappings that you think would benefit from it.

BT-7220: Agreed that 'setting' is fine. I must've misread it.

For the common operations examples, you're correct that the eForms fields that reference the common operations might have different parents. To be consistent with the eForms examples in the field mappings, I think that we should omit the XML hierarchy above the parts that are referenced in the common operation. That way, it doesn't matter if the parents beyond that differ between each field. I'd also omit the `<!-- Interrupted Mark-up -->` comments as we haven't used those in the eForms examples in the field mappings.

So for add a bids statistic, that would look like:

> ## Add a bids statistic
> Add a `Statistic` object to the `bids.statistics` array, set its `.relatedLot` to the value of `ancestor::efac:LotResult/efac:TenderLot/cbc:ID`, and set its `.id` (string) sequentially across all notices for this procedure. For example, if a first notice for a given procedure has nine bid statistics, it uses `id`'s '1' through '9'. A second notice for the same procedure then uses `id`'s '10' and up, etc.
>
> ```xml
> <efac:LotResult>
>   <efac:TenderLot>
>     <cbc:ID schemeName="Lot">LOT-0001</cbc:ID>
>   </efac:TenderLot>
> </efac:LotResult>
> ```
>
> ```json
> {
>   "bids": {
>     "statistics": [
>       {
>         "id": "1",
>         "relatedLot": "LOT-0001"
>       }
>     ]
>   }
> }
> ```

**Comment by duncandewhurst** [comment]
> Yep, that's right. If we wanted to include the fields referenced in the common operations, we'd need to update the majority of the examples, which would involve a lot of repetition.

I just realised this is actually what we agreed to do earlier in this issue! Not sure how I missed that. It will be easier for readers to follow if the examples in the field mappings are complete, rather than having them split across the field mappings and the common operations page so let's go with that approach, even if it's slightly more work for us.

**Comment by duncandewhurst** [comment]
>     * [ ]  BT-200-Contract, BT-201-Contract, BT-202-Contract: incoherent guidance on identifier uniqueness

The guidance for these fields includes the following sentences:

> The `.id` can be any value guaranteed to be globally unique. For example, it can be set to a [version 4 UUID](https://en.wikipedia.org/wiki/Universally_unique_identifier), or it can be assigned sequentially across all notices for this procedure (the first notice sets it to "1", the second to "2", etc.).

However, sequential identifiers are not globally unique. Should we update the first sentence to read "The `.id` can be any value guaranteed to be unique within the scope of the procedure"?

**Comment by odscjen** [comment]
BT-140-notice - Change Reason Code has guidance with a 3 exclusive conditionals, 1 of which references a common operation, the other 2 don't. Currently the eForms example doesn't include the elements in the common operation (get the award for a lotResult). I can't decide if it would be useful to include it when it's not relevant for 2 of the options?

**Comment by odscjen** [comment]
> However, sequential identifiers are not globally unique. Should we update the first sentence to read "The .id can be any value guaranteed to be unique within the scope of the procedure"?

This seems sensible to me

**Comment by odscjen** [comment]
note to self (or Duncan), checked up to BT-510(c)-UBO inclusive, other than the conditional guidance noted above

**Comment by duncandewhurst** [comment]
I think that it's sufficient for the examples to cover only one set of conditions.

**Comment by duncandewhurst** [comment]
@odscjen I've picked up where you left off and done up to to BT-739-Organization-TouchPoint inclusive.

**Comment by odscjen** [comment]
@duncandewhurst a small amount picked up, to BT-771-Lot inclusive

**Comment by duncandewhurst** [comment]
@odscjen I've done up to OPP-030-Tender inclusive

**Comment by odscjen** [comment]
@duncandewhurst that's them all done!

I had to update the guidance for OPP-080 as it didn't cover how to actually get the `contract` the field was being added to. Can you double check it makes sense as it's not as simple as just using [Get the contract for a SettledContract]?

**Comment by duncandewhurst** [comment]
Great!

I made a couple of tweaks to the OPP-080 guidance for clarity so I think that we can close this issue now :-)
