### ISSUE TITLE
OPP-050, OPP-051, OPP-052: buyer lead, awarding CPB and acquiring CPB

### ISSUE THREAD

**Issue by odscjen** [open-contracting/european-union-support#143]
none of these terms are named in the SDK but they are all covered in the [buyers section](https://docs.ted.europa.eu/eforms/latest/schema/all-in-one.html#buyerSection). All three are boolean true/false indicators:

OPP-050 Buyers Group Lead Indicator `efac:Organization/efbc:GroupLeadIndicator`
OPP-051 Awarding CPB Buyer Indicator `efac:Organization/efbc:AwardingCPBIndicator`
OPP-052 Acquiring CPB Buyer Indicator `efac:Organization/efbc:AcquiringCPBIndicator`

The EU extensions already has the party role "centralPurchasingBody" defined as "The procuring entity providing centralized purchasing activities and, possibly, ancillary purchasing activities." But this doesn't cover if the CPB is awarding or acquiring the procured goods/works/services. 

In all three cases we could create a new role for when the indicator is true, and just discard when the indicator is false. E.g. "leadBuyer", "awardingCentralPurchasingBody", and "acquiringCentralPurchasingBody".

@jpmckinney do this seem reasonable to you?

**Comment by jpmckinney** [comment]
This seems reasonable. There is some related discussion here, which might inform things (or might not – I just remember that CPBs have a lot of modalities that tend to not matter much) https://github.com/open-contracting/standard/issues/1180

**Comment by odscjen** [comment]
Great. That discussion doesn't seem to inform things here as the definitions suggest that a CPB can be involved in acquiring or awarding:
> 'central purchasing body' (CPB) means a contracting authority providing one of: 
    > (a) the **acquisition** of supplies and/or services intended for contracting authorities,
    > (b) the **award** of public contracts or the conclusion of framework agreements for works, supplies or services intended for contracting authorities

(I've condensed  and combined the definitions for clarity to this discussion). These terms are where eForms are providing further differentiation in the CPB definition.

So I'll add in the 3 new `roles`.

**Comment by odscjen** [comment]
guidance.yaml has been updated so closing this issue
