### ISSUE TITLE
OPT-301-Lot-Mediator

### ISSUE THREAD

**Issue by odscjen** [open-contracting/european-union-support#145]
For the Mediation Party (`OPT-301-Lot-Mediator` and `OPT-301-Part-Mediator` it can be given as either an organization or a touchpoint so the following guidance should work:

>If the value of the field follows the pattern “ORG-XXXX” then [get the organization for the company](common-operations.md#get-the-organization-fot-the-company) whose `cbc:ID` is equal to the value of the field.
Or 
If the value of the field follows the pattern “TPO-XXXX” then [get the organization for the touchpoint](common-operations.md#get-the-organization-fot-the-touchpointy) whose `cbc:ID` is equal to the value of the field.
Add ‘mediationBody’ to the organization’s `.roles` array.

The only potential issue is that in the case of `OPT-301-Lot-Mediator` this field appears under `cac:ProcurementProjectLot​/` and so is applicable only to that lot. Theoretically there could be different Mediation Parties for different lots within a notice but we currently have no way of capturing this in OCDS that I can see. To allow for that we could introduce a new `organizationReference` object in `lot` e.g.
```json
{
    "tender": {
        "lots": [
            {
                "mediationBody": {
                    "id": "ORG-0006",
                    "name": "The Public Mediator"
                }
            }
        ]
    }
}
```
Where I've used `mediationBody` to match the role in the [1.2 version of organizationRole codelist](https://standard.open-contracting.org/staging/1.2-dev/en/schema/codelists/#organization-role) rather than `mediationParty` as used in eForms. 

@jpmckinney @duncandewhurst Or is this overkill and highly unlikely to actually be needed as I imagine the same mediation body will almost always be used for all lots in a tender?

**Comment by odscjen** [comment]
The same guidance and issue applies to OPT-301-Lot-ReviewOrg but with 'reviewBody' as the value to the added to `.roles` and suggestion of `reviewBody` added to `lots`

**Comment by jpmckinney** [comment]
I can't find anything in the eForms regulation about mediators at all, and nothing about review bodies being different per lot. Maybe for now we can just put some boilerplate like:

"eForms allows review bodies and mediation bodies to differ per lot. However, while this may be permitted by law, we have found no evidence in practice. Please contact data@open-contracting.org if you have a use case."

**Comment by odscjen** [comment]
That sounds like a good solution. I'll add the guidance as described in the first part of my initial comment to guidance.yaml and add those boilerplate sentences at the end.

**Comment by odscjen** [comment]
closing as guidance.yaml updated
