### ISSUE TITLE
OPT-301-Lot-AddInfo/OPT-301-Part-AddInfo: Additional Information Providing Organization

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/european-union-support#147]
From https://github.com/open-contracting/european-union-support/issues/141, this role is defined as:

> Organization providing additional information about the procurement procedure

I think this maps to the 'processContactPoint' role from the European Union extension:

> A contact point dedicated to this contracting process.

In the EU profile, this role is only used in the context of procedure-level fields so there's no need to tie it to a specific lot. However, in eForms, it is used in the context of individual lots and parts.

In a [Slack thread](https://opencontractingint.slack.com/archives/C03S8JL100P/p1659911924382459), we decided to treat parts as individual contracting processes so there's no need for an explicit link between a tender and the 'processContactPoint'. However, there is a need to add such a field for Lots.

I propose that we reuse the `informationService` terminology from the European Union extension and add a `Lot.informationService` field (an `OrganizationReference`).

@jpmckinney does that sound good to you?

**Comment by odscjen** [comment]
Just to note that for OPT-301-Lot-Mediator and OPT-301-Lot-ReviewOrg the same issue came up re. linking an organization to a specific lot and [we decided to just add the line](https://github.com/open-contracting/european-union-support/issues/145) 

>eForms allows review bodies and mediation bodies to differ per lot. However, while this may be permitted by law, we have found no evidence in practice. Please contact data@open-contracting.org if you have a use case.

to the guidance for these fields and not map anything to `lots`.

**Comment by duncandewhurst** [comment]
The eForms regulation mentions neither additional information providers nor document providers and the fields do not belong to any business groups. However, I think that these fields would fit under BG-100 (Communication), the description for which does say the information may differ per lot/part:

> General information about communication with the buyer(s). This information may differ per lot. In case of a prior information notice used only for information, this information may differ per part of the notice that may later become a lot or a self-standing procedure.

**Comment by jpmckinney** [comment]
Yes, and now also in #148. I'm not aware of processes having so many parties involved for providing information/mediating/financing different lots. I can imagine possible processes, but I'm not sure that any procurement system tracks this level of detail. Out of these OPT-301-* issues, #144 has some public interest and analytical utility. For these others, I suppose a potential supplier might be interested, but that still depends on the information's availability. So my tendency would be to reuse the wording from #145.

**Comment by duncandewhurst** [comment]
Sounds good!
