### ISSUE TITLE
OPT-301-LotResult-Financing and OPT-301-LotResult-Paying

### ISSUE THREAD

**Issue by odscjen** [open-contracting/european-union-support#148]
OPT-301-LotResult-Financing (The Organization whose budget is used to pay for the contract)

OPT-301-LotResult-Payer (The Organization executing the payment)

These terms appear in `LotResult` and for a single `LotResult` there can be multiple entries for both terms. Neither fit into `contracts.implementation.payer` as they're not referring to a specific transaction. The `Finance` extension also doesn't quite fit as these don't appear to relate to specific methods of financing the contract, just who is providing the money and who is doing the administration of paying the money over.

Maybe the solution here is as simple as just adding the role 'funder' to the Organization in `parties` that matches `OPT-301-LotResult-Financing' and 'payer' to the Organization in `parties` that matches `OPT-301-LotResult-Payer'. The issue with this is that this doesn't allow the Lot specific information to be retained, e.g. that ORG-0001 is financing the contract awarded for LOT-0002 and ORG-0002 is executing the payment for that contract. To retain that information we could add arrays of `OrganizationReference` objects to `lots` or `awards` called `financingParties` and `paymentParties`?

@jpmckinney @duncandewhurst

**Comment by jpmckinney** [comment]
Let's use a similar construction as in https://github.com/open-contracting/european-union-support/issues/145#issuecomment-1341623984, seeing as these fields are new and I can't really trace where their requirement comes from (other than the law doesn't prohibit this scenario).

**Comment by odscjen** [comment]
closing as updated guidance.yaml
