### ISSUE TITLE
common guidance for documents

### ISSUE THREAD

**Issue by odscjen** [open-contracting/european-union-support#150]
It's being discussed in https://github.com/open-contracting/european-union-support/issues/138 that we should have common guidance for documents. I've looked through all the mappings we've got so far (which is almost all terms) and the terms we're mapping to `.document` fall into 2 categories. 

1. The vast majority (BT-15, BT-708, BT-737, OPT-110, OPT-111, OPT-112, OPT-113, OPT-120, OPT-130, OPT-140) all have a parent term that ends 'DocumentReference' (`cac:CallForTendersDocumentReference`, `cac:EmploymentLegislationDocumentReference`, `cac:EnvironmentalLegislationDocumentReference`, `cac:FiscalLegislationDocumentReference`) and a `cbc:ID` that follows that parent. All of these are being mapped to `tender.documents` with the `cbc:ID` being set to the document's `.id`.
2. BT-151 is being mapped to `contracts.documents` and doesn't have an associated `cbc:ID` so its `.id` is being set incrementally.

For the first case I'm proposing the following common guidance:

> **Get the document for a document reference**
> 
> Get the `Document` object in `tender.documents` whose `.id` is equal to the document reference's `/cbc:ID`. If none exists yet, add a `Document` object to `tender.documents` and set its `.id` to the document reference's `/cbc:ID`.

And we'll need to update the mappings for the above noted business terms to reference it. To keep it more generic we can (as mentioned in https://github.com/open-contracting/european-union-support/issues/138#issuecomment-1347620865 remove `tender` from the guidance and include that instead in the individual mapping guidance but as the only terms that this guidance works for map to `tender` I'm not sure that's necessary?

For BT-151 as it's the sole instance of it's type I'm suggesting we leave the individual guidance as it stands.

**Comment by duncandewhurst** [comment]
Thanks for the research! With that context, I think it's fine for the common operations guidance to reference `tender.documents`. Your suggestion for BT-151 sounds good, too.

**Comment by odscjen** [comment]
Great, I've updated the guidance.yaml for all BT's listed above so I'll close this issue now
