### ISSUE TITLE
hard cases - examples/further explanation documentation?

### ISSUE THREAD

**Issue by odscjen** [open-contracting/european-union-support#152]
We have so far the guidance.yaml for each BT (which includes an example of how the specified OCDS mapping will look), the common-operations.md for mapping actions that occur in multiple locations, and overall documentation for common guidance that doesn't fit into either of the first 2 documents. I think it would also be useful to have a document for fuller examples in cases where multiple BT's are highly interlinked and the OCDS mapping is slightly convoluted. In particular I'm thinking of https://github.com/open-contracting/european-union-support/issues/127 but I'm sure there are other instances where a more detailed explanation with full examples would be useful and where the OCDS fields being used aren't entirely from an EU extension. 

@duncandewhurst @jpmckinney what do you think?

**Comment by jpmckinney** [comment]
That sounds reasonable to me! I'll start a `output/content/eforms` directory, where we can start putting these additional pages as Markdown files.

**Comment by duncandewhurst** [comment]
Jen will work on the example for #127 

Both of us will check for any other BTs or groups of BTs that would benefit from additional documentation.

**Comment by duncandewhurst** [comment]
Not sure if it's a hard case exactly, but I think that BT-752-Lot and its related BTs would benefit from an example. As it stands, the example feels a bit meaningless:

```json
{
  "tender": {
    "lots": [
      {
        "selectionCriteria": {
          "criteria": [
            {
              "numbers": [
                {
                  "number": 2
                }
              ]
            }
          ]
        }
      }
    ]
  }
}
```

**Comment by duncandewhurst** [comment]
I think it would be helpful to have some documentation that explains how organizations, UBOs, companies and touchpoints are modelled in OCDS. The documentation could build on the diagrams from https://docs.ted.europa.eu/eforms/latest/schema/parties.html#organizationsInformationDesignSection:

![image](https://github.com/open-contracting/european-union-support/assets/19265814/852f5ed0-1447-44c1-8eeb-438352c34ea1)

![image](https://github.com/open-contracting/european-union-support/assets/19265814/3382932a-cbd6-468e-bf4a-92b0771b3d67)
 
Similarly, some introductory content to explain the relationship between key eForms concepts (Lots, LotGroups, LotResults, TenderLots, LotTenders etc.) and OCDS would be useful.

**Comment by jpmckinney** [comment]
Sounds good. We can maybe move the "how-to" content from https://github.com/open-contracting-extensions/eforms/blob/latest/docs/how.md to a separate sub-page, and add this new "explanation" content to a new page that appears before it, under `how/`.

**Comment by duncandewhurst** [comment]
I wonder if it would be better to separate the explanatory content into a primer/introduction/getting started section? e.g.

Section | Mode | Content
-- | -- | --
Primer | Explanation | Introductory content from `how.md` (up to 'Convert a notice to OCDS format'); explanation of how key eForms concepts are modelled in OCDS; 'What's not included' from `how.md`.
How to use this profile | How-to guides | 'Convert a notice to OCDS format'; 'Post-processing steps'; 'Post-publication steps'; and 'Data use' from `how.md`. Suggest splitting into two sub-pages: 'How to publish eForms notices in OCDS format' and 'How to use OCDS for eForms data'.

**Comment by jpmckinney** [comment]
That's also fine - we have limited content so it's hard to say what's the right shape.

**Comment by duncandewhurst** [comment]
Great. I've started drafting the new explanatory content in a [Google Doc](https://docs.google.com/document/d/1NLcZ9TJMTd2vFR8VpjsK2m-1X7VRVGBl_GaozSRUvT8/edit#heading=h.p6z42bccbig8) and will see which structure seems most appropriate once I have a first draft.

**Comment by duncandewhurst** [comment]
@odscjen @jpmckinney the [draft content](https://docs.google.com/document/d/1NLcZ9TJMTd2vFR8VpjsK2m-1X7VRVGBl_GaozSRUvT8/edit#heading=h.p6z42bccbig8) is ready for review. I figure it makes sense to make sure that we're all on the same page regarding the content before deciding on how to integrate it and whether to restructure the existing docs.

**Comment by jpmckinney** [comment]
I've left a bunch of comments, but it's looking good :)

**Comment by duncandewhurst** [comment]
@jpmckinney I've addressed all your comments. Let me know if any other changes are needed or if you're happy for me to prepare a PR.

Regarding structure, given that the new content is fairly substantial, I think that the structure proposed in https://github.com/open-contracting/european-union-support/issues/152#issuecomment-1683254602 makes sense.

**Comment by jpmckinney** [comment]
I did some copy-editing. Looks good for PR!

**Comment by duncandewhurst** [comment]
> Not sure if it's a hard case exactly, but I think that BT-752-Lot and its related BTs would benefit from an example. As it stands, the example feels a bit meaningless:

Having looked at this again, I don't think we need to author any extra content. The example makes sense in the context of the eForms data model, which separates numbers and their meaning into separate fields so this should make sense to an eForms implementer. From an OCDS perspective, the documentation for [`CriterionNumber`](https://extensions.open-contracting.org/en/extensions/awardCriteria/master/schema/#criterionnumber) is sufficient.

**Comment by duncandewhurst** [comment]
> Both of us will check for any other BTs or groups of BTs that would benefit from additional documentation.

I reviewed the field mappings and, taking into account the expanded examples added for each mapping in https://github.com/open-contracting/european-union-support/issues/142 and the primer documentation added in this issue, I didn't find any BTs that I felt needed additional explanation. I considered further explaining changes/amendments and withheld information, but I think the mappings are actually quite straightforward if you understand the eForms model, which we expect implementers to be familiar with.

@odscjen do you still think some extra documentation is needed for https://github.com/open-contracting/european-union-support/issues/127?

**Comment by odscjen** [comment]
Given the additional documentation and considering that we're expecting implementers to be more familiar with the eForms model than I was when I started this issue then I think you're right and we don't need the extra documentation for #127.

In which case this issue can be closed?
