### ISSUE TITLE
Remove links to GitHub issues if not needed

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/european-union-support#155]
There are several occurrences of https://github.com/open-contracting/european-union-support/issues in `eForms guidance`.

I think many of these are from when merging in Colin's original mappings, where Colin left a link to what was an open issue at the time.

Unless there's something left to discuss in the issue, we can remove these links.

**Comment by odscjen** [comment]
A couple of these links are in the TED guidance.

Of those in the eforms guidance the issues that remain to be discussed are:
* referencing a previous publication - BT-125(i), BT-1251, OPP-090, these all link to https://github.com/open-contracting/european-union-support/issues/54/ which is the general common operations thread
* selection criteria or requirements https://github.com/open-contracting/european-union-support/issues/97/
* CVD awards https://github.com/open-contracting/european-union-support/issues/127 which is in its final stages of working out how to structure the guidance and then these links will be removed.

**Comment by jpmckinney** [comment]
Okay, I removed the remaining links, since the open issues refer to the relevant BTs.
