### ISSUE TITLE
OPP-070-notice: Add guidance

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/european-union-support#159]
@odscjen 

> The guidance for BT-02 is to discard it. As OPP-070 is a notice sub-type to BT-02's notice type I'm assuming OPP-070 can also be discarded?

@jpmckinney 

> Ah, yes. Since eForms is notice-based, it can publish facts about individual notices. OCDS is record-based, so if we wanted to include this field, it would have to be omitWhenMerged in an extension’s schema. I think we discarded BT-02, because fields that don’t appear in compiled releases are not as valuable. Not sure if maybe still useful to include these, though.

@odscjen 

> that all sounds reasonable. I'm also not sure if this would be useful to anyone to include. I'll leave it unmapped for now

**Comment by odscjen** [comment]
There is now guidance for this field:

> Discard

**Comment by jpmckinney** [comment]
Ha! Works for me.
