### ISSUE TITLE
BG-708 Place of performance - deliveryAddresses and deliveryLocations

### ISSUE THREAD

**Issue by odscjen** [open-contracting/european-union-support#160]
This Business Group includes the BTs: BT-727, BT-728, BT-5131, BT-5121, BT-5071, BT-5141, and BT-5101 all of which are found as children of `cac:RealizedLocation`.

Currently the guidance for BT-5131, BT-5121, BT-5071, BT-5141, and BT-5101 starts:

> This field maps to the same `Address` object as created for BT-728-Lot, BT-5131-Lot, BT-5121-Lot, BT-5071-Lot, BT-5141-Lot, and BT-5101-Lot.

With the list adjusted to include all the BG terms except the one in question.

All of these 5 BT's then map to an `Address` object in a `.deliveryAddresses` array, either in `item` or `tender`.

The guidance for BT-727 and BT-728 however doesn't mention any other BT's and in both cases says to map to `deliveryLocations.description`.

The [SDK guidance for this BG](https://docs.ted.europa.eu/eforms/latest/schema/all-in-one.html#performancePlaceSection) makes it clear that all 7 terms do belong together. It also states that multiple `RealizedLocation`'s are possible and that for certain values of BT-727 BT-5141 is mandatory. Both `deliveryAddresses` and `deliveryLocations` allow multiple values but they are not connected. If only one `RealizedLocation` is present this isn't a problem but if multiple `RealizedLocation`s are given then the current OCDS mapping separates the BG out and it will no longer be clear which `description` belongs with which `Address`.

We could add a `description` field to the `Address` objects when used in `deliveryAddresses`?

Should BT-727 (restrictions code) be separated from BT-728 (restrictions additional information) through the use of `details` in addition to a `description` field or are they fine to be concatenated into a single OCDS `description` field?

@jpmckinney @duncandewhurst

**Comment by jpmckinney** [comment]
Aha, yes, it looks like the best resolution is to add `description` to `Address`, instead of splitting it off into a `Location` object.

**Comment by duncandewhurst** [comment]
Good spot! I think it's fine to concatenate BT-727 and BT-728 into `.deliveryAddresses.description`.

**Comment by odscjen** [comment]
Great thanks both, closing this issue as guidance.yaml is now updated

**Comment by odscjen** [comment]
Re-opening as I must have messed up the guidance updating and so the need to create `Address.description` in an extension got missed.

**Comment by odscjen** [comment]
closing again as the extension has now been updated accordingly
