### ISSUE TITLE
python upgrade issues? 

### ISSUE THREAD

**Issue by odscjen** [open-contracting/european-union-support#162]
I notice that the last three commits have all failed at the build stage. The last successful commit was the upgrade python commit https://github.com/open-contracting/european-union-support/commit/77285341579e26a1a7aef51a5c21edb6fde88dcc, has this broken something @jpmckinney?

**Comment by jpmckinney** [comment]
What's failing? We only have one workflow: https://github.com/open-contracting/european-union-support/actions

**Comment by jpmckinney** [comment]
Oh, right, the pre-commit CI integration, like https://results.pre-commit.ci/run/github/143920644/1675177082.O0OOQYQ5Q6uG8kCtWWvJWw

I'll have a look.

**Comment by jpmckinney** [comment]
Looks like poetry-core caused an issue on isort: https://github.com/PyCQA/isort/pull/2078
