### ISSUE TITLE
organization-role.csv is not linked to

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/european-union-support#163]
Or, I can't find a link on a quick search.

**Comment by odscjen** [comment]
No I think you're right and it's not linked in any of the relevant pieces of guidance. No idea how we missed that! It looks as though most just specify the OCDS equivalent code directly, e.g. in OPT-030 the guidance says
> If the value of the field is "serv-prov" add `procurementServiceProvider` to the organization's `.roles` array. If the value of the field is "ted-esen" add `esender` to the organization's `.roles` array.

but given the presence of the orgnaization-role.csv list we can instead write this as 

> Add the code to the organization's `.roles` array according to the [organization role mapping table](codelists/organization-role).

**Comment by odscjen** [comment]
Actually I've had a more thorough search now and it appears that with the exception of the 2 codes in OPT-030 only one other code in organization-roles.csv is in use in eForms and it's not being used in the way it is in this table. (It's "rev-req" which is one of the withheld information codes representing BT-712 Buyer Review Complainants). The only place that features `listName="organisation-role"` is OPT-030.

So we could just revert the sentence I change in OPT-030 and remove the organization-roles.csv table entirely...

**Comment by jpmckinney** [comment]
Aha, sure - I've just copied the table here in case we find a need for it again.

eForms code | eForms label | OCDS code | OCDS label
-- | -- | -- | --
  | ben-own | Beneficial owner | beneficialOwner | Beneficial owner
  | buyer | Buyer | buyer | Buyer
  | cpb-acq | Central purchasing body acquiring supplies and/or services intended for other buyers | centralPurchasingBody | Central purchasing body
  | cpb-awa | Central purchasing body awarding public contracts or concluding framework agreements for works, supplies or services intended for other buyers | centralPurchasingBody | Central purchasing body
  | info-emp | Organisation providing information concerning the general regulatory framework for employment protection and working conditions applicable in the place where the contract is to be performed | informationServiceEmployment | Information service (employment)
  | info-envir | Organisation providing information concerning the general regulatory framework for environmental protection applicable in the place where the contract is to be performed | informationServiceEnvironment | Information service (environment)
  | info-tax | Organisation providing information concerning the general regulatory framework for taxes applicable in the place where the contract is to be performed | informationServiceTaxes | Information service (taxes)
  | mediator | Mediation organisation | mediationBody | Mediation body
  | rev-req | Organisation (or person) requesting review that has or has had an interest in a contract and who has been or risks being harmed by an alleged infringement | reviewRequester | Review requester
  | reviewer | Review organisation | reviewBody | Review body
  | serv-prov | Procurement service provider | procurementServiceProvider | Procurement service provider
  | subcont | Subcontractor | subcontractor | Subcontractor
  | ted-esen | TED eSender | tedEsender | TED eSender
  | tenderer | Tenderer | tenderer | Tenderer
  | winner | Winner | supplier | Supplier

**Comment by odscjen** [comment]
great, I've reverted OPT-030 so I'll close this issue now
