### ISSUE TITLE
Link to guidance for creating a release

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/european-union-support#166]
I'm creating a separate issue for this task from https://github.com/open-contracting/european-union-support/issues/54#issuecomment-1401354963:

>     * [ ]  Review the guidance for creating a release and decide where it will be linked from

Currently, the [instructions](https://standard.open-contracting.org/profiles/eforms/latest/en/operations/#create-a-release) for creating a release are linked from two places: [Release withheld information](https://standard.open-contracting.org/profiles/eforms/latest/en/how/#release-withheld-information) and the mapping for BT-701-notice (notice identifier).

I think it would be helpful to add a sub-heading to [how to use this profile](https://standard.open-contracting.org/profiles/eforms/latest/en/how/) before 'post-processing steps' with a link to the instructions for creating a release so that implementers know to do that before mapping other fields. The heading could be either 'Convert a notice to OCDS format' or 'Publish a notice in OCDS format', e.g.

> ## Convert a notice to OCDS format
>
> [Create a release]() and map each field on the notice according to the [field mappings]().

@jpmckinney does that sound good?

**Comment by jpmckinney** [comment]
Yes, sounds good!

**Comment by duncandewhurst** [comment]
Done in https://github.com/open-contracting/european-union-support/commit/bd2f108980d301664fe2e026634d7254b082e182
