### ISSUE TITLE
BT-769-Lot (Multiple Tenders)

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/european-union-support#174]
This field is [effectively a boolean](https://docs.ted.europa.eu/eforms/latest/schema/procedure-lot-part-information.html#multipleTendersSection). However, it is mapped to a (new) string field `SubmissionTerms.multipleTendersPolicy`. Is there a reason not to map it to a boolean field in OCDS?

Also, in keeping with OCDS's terminology, I think the field should be called `multipleBids` rather than `multipleTenders`.

**Comment by jpmckinney** [comment]
I don't think it's a boolean. I uses the permission codelist, which has 3 values: https://op.europa.eu/en/web/eu-vocabularies/concept-scheme/-/resource?uri=http://publications.europa.eu/resource/authority/permission

We tend to use the `Policy` suffix for fields that use a permission codelist.

Agree to substitute `Bids` for `Tenders`.

**Comment by duncandewhurst** [comment]
For this field specifically, only the 'allowed' and 'not-allowed' values from the permission codelist are permitted:

> The Multiple Tenders business term allows to specify for a given Lot whether a tenderer may submit more than one tender ("allowed") or not ("not-allowed"). This information is marked using the "cbc:MultipleTendersCode" for which only the two previous values of the [permission](https://op.europa.eu/web/eu-vocabularies/at-dataset/-/resource/dataset/permission) codelist are accepted.

**Comment by jpmckinney** [comment]
Ah, good catch! (but also what a confusing way to design their schema)

So, yes, the boolean can be named `multipleBidsAllowed`.

**Comment by duncandewhurst** [comment]
PR for updates: https://github.com/open-contracting-extensions/ocds_submissionTerms_extension/pull/4
