### ISSUE TITLE
eForms 1.7.0 upgrade

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/european-union-support#175]
https://github.com/OP-TED/eForms-SDK/releases/tag/1.7.0

We might want to check that any translation steps are still correct.

New fields:

* BT-195(BT-660)-LotResult
* BT-196(BT-660)-LotResult
* BT-197(BT-660)-LotResult
* BT-198(BT-660)-LotResult
* OPT-060-Lot

Changed to mandatory:

* BT-1311(d)-Lot BT-1311(t)-Lot Deadline Receipt Requests
* BT-132(d)-Lot BT-132(t)-Lot Public Opening Date
* BT-15-Lot BT-15-Part Documents URL
* BT-22-Lot Internal Identifier
* BT-615-Lot BT-615-Part Documents Restricted URL
* BT-707-Lot Documents Restricted Justification

Changed to non-repeatable, and added another level to xPathAbsolute (ChangedSection):

* BT-13716-notice Change Previous Section Identifier
* BT-1501(s)-Contract Modification Previous Notice Section Identifier

Changed from number to integer:

* BT-31-Procedure Lots Max Allowed
* BT-33-Procedure Lots Max Awarded

Other changes that I think make no difference:

* Some `parentNodeId`
* Some `pattern` for identifiers
* Some `xpathAbsolute` (`not-ree-val` to `gro-ree-val`, attribute selectors added/moved)

I checked and it doesn't look like our mappings use any of these codes:

> The content of codelists was updated, aligning with the latest official codelists on EU Vocabularies, including these changes:
> 
> * "criterion": "autorisation" replaced by "authorisation", "misinterpr" replaced by "misrepresent"
> * "currency": removed Kuna (welcome Croatia to the eurozone!), added new Leone (code SLE; old Leone code SLL is still legal tender in Sierra Leone)
> * "non-publication-identifier": added "gro-ree-val" and "ree-val", removed "not-ree-val"
> * "innovative-acquisition": removed "buy-eff", "fp-requ", "org-nov", "other"
> * Corrected labels for "notice-type", "organisation-role", "eu-programme", "country", "winner-selection-status", "nuts"
> * The codelist "corporate-body" was added (used by EU institutions)

**Comment by duncandewhurst** [comment]
> We might want to check that any translation steps are still correct.

Translation steps are still good.

> New fields:
> 
>     * BT-195(BT-660)-LotResult
> 
>     * BT-196(BT-660)-LotResult
> 
>     * BT-197(BT-660)-LotResult
> 
>     * BT-198(BT-660)-LotResult

@odscjen would you be able to take a look at these, since you authored the guidance for the other 'unpublished' fields?

>     * OPT-060-Lot

I can't find any reference to this field in the SDK documentation. However, looking at the [commit](https://github.com/OP-TED/eForms-SDK/commit/a6e2d0d4426d57f19715a67fbf8648c3aa40b33e) in which it was added, I think it can be discarded since the actual data on performance terms is already mapped in BT-70-Lot. I've updated `guidance.yaml` accordingly.

> Changed to mandatory:
> 
>     * BT-1311(d)-Lot BT-1311(t)-Lot Deadline Receipt Requests
> 
>     * BT-132(d)-Lot BT-132(t)-Lot Public Opening Date
> 
>     * BT-15-Lot BT-15-Part Documents URL
> 
>     * BT-22-Lot Internal Identifier
> 
>     * BT-615-Lot BT-615-Part Documents Restricted URL
> 
>     * BT-707-Lot Documents Restricted Justification

No changes are required.

> Changed to non-repeatable, and added another level to xPathAbsolute (ChangedSection):
> 
>     * BT-13716-notice Change Previous Section Identifier
> 
>     * BT-1501(s)-Contract Modification Previous Notice Section Identifier
 
No changes are required. The guidance for both fields is to discard them.

> Changed from number to integer:
> 
>     * BT-31-Procedure Lots Max Allowed
> 
>     * BT-33-Procedure Lots Max Awarded

No changes are required. The OCDS fields to which these fields are mapped are already integers.

**Comment by odscjen** [comment]
guidance.yaml now updated for the withheld fields for BT-660-LotResult

**Comment by duncandewhurst** [comment]
Thanks! I think that this can be closed now.
