### ISSUE TITLE
Use Bids extention for bid statistics but new Statistics extension to complaints statistics

### ISSUE THREAD

**Issue by odscjen** [open-contracting/european-union-support#179]
Currently all the statistics BT's, both both bids and complaints, refer to "#Add a statistic" in `operations.md`. That says to place ALL statistics in the top-level `statistics` array and set the scope to either 'bids' or 'complaints' as appropriate. But that was when we thought `statistics` would be getting moved out of `Bids`. Now that this is not the case we need to redo the guidance for all the bid statistics. This will be:
* BT-710-LotResult
* BT-711-LotResult
* BT-759-LotResult
* BT-760-LotResult

It's probably worth adjusting the current "#Add a statistic" to have 2 common operations, one for #Add a complaints statistics, and another for #Add a bids statistics"

The complaints statistic BTs are:
* BT-635-LotResult
* BT-636-LotResult 
* BT-712(a)-LotResult
* BT-712(b)-LotResult

**Comment by duncandewhurst** [comment]
Sounds good!

**Comment by odscjen** [comment]
guidance.yaml and operations.md updated
