### ISSUE TITLE
Add a .currency field to BidsStatistic

### ISSUE THREAD

**Issue by ColinMaudry** [open-contracting/european-union-support#18]
The `BidsStatistics` may be used to publish statistics about amount of money. In that case, the `value` field must be completed with an optional `currency` field (see II.1.7 "Currency" in F03).

**Comment by ColinMaudry** [comment]
Do we `.currency` in Bid statistics directly, or do we first add it to the EU-specific extension?

**Comment by jpmckinney** [comment]
First in the EU-specific extension, as we can only change the bids extension as part of OCDS 1.2.0.

**Comment by jpmckinney** [comment]
Oops, we did it in the Bids extension: https://github.com/open-contracting-extensions/ocds_bid_extension/pull/40

**Comment by ColinMaudry** [comment]
> Oops, we did it in the Bids extension: [open-contracting-extensions/ocds_bid_extension#40](https://github.com/open-contracting-extensions/ocds_bid_extension/pull/40)

Is that a problem?

**Comment by jpmckinney** [comment]
The rules around patch-level versions are unclear (there's an open PR: https://github.com/open-contracting/standard/pull/674), so it's more a matter of convention – not a problem.
