### ISSUE TITLE
BT-3201-Tender - Tender Identifier: Incoherent guidance

### ISSUE THREAD

**Issue by odscjen** [open-contracting/european-union-support#181]
The current guidance for BT-3201 is

> [Get the bid for the LotTender](operations.md#get-the-bid-for-a-lottender), and map to its `.id`.

Which can be expanded to 
>Get the `Bid` in `bids` whose `id` is equal to the value of `ancestor::efac:LotTender/cbc:ID`. If none exists yet:

>1. Add a `Bid` to `bids`
>1. Set its `.id` to the value of `ancestor::efac:LotTender/cbc:ID`
>1. Add the value of `ancestor::efac:LotTender/efac:TenderLot/cbc:ID` to its `.relatedLots`

>and map to its `id`

The problem is that this means 2 separate values are being mapped to the bids `.id`, `ancestor::efac:LotTender/cbc:ID` and `efac:LotTender/efac:TenderReference/cbc:ID` which is the value of this BT.

From the values given in the [eform guidance docs](https://docs.ted.europa.eu/eforms/latest/schema/all-in-one.html#lotTenderSection)

```xml
<efac:NoticeResult>
    <efac:LotTender>
        <cbc:ID schemeName="tender">TEN-0001</cbc:ID>
               <efac:TenderReference>
            <cbc:ID>BID ABD/GHI-SN/2020-002</cbc:ID>
        </efac:TenderReference>
    </efac:LotTender>
   </efac:NoticeResult>
``` 

it looks as though `ancestor::efac:LotTender/cbc:ID` is the internal reference that allows the different parts of the XML to be linked (so it makes sense for that to be mapped to `bids.details.id`), and `efac:LotTender/efac:TenderReference/cbc:ID` is possibly just the external reference, e.g. the reference code the tenderer is provided with when they submit their bid?

Regardless this inconsistency needs fixing. We could just add an `identifiers` object to `bid.details` to hold BT-3201 in a similar vein to the `identifiers` array that's being added to `tender`?

**Comment by duncandewhurst** [comment]
Good spot! Yes, I think that's the correct approach and it's in keeping with the way we've mapped the technical and internal identifiers for tenders, lots, lot groups and contracts.

**Comment by odscjen** [comment]
Great, I'll update guidance.yaml with a version of the guidance for BT-150-Contract (which is a similar internal id) and then create an new issue to update the Bids extension to add an `identifiers` array.
