### ISSUE TITLE
BT-3202-Contract - Contract Tender ID (Reference): guidance duplication

### ISSUE THREAD

**Issue by odscjen** [open-contracting/european-union-support#182]
The guidance for BT-3202-Contract is long but I think there's an unnecessary duplication within it. The current guidance is:

> - [Get the contract for the SettledContract](operations.md#get-the-contract-for-a-settledcontract) and add the value of this field to its `.relatedBids` array.
       - Get the `ancestor::efac:NoticeResult/efac:LotTender` whose `/cbc:ID` is equal to the value of this field.
       - Get the `ancestor::efac:NoticeResult/efac:TenderingParty` whose `/cbc:ID` matches the `LotTender`'s `/efac:TenderingParty/cbc:ID`.
       - For each `ancestor::efac:TenderingParty/efac:Tenderer`, [get the organization for the tenderer](operations.md#get-the-organization-for-a-tenderer), and:
         - Get the `ancestor::efext:EformsExtension/efac:Organizations/efac:Organization/efac:Company` whose `/cac:PartyIdentification/cbc:ID` is equal to the organization's `.id`, and:
           - Add 'supplier' to the organization's `.roles` array.
         - For each `ancestor::efac:NoticeResult/efac:LotResult` with an `/efac:SettledContract/cbc:ID` equal to the value of `ancestor::efac:SettledContract/cbc:ID`:
           - [Get the award for the LotResult](operations.md#get-the-award-for-a-lotresult).
           - Add an `OrganizationReference` to the award's `.suppliers` array, and:
             - Set the organization reference's `.id` to the organization's `.id`.

The duplication is in these two lines:
> For each `ancestor::efac:TenderingParty/efac:Tenderer`, [get the organization for the tenderer](operations.md#get-the-organization-for-a-tenderer), and:
         - Get the `ancestor::efext:EformsExtension/efac:Organizations/efac:Organization/efac:Company` whose `/cac:PartyIdentification/cbc:ID` is equal to the organization's `.id`,

both lead you to the same organization in `parties`. I think we can just remove the second part so the guidance will become:

> - [Get the contract for the SettledContract](operations.md#get-the-contract-for-a-settledcontract) and add the value of this field to its `.relatedBids` array.
       - Get the `ancestor::efac:NoticeResult/efac:LotTender` whose `/cbc:ID` is equal to the value of this field.
       - Get the `ancestor::efac:NoticeResult/efac:TenderingParty` whose `/cbc:ID` matches the `LotTender`'s `/efac:TenderingParty/cbc:ID`.
       - For each `ancestor::efac:TenderingParty/efac:Tenderer`, [get the organization for the tenderer](operations.md#get-the-organization-for-a-tenderer), and:
           - Add 'supplier' to the organization's `.roles` array.
         - For each `ancestor::efac:NoticeResult/efac:LotResult` with an `/efac:SettledContract/cbc:ID` equal to the value of `ancestor::efac:SettledContract/cbc:ID`:
           - [Get the award for the LotResult](operations.md#get-the-award-for-a-lotresult).
           - Add an `OrganizationReference` to the award's `.suppliers` array, and:
             - Set the organization reference's `.id` to the organization's `.id`.

which is slightly friendlier!

**Comment by duncandewhurst** [comment]
Sounds good. I can't see what purpose the second part was serving.

**Comment by odscjen** [comment]
updated guidance.yaml accordingly
