### ISSUE TITLE
Lint command replaces 1e9999 with Infinity

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/european-union-support#185]
`./manage.py lint output/mapping/eforms/guidance.yaml` replaces `1e9999` in the OCDS example for BT-763-Procedure with `Infinity` which it then reports as invalid:

> BT-763-Procedure: OCDS is invalid: inf is not of type 'integer', 'null' (properties/tender/properties/lotDetails/properties/maximumLotsBidPerSupplier/type)

**Comment by duncandewhurst** [comment]
The command still reports the OCDS example for BT-763-Procedure as invalid, but we already have an open issue about that: https://github.com/open-contracting/ocds-extensions/issues/128

**Comment by jpmckinney** [comment]
Yup, that won't change until the issue is closed.
