### ISSUE TITLE
manage.py error relating to ocds_1_2_draft_extension

### ISSUE THREAD

**Issue by odscjen** [open-contracting/european-union-support#187]
I tried to run `./manage.py lint` on guidance.yaml and got the following error: 

> ocdsextensionregistry.exceptions.DoesNotExist: Extension version matching {'id': '1_2_draft', 'version': 'https://github.com/open-contracting-extensions/ocds_1_2_draft_extension/archive/master.zip'} does not exist.

which is odd as it does? 

I ran `curl -O https://standard.open-contracting.org/profiles/eu/latest/en/_static/patched/release-schema.json` and `pip install -r requirements.txt` prior to the `.manage.py` command and I'd pulled the repo so definitely had the most up-to-date version. Any idea's why I'm getting this error?

**Comment by jpmckinney** [comment]
Note that `pip install -r requirements.txt` will not upgrade dependencies.
