### ISSUE TITLE
BT-708 and BT-737 official and nonofficial languages in tender documents

### ISSUE THREAD

**Issue by odscjen** [open-contracting/european-union-support#189]
BT-737-Lot/Part, `efac:NonOfficialLanguages/cac:Language/cbc:ID` is repeatable within `cac:CallForTendersDocumentReference` as is BT-708-Lot/Part, `efac:OfficialLanguages/cac:Language/cbc:ID`. So a single document can have multiple languages noted as it's official languages and as it's unofficial languages.

e.g. (taken from [pin-only_24-maximal.xml](https://github.com/OP-TED/eForms-SDK/blob/develop/examples/notices/pin-only_24_maximal.xml))

```xml
<cac:CallForTendersDocumentReference>
  <ext:UBLExtensions>
    <ext:UBLExtension>
      <ext:ExtensionContent>
        <efext:EformsExtension>
          <efac:NonOfficialLanguages>
            <cac:Language>
              <cbc:ID>CAT</cbc:ID>
            </cac:Language>
          </efac:NonOfficialLanguages>
          <efac:OfficialLanguages>
            <cac:Language>
              <cbc:ID>ENG</cbc:ID>
            </cac:Language>
            <cac:Language>
              <cbc:ID>FRA</cbc:ID>
            </cac:Language>
          </efac:OfficialLanguages>
        </efext:EformsExtension>
      </ext:ExtensionContent>
    </ext:UBLExtension>
  </ext:UBLExtensions>
  <cbc:ID>Doc1</cbc:ID>
  <cbc:DocumentType>non-restricted-document</cbc:DocumentType>
</cac:CallForTendersDocumentReference>
```

Currently in guidance.yaml we have:
> **BT-708**
>  [Get the document for the document reference](operations.md#get-the-document-for-a-document-reference).
> Lowercase and convert the code into a two-letter [ISO 639-1 code](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes), and add it to the document's `.languages` array.

Which allows for multiple languages but doesn't specify that they are official.

>**BT-737**
> [Get the document for the document reference](operations.md#get-the-document-for-a-document-reference).
> Set the document's `.unofficialTranslation` to `true`.

Which doesn't actually map the language code anywhere.
Following this guidance for the above snippet of XML we'd get the following OCDS:

```json
{
  "documents": [
    {
      "id": "Doc1",
      "languages": [
	 "en",
         "fr"
      ],
      "unofficialTranslation": true
    }
  ]
}
```

which both misses out the unofficial translation language and gives the erroneous impression that the languages given are unofficial.

**Comment by jpmckinney** [comment]
Let's change `unofficialTranslation` to `unofficialTranslations` (plural) and make it a list of languages.

**Comment by duncandewhurst** [comment]
`lint` is reporting `tender/documents/unofficialTranslation` as an additional field so it looks like something still needs to be updated in `guidance.yaml`:

```csv
field,id,title
tender/documents/unofficialTranslation,BT-737-Lot,Documents Unofficial Language,BT-737-Part,Documents Unofficial Language
```

**Comment by odscjen** [comment]
oops, good catch.

The extension is now quite differently modelled from the eForms. So I think the guidance will need updated to:

> **BT-708-Lot**
> [Get the document for the document reference](operations.md#get-the-document-for-a-document-reference).
> Lowercase and convert the code into a two-letter [ISO 639-1 code](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes):
> Get the value of BT-737-Lot, if it is true, add the converted code to the document's `.languages` array.
> Otherwise, add the converted code to the documents `.unofficialTranslations` array.
> [Get the lot for the ProcurementProjectLot](operations.md#get-the-lot-for-a-procurementprojectlot), and add it to the document's `.relatedLots`.

> **BT-737**
> See [BT-708-Lot](<#BT-708-Lot>).

with the -Part version being the same but without the final line.

**Comment by duncandewhurst** [comment]
Hmm, something seems to have gotten out of sync.

https://github.com/open-contracting/european-union-support/commit/bbb26539ec6ab82972e8f7848343931f52bebe76 updated the `xPathAbsolute` for BT-737-Lot to:

```
/*/cac:ProcurementProjectLot[cbc:ID/@schemeName='Lot']/cac:TenderingTerms/cac:CallForTendersDocumentReference/ext:UBLExtensions/ext:UBLExtension/ext:ExtensionContent/efext:EformsExtension/efac:NonOfficialLanguages/cac:Language/cbc:ID
```

That matches the `develop` branch of the eForms SDK repo, but in the 1.8.0 release of eForms, `fields.json` still has it as:

```
/*/cac:ProcurementProjectLot[cbc:ID/@schemeName='Lot']/cac:TenderingTerms/cac:CallForTendersDocumentReference/cbc:LanguageID[../cbc:DocumentStatusCode/text()='non-official']
```

@jpmckinney is it possible that `guidance.yaml` has been updated based on the `develop` branch rather than the 1.8.0 release?

**Comment by jpmckinney** [comment]
Indeed – I accidentally updated to develop, which is more like 1.9.0.

Should I force 1.8.0?

**Comment by duncandewhurst** [comment]
Since there are no implementers yet, I think it's probably fine to continue as-is and then make the necessary updates when 1.9.0 is released.

**Comment by odscjen** [comment]
OK, if we're leaving the XPATH for BT-737 as for the develop branch then the guidance is much simplier and just a case of for BT-708 add the equivalent ID to `languages` (so stays the same as it currently is) and for BT-737 add the equivalent ID to `unofficialTranslation` so I'll update guidance.yaml for those.
