### ISSUE TITLE
II.2.3 allows multiple "Places of performance", but deliveryAddress on allows one .region

### ISSUE THREAD

**Issue by ColinMaudry** [open-contracting/european-union-support#19]
In F01, II.2.3 "Place of performance" can be repeated, but only one `.deliveryAddress` is allowed in the Location extension.

Shall we add a `.deliveryAddresses` array  in Location or a EU specific extension?

**Comment by jpmckinney** [comment]
Mapping done in #21. Still need to add to EU extension.
