### ISSUE TITLE
Remove references to BT-541-Lot, BT-541-LotsGroup, BT-752-Lot

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/european-union-support#192]
Follow-up #188 

The fields were removed in 1.8.0, but are mentioned in a few places.

**Comment by duncandewhurst** [comment]
I've replaced the references to the removed fields with references to the fields they were split into in 52d0c49a3392071bfa7b0a8f62c6b0737fe1fdb2:

* BT-541-Lot -> BT-541-Lot-FixedNumber, BT-541-Lot-ThresholdNumber, BT-541-Lot-WeightNumber
* BT-541-LotsGroup -> BT-541-LotsGroup-FixedNumber, BT-541-LotsGroup-ThresholdNumber, BT-541-LotsGroup-WeightNumber
* BT-752-Lot -> BT-752-Lot-ThresholdNumber, BT-752-Lot-WeightNumber
