### ISSUE TITLE
BT-11-Procedure-Buyer uses TED_CA_TYPE

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/european-union-support#208]
However, [TED_CA_TYPE](https://standard.open-contracting.org/profiles/eu/latest/en/forms/F02/#I.4) has different codes than https://op.europa.eu/en/web/eu-vocabularies/concept-scheme/-/resource?uri=http://publications.europa.eu/resource/authority/buyer-legal-type, e.g. BODY_PUBLIC vs body-pl

We should change to 'eu-buyer-legal-type' or something.

**Comment by odscjen** [comment]
eu-buyer-legal-type seems a good name to me
