### ISSUE TITLE
BT-809: Selection Criteria possible xpath error and updated selection-criteria codelist

### ISSUE THREAD

**Issue by odscjen** [open-contracting/european-union-support#218]
This new field has been added with SDK 1.12.0 (see https://github.com/open-contracting/european-union-support/issues/215) 

From the SDK docs this is essentially the same as BT-747 so could use the same mapping, but the `fields.json` file has brought through what I think is the wrong xpathAbsolute so [I'm waiting on confirmation of that](https://github.com/OP-TED/eForms-SDK/discussions/990) before I put the mapping that had been used for BT-747-Lot in for this new field.

If this is the case, the [selection-criterion codelist](https://op.europa.eu/en/web/eu-vocabularies/concept-scheme/-/resource?uri=http://publications.europa.eu/resource/authority/selection-criterion) that is used has changed significantly. The 4 codes that are mapped to OCDS in the [`selection-criteria.csv`](https://standard.open-contracting.org/profiles/eforms/latest/en/codelists/selection-criterion/) mapping table have all been retired and 37 new codes added. These are much more nuanced. The BT-747 mapping went to `criteria.type` which has a closed codelist, hence the need for a mapping table. I don't think it's worth adding all of these codes to the OCDS selectionCriterionType codelist as they are so specific so possibly only relevant to the EU, so I think we've 2 options:
1. map all the new codes to the 4 existing OCDS codes. This will lose all of that newly introduced specificity in the eforms codes. These could be retained by appending the label to the criterion's `.description` where BT-750 (Selection Criterion Description) is already being mapped but this would make it unstructured.
2. Add an array of `Classification` objects (e.g. `selectionClassifications`) to `SelectionCriterion` and use the codes as they are. This would allow that specificity to be retained in a structured way. It could be combined with the first bit of option 1 so that `criteria.type` is still being filled in with the broader types. If we put this in the Selection Criteria extension I think though it could confuse things for non-EU publishers around how it should be used when `type` is already there so the guidance would need to be very clear around its use.

@jpmckinney

**Comment by jpmckinney** [comment]
> map all the new codes to the 4 existing OCDS codes

https://extensions.open-contracting.org/en/extensions/selectionCriteria/master/codelists/#selectionCriterionType.csv

Looks like this would be:

* economic: slc-stand\* (Selection criteria based on the level of financial risk status of the economic operator.)
* technical: slc-abil\* (Selection criteria based on the technical and qualification capacities of the economic operator.)
* suitability: slc-suit\* (Selection criteria based on ability of the economic operator to attend professional exercise.)
* other:
  * slc-sche-* (Selection criteria based on quality assurance schemes and environmental management standards.)
  * slc-sec\* (Selection criteria based on the ability to secure information, processes, and certification on deliveries by the economic operator.)
 
Codes no longer valid:

- ef-stand
- sui-act
- tp-abil
- other

I don't think there is much value in adding more classifications arrays everywhere.

We can just add a string `subType` field.

**Comment by odscjen** [comment]
Answer from the eForms maintainers

> The online documentation has now been corrected, and the corrected version is available on the linked page:
https://docs.ted.europa.eu/eforms/latest/schema/procedure-lot-part-information.html#tenderingTermsRelatedInformationTable

**Comment by odscjen** [comment]
note to self, replace references to BT-747, BT-749 with references to BT-809

**Comment by jpmckinney** [comment]
I think just delete them.

That said, the way eForms versioning works, new versions can add or remove things, but ALL versions are supported by TED. So it *is* possible that some country is implementing e.g. eForms 1.0.7, where only the old codes are present. And if that country wants to implement OCDS, they would be happier to see the old codes mapped.

But, our approach so far has been to just model the most recent version. This is practical (having different versions for each version of eForms is a headache). If a user does need mappings for old versions, then either: the mapping is obvious to a reader anyway, without us making it explicit; or, we could just checkout an old version and send them the mapping.
