### ISSUE TITLE
Section IV.2.1 in F02 cannot link to a specific ocid

### ISSUE THREAD

**Issue by ColinMaudry** [open-contracting/european-union-support#22]
In F02 "Contract notice", the guidance for IV.2.1 to link to the previous release(s) states:

> Discard. The previous publication concerning this procedure is the OCDS release with the same ocid as this release and with the nearest earlier date to this release.

Problem: a Prior Information Notice can contain several contracts, each one generating a different `ocid`. There is apparently no way from F02 to determine which `ocid` to link back to.

I also don't know how we determine the `ocid` in F02.

**Comment by jpmckinney** [comment]
OCID creation is described on this page, which is one of the first links on the F02 page: https://staging.standard.open-contracting.org/profiles/eu/master/en/operations/#create-a-release

**Comment by ColinMaudry** [comment]
OK, I knew, but I had forgotten :angel:

**Comment by ColinMaudry** [comment]
OK, so the OBJECT_CONTRACT/REFERENCE_NUMBER in F01 is what they link back to from F02, right?

I'm still looking for a multi-OBJECT_CONTRACT F01 to check.

**Comment by ColinMaudry** [comment]
I mean the ocid built from REFERENCE_NUMBER, of course.

**Comment by jpmckinney** [comment]
Unfortunately REFERENCE_NUMBER is optional, and we don't have guidance / solutions for what to do if it is missing. I responded via email with that and another alternative.

**Comment by jpmckinney** [comment]
Fixed in https://github.com/open-contracting-extensions/european-union/commit/f79914b75516f047aa08d0c3a4fd8efe03562216
