### ISSUE TITLE
BT-105: map new Procurement procedure type authority table codes to procurementMethod

### ISSUE THREAD

**Issue by odscjen** [open-contracting/european-union-support#230]
Issue copied over from https://github.com/open-contracting-extensions/eforms/issues/14

BT-105-Procedure uses the [Procurement procedure type](https://op.europa.eu/en/web/eu-vocabularies/concept-scheme/-/resource?uri=http://publications.europa.eu/resource/authority/procurement-procedure-type) authority table which as been updated since the mapping for this BT was completed. The authority table maps to the codes from the [method.csv](https://standard.open-contracting.org/latest/en/schema/codelists/#method) codelist via the [procurement-procedure-type](https://standard.open-contracting.org/profiles/eforms/latest/en/codelists/procurement-procedure-type/) mapping table. 

Changes to the authority table are:

eForms code | eForms label | Valid since 
-- | -- | -- 
exp-int-rail | Based on Article 5(3b) of Regulation (EC) No 1370/2007, competent authorities may make public their intentions to award a public service contract for public passenger transport services by rail by publishing an information notice in the Official Journal of the European Union. | 2024-03-13 
oth-mult | Multiple stage procedure not covered by other concepts in this table. | 2019-09-18 
oth-single | Single stage procedure not covered by the other concepts in this table. | 2019-09-18

**Comment by jpmckinney** [comment]
For `oth-*`, we'll need to have no mapping to procurementMethod.

exp-int-rail is described at https://eur-lex.europa.eu/eli/reg/2007/1370

> competent authorities may decide to apply the following procedure:
> 
> Competent authorities may make public their intentions to award a public service contract for public passenger transport services by rail by publishing an information notice in the Official Journal of the European Union.
> 
> That information notice shall contain a detailed description of the services that are the subject of the contract to be awarded, as well as the type and the duration of the contract.
> Operators may express their interest within a period fixed by the competent authority which shall not be less than 60 days following the publication of the information notice.
> 
> If after the expiration of that period:
> 
> (a)  only one operator has expressed its interest in participating in the procedure to award the public service contract;
> (b)  that operator has duly proved that it will in fact be able to provide the transport service complying with the obligations established in the public service contract;
> (c)  the absence of competition is not the result of an artificial narrowing of the parameters of the procurement; and
> (d)  no reasonable alternative exists;
> 
> the competent authorities may start negotiations with this operator in order to award the contract without further publication of an **open tendering procedure**.

So, basically, it's an open procedure, unless there's only one submission, in which case it's a negotiated procedure.

I think that means we can map it to 'open'.

**Comment by odscjen** [comment]
Great, I also just noticed that we've already got a note in the guidance saying 
> `tender.procurementMethod` is not set for "oth-mult" and "oth-single"

 so it's just the one change needed
