### ISSUE TITLE
BT-03-Notice: map new form type authority codes to form-type mapping table

### ISSUE THREAD

**Issue by odscjen** [open-contracting/european-union-support#231]
Copied issue over from https://github.com/open-contracting-extensions/eforms/issues/13

BT-03-Notice uses the [form type authority table](https://op.europa.eu/en/web/eu-vocabularies/concept-scheme/-/resource?uri=http://publications.europa.eu/resource/authority/form-type). OCDS mapping has the values from this BT map to `tender.status` via the `form-type` mapping table. Since this was created 3 new codes have been added to the authority table and 1 deprecated:

eForms code | eForms label | Valid since | Valid until
-- | -- | -- | --
bri | Business registration information | 2021-09-29 | 
completion | Completion | 2024-09-25 |
consultation | Consultation | 2024-09-25 |
change | Change | 2019-09-18 | 2023-06-13	

The form-type mapping table should be updated to reflect these changes.

**Comment by odscjen** [comment]
Suggest the following mapping (as well as removing the deprecated code)

eForms code | eForms label | Release tag | Tender status
-- | -- | -- | --
bri | Business registration information | ? | 
completion | Completion | contractUpdate | 
consultation | Consultation | planning | planning

I don't think "bri" really goes with the rest of these, I'm inclined to say that if BT-03 is this code then discard the entire notice as OCDS isn't structured to publish this type of information?

**Comment by jpmckinney** [comment]
Looks good. Yes, we can discard bri.
