### ISSUE TITLE
F23, F25, and details about the value of concessions 

### ISSUE THREAD

**Issue by ColinMaudry** [open-contracting/european-union-support#27]
F23 and F25 have fields that look similar:

- F23, in V.2.4) (`/AWARD_CONTRACT/AWARDED_CONTRACT/INFO_ADD_VALUE`), "Any other details relevant to the value of the concession accord to Art. 8(3) of the directive" ([this section](https://eur-lex.europa.eu/legal-content/FR/TXT/?uri=OJ%3AJOL_2014_094_R_0001_01#d1e1760-1-1) is about the method to calculate the value of a concession)
- F25, in II.1.5) (`/OBJECT_CONTRACT/CALCULATION_METHOD`) "Method used for calculating the estimated value of the concession"

I've mapped `CALCULATION_METHOD` to `award.concession.valueCalculationMethod` (the name may be improved), and I wonder whether `INFO_ADD_VALUE` could also map to it. They seem semantically very close.

Could both F23 and F25 be filled in a concession procedure, and could `INFO_ADD_VALUE` and  `CALCULATION_METHOD` clash?

**Comment by jpmckinney** [comment]
My understanding is that F23 and F25 are not used together for the same contracting process, so those elements can be mapped to the same field.

**Comment by ColinMaudry** [comment]
Thanks! Done in #28 and #29.

**Comment by jpmckinney** [comment]
Regarding my comment in #29, I didn't notice that F23 discloses this in section V whereas F25 discloses this in section II. Those sections have different semantics, so the mapping should be to different fields.
