### ISSUE TITLE
Link to the TED schemas page is broken

### ISSUE THREAD

**Issue by ColinMaudry** [open-contracting/european-union-support#34]
The following link is used in the documentation (e.g. [F14](https://standard.open-contracting.org/profiles/eu/master/en/F14/#guidance-for-changes-change)) : https://op.europa.eu/en/web/eu-vocabularies/tedschemas, but it's broken.

Here is the right one: https://op.europa.eu/en/web/eu-vocabularies/e-procurement/tedschemas

**Comment by ColinMaudry** [comment]
Fixed in cd36f88bbc7e614bd681

**Comment by jpmckinney** [comment]
Thanks! I re-built the docs and deployed.
