### ISSUE TITLE
TED XML schemas update (R2.0.9.S05)

### ISSUE THREAD

**Issue by ColinMaudry** [open-contracting/european-union-support#50]
@jpmckinney The European Commission has updated the TED XML schema with a few new elements https://webgate.ec.europa.eu/fpfis/wikis/pages/viewpage.action?pageId=876970615

Quoting the blog post:

These 4 elements have been added to R2.0.9.S05:

- PT_REQUEST_EXPRESSION_INTEREST : Request for expression of interest - only for rail (art. 5(3b) of 1370/2007)
- PT_DA_EXCEPTIONAL_CIRCUMSTANCE_RAIL : Direct award, if justified by exceptional circumstances - only for rail (art. 5(3a) of 1370/2007
- PT_DA_MARKET_NETWORK_RAIL : Direct award, if justified by relevant structural and geographical characteristics of the market and the network - only for rail (art. 5(4a) of 1370/2007)
- PT_DA_OPERATOR_MANAGER_RAIL : Direct award, to an operator which manages simultaneously the entire or the major part of the railway infrastructure on which the services are provided - only for rail (art. 5(4b) of 1370/2007)

There will be no change to the R.2.0.8 (defence).

Do we intend to stick to the latest release of the TED XML schemas?

@benccs Does your team plan to make use of these new elements?

**Comment by jpmckinney** [comment]
T01 is very rarely used in TED. We're not expecting any non-UK implementers of the profile until the eForms mapping is added. So, it depends on whether the UK implementers will be adding corresponding elements (these elements refer to EU legislation, but there might be a correspondence to UK legislation).

**Comment by BenCCS** [comment]
@ColinMaudry, @jpmckinney - We're currently taking advice on how this is covered by UK legislation. As you say, T01 is rarely used, with only one such notice published on Find a Tender so far.

**Comment by Ben-Hickling** [comment]
I can now confirm that we will be adding these procedure types to T01 in the UK as well. In the OCDS output we plan to follow the pattern used in the EU profile at https://standard.open-contracting.org/profiles/eu/latest/en/forms/T01/#IV.1.1, setting tender.procurementMethod to "direct" and tender.procurementMethodDetails to the string from the form (minus the article/directive information):

- "Request for expression of interest - only for rail"
- "Direct award, if justified by exceptional circumstances - only for rail"
- "Direct award, if justified by relevant structural and geographical characteristics of the market and the network - only for rail"
- "Direct award, to an operator which manages simultaneously the entire or the major part of the railway infrastructure on which the services are provided - only for rail"

**Comment by jpmckinney** [comment]
Hi @Ben-Hickling, for an expression of interest, wouldn't the competitive conditions be 'open' or 'selective'?

**Comment by Ben-Hickling** [comment]
@jpmckinney - You're right, we shouldn't use "direct" for the request for expression of interest. I'm thinking "open" may be best for that as anyone could express an interest. Would you agree?

**Comment by jpmckinney** [comment]
Yes, I think so!

**Comment by Ben-Hickling** [comment]
Hi, @jpmckinney. I think art. 5(3b) must be referring to the updated text at https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX%3A02007R1370-20171224. That contains 3b as follows:

> 3b.  In application of paragraph 3, competent authorities may decide to apply the following procedure:
> 
> Competent authorities may make public their intentions to award a public service contract for public passenger transport services by rail by publishing an information notice in the Official Journal of the European Union.
> 
> That information notice shall contain a detailed description of the services that are the subject of the contract to be awarded, as well as the type and the duration of the contract.
> 
> Operators may express their interest within a period fixed by the competent authority which shall not be less than 60 days following the publication of the information notice.
> 
> If after the expiration of that period:
> 
> (a) only one operator has expressed its interest in participating in the procedure to award the public service contract;
> 
> (b) that operator has duly proved that it will in fact be able to provide the transport service complying with the obligations established in the public service contract;
> 
> (c) the absence of competition is not the result of an artificial narrowing of the parameters of the procurement; and
> 
> (d) no reasonable alternative exists;
> 
> the competent authorities may start negotiations with this operator in order to award the contract without further publication of an open tendering procedure.

That sounds more like open to me, but perhaps it doesn't say whether there are any restrictions on who can express an interest. If we can't know, should it be left out like for "Award procedure with prior publication of a concession notice" in F23 and F25?

**Comment by jpmckinney** [comment]
So 'selective' means a two-stage procedure where first (1) there's a request to participate (can be called an expression of interest, but that term is used for other things as well) to which anyone can submit, then (2) the buyer applies pre-qualification/pre-selection criteria, then (3) there's a request for tender from the qualified suppliers. (3b) describes an exception, whereby the buyer can skip 3 if there is a single bidder.

'limited' is the code used when there's a restriction on who can request to participate.
