### ISSUE TITLE
BT-738, BT-632, BT-708, BT-727, BT-631, BT-16, BT-19, BT-769: Require new OCDS extension fields

### ISSUE THREAD

**Issue by ColinMaudry** [open-contracting/european-union-support#55]
Although we have created many extensions to cover the fields of standard forms, eForms introduces fields that require more fields to be created, and possibly new extensions:

- [ ] Notice Publication Date Preferred (BT-738) => Communication extension
- [ ] (Atypical) Tool Name (BT-632) => Communication extension
- [ ] Documents Official Language (BT-708) => Document Details (Add it to the document's `.languages` array.)
- [ ] Place Performance Services Other (BT-727) There are other restrictions on the place of performance (e.g. "anywhere in the European Economic Area", "anywhere in the given country").  => item's `deliveryLocation.description`
- [ ] Dispatch Invitation Interest (BT-631) The estimated date of dispatch of the invitations to confirm interest. => Communication. The extension should be extended to lots. In guidance: `.communication.invitationToConfirmInterest.startDate`
- [ ] Organisation Part Name (BT-16) The name of a part of an organisation (e.g. the relevant department of a large buyer). => I can't think of an organisation extension where it would fit, thus it could go to the EU extension
- [ ] Submission Nonelectronic Justification (BT-19) The justification for electronic submission of tenders, requests to participate, or expressions of interest not being possible. => `.nonElectronicRationale` in Submission terms
- [ ] Multiple tenders (BT-769) Tenderers may submit more than one tender (for a given lot). => `.multipleTendersPolicy` in Submission terms

**Comment by ColinMaudry** [comment]
BT-13, Additional Information Deadline: the time limit for requesting additional information about the procurement procedure.

@jpmckinney Does it fit with `Tender.tenderPeriod.endDate` or do we mint a new dedicated field in the Communication extension?

**Comment by yolile** [comment]
> BT-13, Additional Information Deadline: the time limit for requesting additional information about the procurement procedure.

That sounds like `tender.enquiryPeriod.endDate` to me :smiley:

**Comment by ColinMaudry** [comment]
That's right, thanks @yolile!

**Comment by duncandewhurst** [comment]
We'll generate an updated list of extension changes from `guidance.yaml`.
