### ISSUE TITLE
BT-23: How to map 'combined' contract nature (procurement category)

### ISSUE THREAD

**Issue by ColinMaudry** [open-contracting/european-union-support#56]
In OCDS we support the following procurement categories:

- works
- services
- supplies

With the possibility to add additional procurement categories via an [open codelist](https://standard.open-contracting.org/1.1/en/schema/codelists/#extended-procurement-category).

In eForms, they support the same values + 'combined' ("Provision of any combination of services, supplies and/or works").

How do we reflect that in the mapping?

Can we leave `tender.mainProcurementCategory` empty and

- add 'combined' to `tender.additionalProcurementCategories`?
- OR add 'works', 'services' and 'supplies' to `tender.additionalProcurementCategories`?

I think I saw somewhere that there were discussions around a 'combined' option in OCDS.

**Comment by jpmckinney** [comment]
I think 'combined' (or similar) better fits the semantics, since we don't know if it's goods+services, goods+works, etc.

**Comment by jpmckinney** [comment]
Here is the EU codelist: https://op.europa.eu/en/web/eu-vocabularies/concept-scheme/-/resource?uri=http://publications.europa.eu/resource/authority/contract-nature

**Comment by jpmckinney** [comment]
'combined' is mapped directly to additionalProcurementCategories.
