### ISSUE TITLE
Procedure description: different guidance for design contests?

### ISSUE THREAD

**Issue by ColinMaudry** [open-contracting/european-union-support#57]
For the description of the procedure in standard forms, we wrote the following guidance:

> Map to the lot's `.description`
> **F12, F13**: Instead, map to `tender.description`

@jpmckinney Do you remember why design contests (notice and result notice) had special guidance in this case? They are not alotted?

**Comment by ColinMaudry** [comment]
Actually that's not an issue for eForms since BT-23 (Main nature) and BT-531 (Additional nature) explicitly map to two xpaths: one for the whole procedure and one for each lot. I don't know if both the procedure xpath and the lot xpath can be present at the same time.

**Comment by jpmckinney** [comment]
That's right - F12 and F13 don't have lots.

**Comment by ColinMaudry** [comment]
See also https://github.com//open-contracting//european-union-support//issues//58#issuecomment-990799866
