### ISSUE TITLE
New roles in eForms

### ISSUE THREAD

**Issue by ColinMaudry** [open-contracting/european-union-support#59]
eForms introduces new roles (I have crossed the roles that are not new):

1. Beneficial owner
2. ~~Buyer~~
3. Central purchasing body acquiring supplies and/or services intended for other buyers (this used to be a single code in TED, it means *wholesaler*)
4. Central purchasing body awarding public contracts or concluding framework agreements for works, supplies or services intended for other buyers (this used to be a single code in TED, it means *contract intermediary*)
5. Organisation providing information concerning the general regulatory framework for employment protection and working conditions applicable in the place where the contract is to be performed
6. Organisation providing information concerning the general regulatory framework for environmental protection applicable in the place where the contract is to be performed
7. Organisation providing information concerning the general regulatory framework for taxes applicable in the place where the contract is to be performed
8. Mediation organisation
9. Organisation (or person) requesting review that has or has had an interest in a contract and who has been or risks being harmed by an alleged infringement
10. ~~Review organisation~~
11. Procurement service provider
12. Subcontractor
13. TED eSender
14. ~~Tenderer~~
15. ~~Winner~~

This topic isn't new: https://github.com/open-contracting/standard/issues/1180 cc @JachymHercher

**Comment by ColinMaudry** [comment]
The [current partyRole codelist](https://github.com/open-contracting-extensions/ocds_eu_extension/blob/1.1/codelists/%2BpartyRole.csv) from the EU extension.

**Comment by ColinMaudry** [comment]
I think 6. and 7. are sub codes of "An organization that can provide information regarding specific aspects of the contracting".

**Comment by ColinMaudry** [comment]
Since TED forms and eForms will live in parralell, I guess we must support codes from both.

**Comment by ColinMaudry** [comment]
"Subcontractor" would be added in the subcontracting extension.

The following could be added to core:

- beneficial owner
- mediation organization

The others would be added to the EU extension.

**Comment by ColinMaudry** [comment]
I have proposed "review requester"

**Comment by jpmckinney** [comment]
I believe this has been addressed in other issues about the specific fields relating to each role. (Roles are modelled quite differently in the XML compared to the spreadsheet.)
