### ISSUE TITLE
BT-509: eDelivery gateway URL

### ISSUE THREAD

**Issue by ColinMaudry** [open-contracting/european-union-support#62]
@JachymHercher The description of eDelivery Gateway URL in the annex to the eForms regulation:

> The organisation's uniform resource locator for exchange of data and documents.

It's not the buyer's profile, it's an interface to exchange documents securely using eID (part of the CEF infrastructure):

> eDelivery is a building block that provides technical specifications and standards, installable software and ancillary services to allow projects to create a network of nodes for secure digital data exchange. By building with eDelivery, public and private organisations from different sectors can easily create a safe and interoperable channel to transfer documents and data among each other over a public or private network.

(https://ec.europa.eu/cefdigital/wiki/display/CEFDIGITAL/eDelivery)

Do you think the eDelivery system is specific to Europe for document interchange? If specific, I would add and document it in the EU OCDS extension. Otherwise, probably in the Communication extension.

Thanks!

**Comment by JachymHercher** [comment]
I think there might have been some ambition/news about some extra-EU countries using eDelivery, but I am really not sure. Maybe @ec-mcs would know?

**Comment by ColinMaudry** [comment]
Guidance:

> Map to the party's `.eDeliveryEndpoint`

I suggest we add it to the EU extension.

**Comment by jpmckinney** [comment]
Sounds good to me.

**Comment by jpmckinney** [comment]
I renamed eDeliveryEndpoint to eDeliveryGateway, as I can't find much use of the term "endpoint" with respect to eDelivery, and I don't know if Gateway has a special meaning in eDelivery context - but might as well reuse it.
