### ISSUE TITLE
OCDS date vs. xsd:date

### ISSUE THREAD

**Issue by ColinMaudry** [open-contracting/european-union-support#66]
eForms uses `xsd:date` datatype to express dates that don't require a time. According to the XML Schema recommendation, an `xsd:date` is the date portion of an `xsd:dateTime` object, with the possibility to add an indication of the timezone.

Valid examples of `xsd:date`:

- 2021-10-09
- 2021-10-09+02:00

Question: is this datatype fully compatible with OCDS date, or does a time portion must be added? I see that in the EU standard forms guidance dates (e.g. "20191127") are mapped as-is, without conversion.

Ideally we should require a conversion of the dates both in eForms and SF guidance so that they match the OCDS date format: `YYYY-MM-DDThh:mm:ssTZ`

What do you think @jpmckinney?

**Comment by jpmckinney** [comment]
> Standard forms use YYYYMMDD, eForms uses `xsd:date`.

Aha, so yes, you will need to edit this file (it's in the profile itself, rather than european-union-support): https://github.com/open-contracting-extensions/european-union/blob/latest/docs/operations.md
