### ISSUE TITLE
BT-04 Procedure identifier

### ISSUE THREAD

**Issue by ColinMaudry** [open-contracting/european-union-support#67]
BT-04 (Procedure identifier)

> The European Public Procurement Procedure Identifier, a unique identifier of a procurement procedure. Including this identifier in all published versions of this notice (e.g. published on TED, national publication portals, regional publication portals) allows unique identification of procurement procedures around the EU.

This BT is not present at planning stage (notices 1-9) and only appears from the tendering stage. That means we can't add it in the ocid from the start, unless the procedure starts with a tender notice.

On solution could be to have two ocid: one for the planning stage and one for the rest of the procedure. They would be linked via `.relatedProcesses`. However, as there can also be a process split between the tender and the award stages (certain lots having their own procedure), we may end up with data that is hard to analyse.

**Comment by ColinMaudry** [comment]
OK, then the obvious mapping for the procedure identifier would be the ocid when tendering starts (after planning). However I'm not sure it will work with multi-staged procedures.

OCDS changes ocid at each stage:

> In multiple stage procedures (e.g. framework agreements with reopening of competition), each round of competition is treated as a separate contracting process.

while it doesn't change in eForms (right @JachymHercher ?)

**Comment by jpmckinney** [comment]
Yes, in eForms, it is just one procedure.

I think the mapping for procedure identifier is probably `tender.id`.

There is no mapping for ocid (it needs an OCDS prefix anyway).

**Comment by ColinMaudry** [comment]
Makes sense. I had mapped BT-22 Internal Identifier to `tender.id`, I moved it to the lot's `.description`.
