### ISSUE TITLE
BT-744: Submission Electronic Signature

### ISSUE THREAD

**Issue by ColinMaudry** [open-contracting/european-union-support#68]
Definition:

> Advanced or qualified electronic signature or seal (as defined in [Regulation (EU) No 910/2014](https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=uriserv:OJ.L_.2014.257.01.0073.01.ENG)) is required.

@JachymHercher I'm not sure what this BT is about: is it the regular electronic signature that applies in virtually any electronic procedure, or is it something more advanced?

In a nutshell:

- can we call the to-be-created OCDS field `electronicSignature: true/false`, or would it be too broad?
- doesn't `BT-17 Submission Electronic: required` necessarily imply that `BT-744 Submission Electronic Signature: true`?

**Comment by JachymHercher** [comment]
The "advanced or qualified" is what makes the difference (see e.g. https://en.wikipedia.org/wiki/EIDAS#Regulated_aspects_in_electronic_transactions for their explanation). You can have electronic signatures that are neither. 

Consequently, if you leave this out, then indeed the field would be too broad; and no electronic submission does not imply advanced or qualified electronic signature, exactly because it could be non-advanced.

**Comment by ColinMaudry** [comment]
Here is what I came up with in the guidance:

> Set the lot's `.submissionTerms.advancedElectronicSignaturePolicy` to 'required'

**Comment by jpmckinney** [comment]
Sounds good!

**Comment by jpmckinney** [comment]
Mapped as discussed.

**Comment by duncandewhurst** [comment]
In eForms, this field is a boolean, is there a reason not to have a boolean field in OCDS?

**Comment by jpmckinney** [comment]
Hmm, possibly because in the regulation it was a codelist.

How are electronicSubmissionPolicy, variantPolicy, electronicCataloguePolicy – and electronicInvoicingPolicy in contractTerms – implemented in eForms?

Those are the other ones using the permission codelist.

**Comment by jpmckinney** [comment]
So the esignature-submission codelist used by BT-744-Lot really is true/false https://github.com/OP-TED/eForms-SDK/blob/main/codelists/indicator_esignature-submission.gc

We can replace `Policy` with `Required` and make it a boolean.

To answer my question:

* BT-17 SubmissionElectronic uses esubmission, which is 3-value: https://github.com/OP-TED/eForms-SDK/blob/develop/codelists/permission_esubmission.gc
* BT-63 Variants uses permission (3-value)
* BT-764 Submission Electronic Catalogue uses ecatalog-submission (3-value)
* BT-743 Electronic Invoicing uses einvoicing (3-value)

**Comment by duncandewhurst** [comment]
Thanks!

> We can replace `Policy` with `Required` and make it a boolean.

I've done this on my local branch.
