### ISSUE TITLE
BT-771, BT-772 Late Tenderer Information

### ISSUE THREAD

**Issue by ColinMaudry** [open-contracting/european-union-support#69]
Definition:

> Whether tenderer-related information can be supplemented even after the submission deadline.

Basically, whether the information of a tenderer can me modified or added after the submission deadline/tendering period.

I'm not sure whether an existing field would fit (`submissionMethodDetails`?), or if we need a new one.

It's bound to a short [codelist](https://op.europa.eu/en/web/eu-vocabularies/concept-scheme/-/resource?uri=http://publications.europa.eu/resource/authority/missing-info-submission).

**Comment by ColinMaudry** [comment]
It seems to me it's a corner case, plus the codes are not very expressive. I consequently suggest the following guidance:

> Map the [definition of the code](https://op.europa.eu/en/web/eu-vocabularies/concept-scheme/-/resource?uri=http://publications.europa.eu/resource/authority/missing-info-submission) to `.submissionMethodDetails`

**Comment by jpmckinney** [comment]
I think there are often rules for late submission of missing documents, but the policy is very rarely expressed in data, so I think it's fine to do as you suggest.

**Comment by jpmckinney** [comment]
Mapped as discussed.
