### ISSUE TITLE
Replacing 'boolean' with `boolean` in mapping CSVs

### ISSUE THREAD

**Issue by ColinMaudry** [open-contracting/european-union-support#7]
Until now, in the mapping files, I have consistently expressed boolean values as 'true' or 'false', using single quotes.

However, \`true\` and \`false\`, with back ticks, are more appropriate.

**Comment by jpmckinney** [comment]
I've fixed this while reviewing the mappings :)

**Comment by ColinMaudry** [comment]
Thanks!
