### ISSUE TITLE
BT-538 Duration Other

### ISSUE THREAD

**Issue by ColinMaudry** [open-contracting/european-union-support#70]
On top of the duration in days/months/years and the start and end dates, eForms offers the possibility to express duration according to a wide [code list](https://op.europa.eu/en/web/eu-vocabularies/concept-scheme/-/resource?uri=http://publications.europa.eu/resource/authority/timeperiod). OCDS has no equivalent.

Users have the possibility to use this field as a replacement for the other types of durations.

Since it's tightly bound to a EU code list, I suggest we add it to the EU extension.

**Comment by ColinMaudry** [comment]
I propose we add a `.other` field in the Period object via the EU extension, using the EU codelist.

**Comment by jpmckinney** [comment]
I renamed `other` to `description` in 9707454, since `other` is somewhat meaningless, and `description` can perhaps be used for e.g. "the time between the winter solstice and spring equinox" or other unlikely variations.

**Comment by odscjen** [comment]
ocds examples were still using "other", I've changed that to "description" now

**Comment by jpmckinney** [comment]
Thank you! 🙏
