### ISSUE TITLE
BG-72 Selection Criteria Second Stage Invite Number (selection criteria weight)

### ISSUE THREAD

**Issue by ColinMaudry** [open-contracting/european-union-support#73]
Definition:

> Information about a number linked to the selection criteria (or criterion) used for selecting the candidates to be invited for the second stage of the procedure.

It contains the following BTs:

- BT-752 Selection Criteria Second Stage Invite Number: A number linked to the selection criteria (or criterion).
- BT-7531 Selection Criteria Second Stage Invite Number Weight: Whether the number linked to a selection criterion (or selection criteria) is a type of weight (e.g. a percentage) => [codelist](https://op.europa.eu/en/web/eu-vocabularies/concept-scheme/-/resource?uri=http://publications.europa.eu/resource/authority/number-weight)
- BT-7532 Selection Criteria Second Stage Invite Number Threshold: Whether the number linked to a selection criterion (or selection criteria) is a type of threshold (e.g. a minimum score, a maximum number of tenders with the highest score passing) => [codelist](https://op.europa.eu/en/web/eu-vocabularies/concept-scheme/-/resource?uri=http://publications.europa.eu/resource/authority/number-threshold)

This convoluted, multi-purpose data structure enables the expression of any numeric feature of selection criteria.

These semantics could be added to the selection criteria extension. Do we keep the same structure? It would ease the eForms mapping, but might not work for non-EU procedures.

In standard forms, we mapped the information about weight to the criterion's `.description`.

**Comment by ColinMaudry** [comment]
I see we have created this structure for [award criteria](https://extensions.open-contracting.org/en/extensions/awardCriteria/master/). Should we apply it to selection criteria?

**Comment by jpmckinney** [comment]
Yes, I think we can re-use the same structure.

**Comment by duncandewhurst** [comment]
The [award criteria extension](https://extensions.open-contracting.org/en/extensions/awardCriteria/master/) adds codelists for [criterionWeight](https://extensions.open-contracting.org/en/extensions/awardCriteria/master/codelists/#criterionWeight.csv) and [criterionThreshold](https://extensions.open-contracting.org/en/extensions/awardCriteria/master/codelists/#criterionThreshold.csv) which seem to be equivalent to eForms' [number-weight](https://op.europa.eu/en/web/eu-vocabularies/concept-scheme/-/resource?uri=http://publications.europa.eu/resource/authority/number-weight) and [number-threshold](https://op.europa.eu/en/web/eu-vocabularies/concept-scheme/-/resource?uri=http://publications.europa.eu/resource/authority/number-threshold) codelists, respectively, but with camelCase codes, such as 'percentageExact', in place of the eForms codes, which look like 'per-exa', for example.

Do we need to document a mapping from the the eForms codes to the OCDS codes, or is it sufficient to say something along the lines of "...identify the equivalent code from the [criterionWeight](https://extensions.open-contracting.org/en/extensions/awardCriteria/master/codelists/#criterionWeight.csv) codelist and map it to..."?

**Comment by jpmckinney** [comment]
That sounds fine, assuming the codelists are 1-to-1.

**Comment by duncandewhurst** [comment]
The codes are 1-to-1. The only differences are that:

* The [criterionWeight](https://extensions.open-contracting.org/en/extensions/awardCriteria/master/codelists/#criterionWeight.csv) codelist has descriptions for each code, some of which include normative rules like "The numbers must add up to 100.", however, the eForms [number-weight](https://op.europa.eu/en/web/eu-vocabularies/concept-scheme/-/resource?uri=http://publications.europa.eu/resource/authority/number-weight) codelist has no such descriptions or rules.
* The [criterionThreshold](https://extensions.open-contracting.org/en/extensions/awardCriteria/master/codelists/#criterionThreshold.csv) codelist has 'maximumBids' in place of 'max-pass' in the [number-threshold](https://op.europa.eu/en/web/eu-vocabularies/concept-scheme/-/resource?uri=http://publications.europa.eu/resource/authority/number-threshold) codelist. The codes have different descriptions, but I think the semantics are essentially the same:
  * 'maximumBids':  The number is the maximum number of bids that can pass the criterion. For example: "A bid must receive one of the highest 3 scores for criterion X."
  * 'max-pass': The highest number of tenders passing the selection or award criterion

I don't know where the descriptions in the criterionWeight codelist came from.

**Comment by jpmckinney** [comment]
I can't remember the origin. Colin and I might have invented them based on what was available at the time.

**Comment by duncandewhurst** [comment]
Shall I open an issue to remove the extra normative rules from the codelist descriptions or are you happy to keep them at the risk of some eForms data not complying to the rules?

**Comment by jpmckinney** [comment]
I think it's fine. There may very well be eForms validations that enforce these rules – I haven't checked their schematron, etc.

**Comment by jpmckinney** [comment]
Mapped as discussed. As I undestand, no change is needed to the existing extension's codelists.
