### ISSUE TITLE
BT-651 Subcontracting Tender Indication

### ISSUE THREAD

**Issue by ColinMaudry** [open-contracting/european-union-support#74]
BT-651 "Subcontracting Tender Indication" is an array of codes ([values](https://op.europa.eu/en/web/eu-vocabularies/concept-scheme/-/resource?uri=http://publications.europa.eu/resource/authority/subcontracting-indication)). 

Description:

> The information about subcontracting that must be indicated in the tender.

In OCDS, the [subcontracting extension](https://extensions.open-contracting.org/en/extensions/subcontracting/master/) has `tender.subcontracting.description`, but it matches better with BT-554 Subcontracting Description. 

We could cram BT-651 Subcontracting Tender Indication in `tender.subcontracting.description`, asking implementers to append the label or labels from [the codelist](https://op.europa.eu/en/web/eu-vocabularies/concept-scheme/-/resource?uri=http://publications.europa.eu/resource/authority/subcontracting-indication).

Or we add a new field to the subcontracting extension.

Related to #75

**Comment by ColinMaudry** [comment]
Discussed with James: we add a `.subcontractingClauses` field to `tender.submissionTerms` (and `lot`). It's an array of text strings that expects codes from an open codelist that is initiated with [the EU codelist](https://op.europa.eu/en/web/eu-vocabularies/concept-scheme/-/resource?uri=http://publications.europa.eu/resource/authority/subcontracting-indication).

**Comment by jpmckinney** [comment]
@odscjen The OCDS example doesn't match the guidance for this BT 1aeb4bb6

**Comment by odscjen** [comment]
fixed https://github.com/open-contracting/european-union-support/commit/d6392bd1c8e1f12ae2ff0b55212750cd3825b4bd

**Comment by duncandewhurst** [comment]
I'm not sure the semantics of the codes in the [EU codelist](https://op.europa.eu/en/web/eu-vocabularies/concept-scheme/-/resource?uri=http://publications.europa.eu/resource/authority/subcontracting-obligation) fit the semantics of `tender.submissionTerms` (Information about the submission terms to describe how, when and where the tenderers need to submit their bids). The codes seem like better fit for the `tender.subContractingTerms` (Information about the terms governing subcontracting).

@jpmckinney what do you think?

**Comment by jpmckinney** [comment]
For BT-651, the codelist is [subcontracting-indication](https://op.europa.eu/en/web/eu-vocabularies/concept-scheme/-/resource?uri=http://publications.europa.eu/resource/authority/subcontracting-indication), not [subcontracting-obligation](https://op.europa.eu/en/web/eu-vocabularies/concept-scheme/-/resource?uri=http://publications.europa.eu/resource/authority/subcontracting-obligation).

**Comment by duncandewhurst** [comment]
Ah, my mistake! Thanks for clarifying.
