### ISSUE TITLE
BG-44 Prize

### ISSUE THREAD

**Issue by ColinMaudry** [open-contracting/european-union-support#76]
eForms adds more details to the prizes that are awarded at a contest. The BTs are grouped in BG-44 Prize.

From [official examples](https://github.com/OP-TED/eForms-SDK/blob/main/examples/notices/cn-desg_24.xml#L271):

```xml
<cac:AwardingTerms>
	<cac:Prize>
  			<cbc:RankCode>1</cbc:RankCode>
  			<cbc:ValueAmount currencyID="EUR">10000</cbc:ValueAmount>
  			<cbc:Description languageID="FRA">Une indemnité forfaitaire d'un montant identique à celui versé aux concurrents non retenus sera payée à l'équipe lauréate sous forme d'avance sur le marché de maîtrise d'œuvre dès l'issue du concours; cette somme étant à valoir sur le montant des honoraires à percevoir ultérieurement au titre du marché de maîtrise d'œuvre.</cbc:Description>
 		</cac:Prize>
 		<cac:Prize>
  			<cbc:RankCode>>= 1</cbc:RankCode>
  			<cbc:ValueAmount currencyID="EUR">10000</cbc:ValueAmount>
  			<cbc:Description languageID="FRA">Les trois concurrents (candidats admis à concourir) recevront une indemnisation forfaitaire maximale de 10 000 EUR HT. Pour les prestations fournies, sous réserve de la recevabilité de leurs prestations au regard du règlement du concours et du respect du programme. Les indemnisations sont forfaitaires, conformément aux dispositions de l'article R. 2172-4 du code de la commande publique, l'acheteur, sur proposition du jury, se réserve le droit, dans le cas d'un projet qu'il jugerait incomplet ou dont les prestations seraient non conformes par rapport au règlement de concours et ou au programme, de supprimer totalement ou partiellement l'indemnité.</cbc:Description>
		</cac:Prize>
</cac:AwardingTerms>
```

Currently, the [design contest extension](https://extensions.open-contracting.org/en/extensions/designContest/master/) only has `.prizes.description`. We may need an array of Prize objects.

**Comment by ColinMaudry** [comment]
Discussed with James: ok to use an array of prizes in the design contest extension.

**Comment by ColinMaudry** [comment]
It could look like this, following the model of bids:

```json
 "tender": {
    "designContest": {
      "selectedParticipants": [
        {
          "id": "1",
          "name": "Brigitte Hermon"
        },
        {
          "id": "2",
          "name": "Paolo Travino"
        }
      ],
      "hasPrizes": true,
      "prizes": {
        "description": "The winner(s), as well as each unsuccessful competitor who has provided services which meet the program, will receive, subject to the decision of the contracting authority, a prize of EUR 16,500.00 (VAT free).",
		"details": [
			{
				"id": "1",
				"value": {
					"amount": 10000,
					"currency": "EUR"
				}
			},
			{
				"id": "2",
				"value": {
					"amount": 5000,
					"currency": "EUR"
				}
			}
		]
      }
}
```

It's worth noting that, contrary to standard forms, eForms has per prize data, not for all prizes. 

For instance

```
"bindingJuryDecision": `true`
```

applies to all prizes in standard forms, but to a single prize in eForms. To support eForms, this field and others should be moves to Prize objects in the `.designcontest.prizes.details` array, but how to we adapt standard forms guidance?

**Comment by ColinMaudry** [comment]
We could also have both global fields for the whole design contest, and per prize fields.

**Comment by jpmckinney** [comment]
Yes, I think we can have both global and per-prize fields. The sample JSON looks good.

**Comment by ColinMaudry** [comment]
Thanks! 🙏🏻

**Comment by odscjen** [comment]
Noting here that BT-45 is also covered in the official example given in the opening comment but not in the example `details` array. To cover this could add in `.details.description`. This BT is used in the case where the prize doesn't have a monetary value (BT-644).

**Comment by jpmckinney** [comment]
Mapped as discussed.

**Comment by jpmckinney** [comment]
I think you're right - they are for the entire award, not individual prizes.
