### ISSUE TITLE
BT-759, BT-760: Bid submission statistics codes

### ISSUE THREAD

**Issue by ColinMaudry** [open-contracting/european-union-support#78]
eForms enables the publication of statistics through the BT pair BT-759 Received Submissions Count / BT-760 Received Submissions Type (nb of submissions, type of submissions ([codelist](https://op.europa.eu/en/web/eu-vocabularies/concept-scheme/-/resource?uri=http://publications.europa.eu/resource/authority/received-submission-type))).

Example:

```xml
	<efac:ReceivedSubmissionsStatistics>
		<efbc:StatisticsCode listName="received-submission-type">tenders</efbc:StatisticsCode>
		<efbc:StatisticsNumeric>5</efbc:StatisticsNumeric>
	</efac:ReceivedSubmissionsStatistics>
	<efac:ReceivedSubmissionsStatistics>
		<efbc:StatisticsCode listName="received-submission-type">t-sme</efbc:StatisticsCode>
		<efbc:StatisticsNumeric>4</efbc:StatisticsNumeric>
	</efac:ReceivedSubmissionsStatistics>
	<efac:ReceivedSubmissionsStatistics>
		<efbc:StatisticsCode listName="received-submission-type">t-oth-eea</efbc:StatisticsCode>
		<efbc:StatisticsNumeric>0</efbc:StatisticsNumeric>
	</efac:ReceivedSubmissionsStatistics>
	<efac:ReceivedSubmissionsStatistics>
		<efbc:StatisticsCode listName="received-submission-type">t-no-eea</efbc:StatisticsCode>
		<efbc:StatisticsNumeric>0</efbc:StatisticsNumeric>
	</efac:ReceivedSubmissionsStatistics>
	<efac:ReceivedSubmissionsStatistics>
		<efbc:StatisticsCode listName="received-submission-type">t-esubm</efbc:StatisticsCode>
		<efbc:StatisticsNumeric>5</efbc:StatisticsNumeric>
	</efac:ReceivedSubmissionsStatistics>
```

The OCDS bid extension [has codes](https://extensions.open-contracting.org/en/extensions/bids/master/codelists/) for most of the eForms codes, but the following eForms codes have no straight match yet ([current mapping table](https://github.com/open-contracting/european-union-support/blob/eForms/output/mapping/eForms/mapping-tables/submission-count-types.csv)):

- t-med (Tenders from medium tenderers)
- t-small (Tenders from small tenderers)
- t-micro (Tenders from micro tenderers)
- t-no-verif (Tenders for which it has not been verified if they are admissible or inadmissible)
- t-verif-inad (Tenders verified and inadmissible)

For the micro/small/med codes, we could suggest implementers that they sum them up and add them as `smeBids` in OCDS.

**Comment by jpmckinney** [comment]
Like we did with [party scale](https://extensions.open-contracting.org/en/extensions/partyScale/master/codelists/), we can add codes for micro, small and medium, in addition to the existing sme code.

**Comment by jpmckinney** [comment]
This has been mapped as above.
