### ISSUE TITLE
BT-171 Tender Rank

### ISSUE THREAD

**Issue by ColinMaudry** [open-contracting/european-union-support#80]
Through BT-171 Tender Rank, eForms supports the ranking of bids with number field:

> The position of the tender (i.e. whether the tender ended up first, second, third, etc.) in a design contest, some framework agreements with multiple winners (e.g. cascades) or an innovation partnership.

This could be added in the bids extension.

**Comment by ColinMaudry** [comment]
Cascade: number 1 is the winner, but if they don't comply, the buyer switches to number 2, etc.

**Comment by ColinMaudry** [comment]
```json
"awards": [
	{
		"cascade": [
			{
				"bidId": "213",
				"suppliers": [ 
					"3434"
				]
			}
		]
]

```

**Comment by ColinMaudry** [comment]
This would go in a new cascade extension.

**Comment by jpmckinney** [comment]
@ColinMaudry If we are merging `competitive` into `techniques`, should we also add cascades there? https://github.com/open-contracting/ocds-extensions/issues/174

**Comment by ColinMaudry** [comment]
Since cascade also applies to design contests, we said it might be wiser to have it as an independent extension.

**Comment by jpmckinney** [comment]
Oh, right, I forgot that was the reason!

**Comment by odscjen** [comment]
BT-171 is a field that can be withheld from publication. There doesn't appear to be any guidance suggesting that all bid ranks must be withheld for an award notice, it could theoretically be withheld for just some of the bids (although that would be weird as if the rank was only withheld for one bid it could presumably be inferred from the others). But if we assume a case where some are withheld and some aren't then this cascade option ceases to work as the position in the array will not be reflective of the actual rank position.

Alternatively if we are wanting to keep this structure then the OCDS mapping for withheld information for this BT will need to apply to ALL instances of the BT in a notice regardless of their actual status, and only publish them after the latest associated publication date. Which would be withholding information that isn't actually withheld in the original non-OCDS publication.

@jpmckinney what do you think?

**Comment by jpmckinney** [comment]
Per discussion in #125, I think we can avoid this knotty issue by adding fields to bids instead of creating a `cascade` array.

**Comment by jpmckinney** [comment]
Mapped per Jen's comment.
