### ISSUE TITLE
BT-165 Winner size

### ISSUE THREAD

**Issue by ColinMaudry** [open-contracting/european-union-support#81]
Description:

> The size of the winner, tenderer or subcontractor (e.g. micro enterprise, small enterprise, medium enterprise).

The organization classification is a great match for this one, but do we have a codelist for company size?

**Comment by yolile** [comment]
Maybe the party scale extension https://extensions.open-contracting.org/en/extensions/partyScale/master/?

**Comment by ColinMaudry** [comment]
Great, and the codes match eForms'! https://op.europa.eu/en/web/eu-vocabularies/concept-scheme/-/resource?uri=http://publications.europa.eu/resource/authority/economic-operator-size
