### ISSUE TITLE
BT-193 Tender Variant

### ISSUE THREAD

**Issue by ColinMaudry** [open-contracting/european-union-support#82]
Description:

> The tender is a variant.

Variants are bids that "fulfil the buyer's needs differently than as proposed in the procurement documents" (BT-63 Variants).

BT-193 Tender Variant enables the possibililty to tag a bid as being a variant with a boolean.

**Comment by ColinMaudry** [comment]
Discussed with James: we can add this boolean to the bid extension.

**Comment by jpmckinney** [comment]
This has been mapped as a bid's `.variant` boolean.
