### ISSUE TITLE
BT-1251 Previous Planning Part Identifier

### ISSUE THREAD

**Issue by ColinMaudry** [open-contracting/european-union-support#83]
> The identifier of a part of a prior information notice or another similar notice related to this notice.*

The Xpath is  `/*/cac:ProcurementProjectLot/cac:TenderingProcess/cac:NoticeDocumentReference/cbc:ReferencedDocumentInternalAddress`.

@JachymHercher mentions it in [the eForms issues](https://github.com/eForms/eForms/issues/269#issuecomment-475561237). In OCDS, I think it means it's a lot identifier in any case.

**Comment by ColinMaudry** [comment]
BT-1371 Previous Planning Lot Identifier seems to be exactly that: a reference to the lot in the PIN (planning phase). But then, in OCDS context, it seems they have the same semantics since it's lots all along. But lots in *another* procedure (planning).

**Comment by jpmckinney** [comment]
Note that in 1.2, we will have planning in a separate contracting process (ocid), so the reference will be across contracting processes.

**Comment by ColinMaudry** [comment]
Yep, that's what I meant

> Lots in *another* procedure (planning).

**Comment by ColinMaudry** [comment]
I think it's the first time I see the need to refer to a specific lot in another process. Could we add a `lotId` field to the Related process object?

**Comment by ColinMaudry** [comment]
Discussed with James: we add a `relatedLot` array of lot Id's in the Related Process object.

**Comment by odscjen** [comment]
This works for BT-1251-Lot but it was [previously agreed in slack](https://opencontractingint.slack.com/archives/C03S8JL100P/p1659993707218009?thread_ts=1659911924.382459&cid=C03S8JL100P) to treat Parts in eForms as seperate OCIDs. If the eForms XML looks like:

```xml
<cac:NoticeDocumentReference>
    <cbc:ID schemeName="notice-id-ref">123e4567-e89b-12d3-a456-426614174000-06</cbc:ID>
    <cbc:ReferencedDocumentInternalAddress>PAR-0001</cbc:ReferencedDocumentInternalAddress>
    <cbc:ReferencedDocumentInternalAddress>PAR-0003</cbc:ReferencedDocumentInternalAddress>
</cac:NoticeDocumentReference>
```

where `cbc:ID` is BT-125 and already mapped to `relatedProcess.identifier` as per [Reference a previous publication](operations.md#reference-a-previous-publication).

We could still just add `<cbc:ReferencedDocumentInternalAddress>PAR-0003</cbc:ReferencedDocumentInternalAddress>` to `relatedLots` but this risks introducing semantic confusing over parts.

@jpmckinney

**Comment by jpmckinney** [comment]
Ah, indeed. Do we just map BT-1251 similarly to BT-125 then?

**Comment by duncandewhurst** [comment]
I think so, although the mapping for BT-125 is simply a link to the guidance on referencing a previous publication, which I haven't yet checked.

**Comment by odscjen** [comment]
The guidance for BT-125 works for that BT as it's just a link to the actual notice ID. 

If we were to map BT-1251-Part as per BT-125 then really what we're saying is to discard BT-1251-Part as it's just the Part ID can't exist without BT-125 as it wouldn't make any sense, e.g. it would be identifying PAR-0001 but with no information about what it's a Part of.

OR should the advise be to concatenate BT-125-Part and BT-1251-Part to create an identifier that says which Part of the notice it is? e.g. 

```json
{
    "relatedProcess": [
        {
            "id": "1",
            "relationship": [
                "planning"
            ],
            "scheme": "eu-oj",
            "identifier": "123e4567-e89b-12d3-a456-426614174000-06-PAR-0001"
        }
    ]
}
```

**Comment by jpmckinney** [comment]
Ah, I think I get it now. To summarize:

In eForms, BT-125 points to a notice, and BT-1251 points to a part of that notice.

In OCDS, we split parts of notices into separate OCIDs (i.e. whatever OCID is assigned ends up corresponding to the pair of BT-125 and BT-1251), and there is no overall notice that survives in OCDS data.

So, for the 'eu-oj' scheme, I think I prefer concatenating BT-125 and BT-1251 in `relatedProcess.identifier` to make both references at once. We could split them out, but that'd require an additional field on RelatedProcess without clear benefit.

**Comment by odscjen** [comment]
Great, that all seems sensible.

So the guidance for BT-125-Part and BT-1251-Part will both be to concatenate them. 

For BT-1251-Lot the current guidance is to add `relatedLots` to `relatedProcess`. It might be more consistent to also concatenate the BT's in the case of Lots as well?

**Comment by jpmckinney** [comment]
Hmm, with BT-1251-Lot, in both eForms and OCDS, there is a section within the previous notice/related process that represents the lot. So, I think it's handy to split this one out.
