### ISSUE TITLE
BT-634: procurement relaunch

### ISSUE THREAD

**Issue by ColinMaudry** [open-contracting/european-union-support#84]
> This cancelled or unsuccessful competition will be relaunched.

Boolean

Not sure what to do with this one: whether to store it and where to store it.

**Comment by jpmckinney** [comment]
This one seems a bit odd. On what notice / section does this boolean appear?

It seems odd to announce a future competition from a failed competition – it seems preferable to always announce future competitions in the same way. I don't know if we maybe just model this in the EU extension for now.

**Comment by odscjen** [comment]
This is a boolean but from the guidance it seems it will only appear if it is 'true'. It occurs in the `cac:TenderingProcess` section and can apply to either the entire `tender` or an individual `lot`. 

Looking at an [example CAN notice](https://github.com/OP-TED/eForms-SDK/blob/develop/examples/notices/can_24_maximal.xml) when this BT is included it's followed up with BT-125-i, Previous Process Identifier. So it appears to be less that it's saying an unsuccessful process WILL be relaunched and more that this tender IS a relaunch of a previous unsuccessful process. I think therefore we can discard this boolean, if it's 'true' then BT-125-i will cover the reference to a previous publication and anyone looking at that previous publication will see that it was unsuccessful.

@jpmckinney what do you think?

**Comment by jpmckinney** [comment]
@odscjen That sounds good to me. If we learn otherwise, we can revisit the modelling.

**Comment by jpmckinney** [comment]
Discarded as discussed.
