### ISSUE TITLE
BT-726: Suitable For SMEs

### ISSUE THREAD

**Issue by ColinMaudry** [open-contracting/european-union-support#85]
> The buyer emphasizes that this procurement is also suitable for small and medium enterprises (SMEs).

Boolean

I guess we could add a `procurementSuitableFor` **array** field in the communication extension and bind it to the [party scale codelist](https://extensions.open-contracting.org/en/extensions/partyScale/master/codelists/).

**Comment by jpmckinney** [comment]
@ColinMaudry You can have a look at https://github.com/open-contracting/standard/issues/1102

**Comment by jpmckinney** [comment]
This has been mapped according to the linked issue.
