### ISSUE TITLE
BT-191: Item country of origin

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/european-union-support#94]
Belarus draft data includes an additional `productCountry` field in `contract/items` for the country where goods were created. Helpdesk feedback suggested renaming to `countryOfOrigin`.

**Comment by jpmckinney** [comment]
Mapped as a bid's `.countryOfOrigin`.

**Comment by odscjen** [comment]
not sure why it was still unreviewed, reviewed now and closing

**Comment by duncandewhurst** [comment]
Noting that BT-191-Tender is repeatable and, in `guidance.yaml`, `bids.details.countryOfOrigin` is an array. Therefore, according to the style guide, the OCDS field should be plural: `countriesOfOrigin`.

I don't see any data from Belarus in the registry so I don't think we're breaking anything by changing the field name and, in any case, the field is on `Bid` not `Item`.

**Comment by duncandewhurst** [comment]
Also noting some other issues with the first sentence of the mapping in `guidance.yaml`:

> Look up the equivalent ISO 3166-1 alpha-2 code in the [authority table](https://op.europa.eu/en/web/eu-vocabularies/concept-scheme/-/resource?uri=http://publications.europa.eu/resource/authority/country) and convert to lowercase.
> [Get the bid for a LotTender](operations.md#get-the-bid-for-a-lottender) and add to the bid's `.countriesOfOrigin` array.

* The use of lowercase codes is inconsistent with the [OCDS 1.2 Country codelist](https://standard.open-contracting.org/staging/1.2-dev/en/schema/codelists/#country), which uses uppercase codes.
* The guidance doesn't explain what to do in the case of Kosovo, for which there is no ISO 3166-1 alpha-2 code for Kosovo in the EU's [Country authority table](https://op.europa.eu/en/web/eu-vocabularies/concept-scheme/-/resource?uri=http://publications.europa.eu/resource/authority/country).

Therefore, I've updated the guidance to read:

> 1. [Get the bid for a LotTender](operations.md#get-the-bid-for-a-lottender).
> 2. If the value of the field is `1A0` (Kosovo), add 'XK' to the bid's `.countriesOfOrigin` array. Otherwise, look up the equivalent ISO 3166-1 alpha-2 code in the [authority table](https://op.europa.eu/en/web/eu-vocabularies/concept-scheme/-/resource?uri=http://publications.europa.eu/resource/authority/country) and map to the bid's `.countriesOfOrigin` array.

@jpmckinney FYI
