### ISSUE TITLE
Review output/mapping/eforms/mapping-tables/

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/european-union-support#98]
These should be integrated directly into `guidance.yaml`. See e.g. BT-03-notice and BT-105-Procedure

**Comment by duncandewhurst** [comment]
@jpmckinney should we still inline the mapping tables? In most cases, the tables are linked to but not embedded in the guidance, e.g. in the guidance for BT-5422-LotsGroup:

> - For each `efac:AwardCriterionParameter`, add or update a corresponding `AwardCriterionNumber` in the award criterion's `.numbers` array and map the code to the award criterion number's `.fixed` according to the [award criterion fixed mapping table](codelists/number-fixed).

**Comment by jpmckinney** [comment]
I think it's fine to leave them separate, especially since some are referenced more than once. There are two that use bullets instead of mapping tables:

* BT-03-notice
* BT-105-Procedure

I guess these should become tables?

**Comment by duncandewhurst** [comment]
I've created tables for those fields and updated `guidance.yaml` accordingly (0571d24bf8b9e796f8c9c8fcc0cc4ae425513619).
